### ISSUE TITLE
CLI subcommands for reading any program account in a workspace

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#1]
We should add an `anchor account <program>.<account> <address>` command that allows one to fetch any account in the workspace via CLI (by reading all IDLs).

**Comment by armaniferrante** [comment]
It would be nice if this used the on-chain IDL, if none is given.

**Comment by paul-schaaf** [comment]
could also have an `--idl` option to specify the filepath to an idl file so that it cna be used outside a workspace

**Comment by AdithyaNarayan** [comment]
Surprised that issue number 1 is still up for grabs!
