### ISSUE TITLE
Can't provide Program with idl.json

### ISSUE THREAD

**Issue by bweickert** [coral-xyz/anchor#1002]
when using 

`import idl from "./idl.json";

`new Program(idl, programID, provider)`

it is throwing the following error: 
`Argument of type '{ version: string; name: string; instructions: { name: string; accounts: { name: string; isMut: boolean; isSigner: boolean; }[]; args: { name: string; type: string; }[]; }[]; accounts: { name: string; type: { kind: string; fields: ({ ...; } | { ...; })[]; }; }[]; types: { ...; }[]; metadata: { ...; }; }' is not assignable to parameter of type 'Idl'.`

I have taken the idl.json from my anchor build as is. What am I doing wrong?

**Comment by Aadhinana** [comment]
Looks like a TS problem. Re check IDL types that you're trying to use. The type of `Idl` defiend by anchor doesn't seem to match with your import as the code error says.

**Comment by atob1** [comment]
I'm having the same issue--were you able to fix it?

**Comment by nukec** [comment]
same issue

**Comment by BruceMacD** [comment]
A workaround for anyone facing this is to suppress the error using `ts-ignore`. It should still work as expected at runtime.
```
// @ts-ignore
const program = new Program(idl, programID, provider)
```

The actual fix is probably to update the types file, but this works for now.

**Comment by bweickert** [comment]
I have found no solution. The idl is copied over from the generated one after the build. 

> A workaround for anyone facing this is to suppress the error using `ts-ignore`. It should still work as expected at runtime.
> 
> ```
> // @ts-ignore
> const program = new Program(idl, programID, provider)
> ```
> 
> The actual fix is probably to update the types file, but this works for now.

I have found no solution other than use an earlier version of anchor web3. 
The idl is copied over from the generated one after the build. 
The above mentioned solution is working for now.

**Comment by biw** [comment]
This can be fixed by importing from `./target/types/[program-name].ts`, rather than from `./target/idl/[program-name].json`

So, in typescript you would do:

```ts
import { IDL } from '../target/types/[program-name]'

const program = new new Program(IDL, programID, provider)
```
