### ISSUE TITLE
IDL does not reflect types in libraries

### ISSUE THREAD

**Issue by juliotpaez** [coral-xyz/anchor#1058]
I'm developing a project that is composed of three contracts. These contracts have in common a couple of types that I moved to a Rust library. Everything works well but the types are ignored by the IDL generator, throwing a `IdlError: Type not found` error.

Is there any way to include in the IDL types in another Rust library?

Thanks in advance.

**Comment by armaniferrante** [comment]
Related to https://github.com/project-serum/anchor/issues/454.

**Comment by edmbn** [comment]
@juliotpaez I have a very similar use case and didn't find anything either here or discord. Did you find any workaround/solution to this or the only way to go is to redefine the types in every program separately? Thank you.

**Comment by edmbn** [comment]
Thank you @juliotpaez, as I thought we have to add them everywhere. Hopefully we will have a fix soon.

**Comment by Henry-E** [comment]
This is a known issue but maybe if we're lucky kklas's new IDL code might fix this, I still have to check it out.

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2824.
