### ISSUE TITLE
Jest as default test runner?

### ISSUE THREAD

**Issue by jeduan** [coral-xyz/anchor#1069]
I was wondering if there's a bit more context on the choice of mocha as the default test runner. 
Seems like this project uses jest itself. Jest is better at running suites in parallel, so it has made things speedier on my test projects. One of them went from running tests in 25 seconds to 11 seconds.

Would we consider switching to jest?

**Comment by fanatid** [comment]
`tape` also allows parallel testing, should we change to `tape`? (at least it's not polluting global with its own functions and can be run by node binary)

Does `jest` provide any other benefits except parallel tests? It would be good to compare CI time with `mocha`.

**Comment by armaniferrante** [comment]
No context. The decision wasn't particularly thoughtful. Happy to switch to whatever is in vogue. I've never used `tape` before and am not familiar with the benefits.

**Comment by jeduan** [comment]
Thanks for getting back to me and getting started on this discussion. 

The way I'd think about the decision is this project should solve for

 - Ease of configuration: we don't want to spend a lot of time tinkering with config
 - Ease of onboarding: I expect many new users to come, with varying skill levels
 - Runtime: I expect the number of complexity, and thus, tests in this project to rise. In my computer I routinely have ~500ms latency for `test-validator` queries to resolve, so running tests concurrently is paramount.

As how I think about `jest`:

`jest` Pros:
 - Installed base. Looking at https://www.npmtrends.com/jest-vs-mocha-vs-tape-vs-ava I see ~14M downloads a week for `jest`, vs 5M for `mocha` and ~700k for `tape`.
 - Lots of companies already use it, so expertise in scaling is available. Facebook uses it for their monorepo and we use it on Airbnb to run thousands of suites in ours.
 - Lots of tutorials, so the community has other avenues to ask questions. StackOverflow has [17k questions](https://stackoverflow.com/questions/tagged/jestjs). Mocha has around [8k questions](https://stackoverflow.com/questions/tagged/mocha.js). 
 - Its docs are pretty good and offer answers to common questions like [how to test async code](https://jestjs.io/docs/asynchronous)
 - Jest has a batteries included philosophy, so most of the times it requires very little configuration.

`jest` Cons:
 - Injects globals by default. Can be switched with `--injectGlobals=false` https://jestjs.io/docs/configuration#injectglobals-boolean
 - It's not as minimalistic as other frameworks like ava and tape, so it can have a higher overhead.


Now, honestly, after going through a bit more of research, keeping `mocha` and tweaking the configs to add parallel tests it's a pretty decent option as well. I found this [pretty in depth comparison](https://github.com/scraggo/comparing-javascript-test-runners) where mocha comes out pretty well.

**Comment by fanatid** [comment]
`tape` is super unpopular but a good old project, `mocha` and `jest` wins today. I still choose `tape` today because do not need `snapshots` for example, it really works very well and is pretty lightweight IIRC.
I did not knew that `jest` allows disables injecting globals, that is good news! :+1: 

Generally, I'm ok with any test framework. What is important:
- maintainability (how many maintainers / developers comfortable can work with it, understand pros / cons of it)
- simplicity and easiest usage
- test framework performance

Probably, right now parallel `mocha` looks the best choice. But happy to switch to another if there will be enough benefits.

**Comment by tomlinton** [comment]
Parallelisation of tests seems a bit constrained by the `solana-test-validator` and it's inability to reset state or load state data from a snapshot. Some of the tests we use require sequential execution of the test suite.

Are you running tests against the test validator concurrently @jeduan? Is there a smarter way to manage the state required by each test that doesn't require sequential execution?

I don't see a strong reason to switch unless we solve https://github.com/project-serum/anchor/issues/637 or there is some smarter way to parallelise things that I'm not familiar with.

**Comment by Necmttn** [comment]
I think the strategy to solve parallel test execution could be (ref #637): 
Use the workspace to dynamically deploy the program per test suite.
so we could run test suites parallel, and have the sequential state test still valid.

And in terms of test framework, I do agreed with @jeduan

**Comment by ron-liu** [comment]
I just want to share [the article](https://medium.com/solana-fun/how-to-switch-test-runner-to-jest-instead-of-mocha-in-anchor-99e6035a3940) I wrote showing how to switch to jest runner.

**Comment by Henry-E** [comment]
We now have jest as an option. Eventually maybe we will switch to it being the default.
