### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by rbjamaca** [coral-xyz/anchor#1082]
Are you planning on creating a version that supports react native? Or are there any resources we can follow to make it work?

**Comment by safaiyeh** [comment]
I left a comment here to get it to build https://github.com/project-serum/anchor/issues/864#issuecomment-968104501

**Comment by saicharanpogul** [comment]
```
const tx = await program.rpc.setData(
        'data'
        {
          accounts: {
            data: pda,
            user: provider.wallet.publicKey,
            systemProgram: anchor.web3.SystemProgram.programId,
          },
          signers: [],
        },
      );
```
When I call the above instruction, I get this error ```undefined is not a constructor (evaluating 'new a.Transaction()')``` 
I was getting similarly undefined is not a constructor error for anchor node wallet too. 

```
const wallet = new anchor.Wallet(keyPair);

// TypeError: undefined is not a constructor 
// (evaluating 'new (_$$_REQUIRE(_dependencyMap[9], "@project-serum/anchor").Wallet)(keyPair)')
```
so I had to change it to - 
```
anchor.Wallet = keyPair;
const wallet = anchor.Wallet;
```
There's some issue with module exports maybe as I'm using ```require('@project-serum/anchor')``` instead of import. When I use import I get this error -
```
TypeError: undefined is not an object (evaluating '_anchor.default.Wallet = keyPair')
```

**Comment by raj-khare** [comment]
@saicharanpogul did you find any solution?

**Comment by saicharanpogul** [comment]
> @saicharanpogul did you find any solution?

No, I just tried again with new APIs of v0.24.2 and also asked the same in Anchor's Discord and this is not the first time, I asked several times. Seems like no one from the community and even core developers are interested in React Native queries and issues!

**Comment by raj-khare** [comment]
@saicharanpogul it looks like the tx is failing at this line: https://github.com/project-serum/anchor/blob/master/ts/src/program/namespace/transaction.ts#L18-L19

**Comment by saicharanpogul** [comment]
> @saicharanpogul it looks like the tx is failing at this line: https://github.com/project-serum/anchor/blob/master/ts/src/program/namespace/transaction.ts#L18-L19

Yes

**Comment by saicharanpogul** [comment]
@raj-khare Check if this helps you.
https://stackoverflow.com/a/70964609/4687973

**Comment by raj-khare** [comment]
@saicharanpogul thanks, it worked when i removed the `terser` plugin 🚀

**Comment by saicharanpogul** [comment]
> @saicharanpogul thanks, it worked when i removed the `terser` plugin 🚀 

Great, can you share here how you removed the terser plugin exactly.

**Comment by raj-khare** [comment]
@saicharanpogul 
1. Fork the anchor repo
2. Comment/Remove this line: https://github.com/project-serum/anchor/blob/master/ts/rollup.config.ts#L33
3. run `cd ts && yarn && yarn run build:browser`
4. copy the `dist/` folder to your own project
5. instead of doing `import * anchor from "@project-serum/anchor`, do `import * anchor from "./dist/index"`

**Comment by saicharanpogul** [comment]
> @saicharanpogul 
> 1. Fork the anchor repo
> 2. Comment/Remove this line: https://github.com/project-serum/anchor/blob/master/ts/rollup.config.ts#L33
> 3. run `cd ts && yarn && yarn run build:browser`
> 4. copy the `dist/` folder to your own project
> 5. instead of doing `import * anchor from "@project-serum/anchor`, do `import * anchor from "./dist/index"`

Are you able to create instance of ```Wallet``` and pass it ```AnchorProvider```?

**Comment by mordonez-me** [comment]
> @saicharanpogul
> 
> 1. Fork the anchor repo
> 2. Comment/Remove this line: https://github.com/project-serum/anchor/blob/master/ts/rollup.config.ts#L33
> 3. run `cd ts && yarn && yarn run build:browser`
> 4. copy the `dist/` folder to your own project
> 5. instead of doing `import * anchor from "@project-serum/anchor`, do `import * anchor from "./dist/index"`

This solution worked perfect! Thanks @raj-khare. Would be awesome if support for RN is added so we don't have to do this.

**Comment by mordonez-me** [comment]
@saicharanpogul you can add the wallet on the generated file, like this:

![image](https://user-images.githubusercontent.com/2242042/171237412-6ed93858-e045-430a-994c-e125bc670bf0.png)

**Comment by devenus98** [comment]
> @saicharanpogul
> 
> 1. Fork the anchor repo
> 2. Comment/Remove this line: https://github.com/project-serum/anchor/blob/master/ts/rollup.config.ts#L33
> 3. run `cd ts && yarn && yarn run build:browser`
> 4. copy the `dist/` folder to your own project
> 5. instead of doing `import * anchor from "@project-serum/anchor`, do `import * anchor from "./dist/index"`

which version did you use?
I cannot find it, https://github.com/project-serum/anchor/blob/master/ts/rollup.config.ts#L33.

**Comment by Plitskine** [comment]
@devenus98 it has moved to https://github.com/coral-xyz/anchor/tree/master/ts

Good luck...

**Comment by nakuldropchain** [comment]
> @devenus98 it has moved to https://github.com/coral-xyz/anchor/tree/master/ts
> 
> Good luck...

which line needs commenting out now?

**Comment by faisalKhan-99** [comment]
> @devenus98 it has moved to https://github.com/coral-xyz/anchor/tree/master/ts
> 
> Good luck...

which line needs commenting out now?
