### ISSUE TITLE
IDL doesn't generate correct types for enum args

### ISSUE THREAD

**Issue by dominictwlee** [coral-xyz/anchor#1085]
The namespaced RPC method doesn't seem to create the correct type definitions for an enum arg type. 

An enum is specified for instruction arg here:
https://github.com/dominictwlee/ts-enum-example-anchor/blob/master/programs/ts-enum-example/src/lib.rs#L8

However, it seems any type can be passed to that positional arg.
https://github.com/dominictwlee/ts-enum-example-anchor/blob/master/tests/ts-enum-example.ts#L13

I'm guessing the type definitions generated don't seem to enforce the correct type.

**Comment by Juici** [comment]
This should be fixed by https://github.com/project-serum/anchor/pull/1726

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2482.
