### ISSUE TITLE
lang: has_one for options

### ISSUE THREAD

**Issue by paul-schaaf** [coral-xyz/anchor#1092]
instead of doing this
```
pub authority: Signer<'info>,
#[account(constraint = settings.authority == Some(authority.key()))]
pub settings: Account<'info, Settings>
```
how about we do this?
```
pub authority: Signer<'info>,
#[account(has_opt = authority)]
pub settings: Account<'info, Settings>
```

**Comment by Henry-E** [comment]
Is the purpose of this constraint is to handle the case when the settings account does not have the authority  initialised? If so it's possible people could misread this constraint as implying that authority is an optional account that doesn't have to be passed in

**Comment by paul-schaaf** [comment]
@Henry-E yes, it forces the authority field to be the `Some` variant and to have the correct key.

I see what you mean. we can try to come up with a better syntax.  It's an option so the constraint should convey that. Maybe `has_some`? I actually like that more than `has_opt`

(although even if we keep it like this, nothing bad would happen. the program would just fail and the user then hopefully looks up what it actually means)

**Comment by Henry-E** [comment]
Personally I've always kind of disliked/been confused by the `has_one` keyword. I prefer the explicitness of `constraint =`, it's just easier to remember what it does because it's so clear, if a bit verbose. It's kind of similar to how `state` has mostly been abandoned in favour of making people explicitly use their own PDAs. Maybe there's some way to improve the dev UX of `constraint =`?

**Comment by paul-schaaf** [comment]
it's hard to get any statistics of usage but from what Ive seen, in general, users like `has_one`. especially with multiple `has_one` the reduction in verbosity is significant

It was confusing for me too at first. my own confusion stemmed from the name not being very indicative of what it does. Id like to drop the `has_x` format altogether but havent been able to come up with a good syntax to suggest instead.

**Comment by Henry-E** [comment]
One thing is that many of the `has_one` use cases might better be filled by using the public key of the `has_one = ` account actually inside the seeds of the account calling `has_one`.

e.g.
`has_one = authority`
vs.
`seeds = [authority.key().as_ref()], b"this account"]`

**Comment by paul-schaaf** [comment]
there's still cases where using a pda to store a field just doesnt work. e.g. what if the field changes. Also, in the case of optional fields, the field might be None.

**Comment by Henry-E** [comment]
For sure, I'm not saying it covers all cases. But in many cases where it's currently used devs could design around using PDAs instead

**Comment by paul-schaaf** [comment]
yes

but if steering ppl towards pdas means making it harder and more verbose for users to use fields when you cannot use a pda, I dont think we should to that. reducing verbosity and raw constraints is _really_ important I think. every used raw constraint means a potential mistake somewhere in it

**Comment by paul-schaaf** [comment]
@armaniferrante any thoughts on this discussion?
