### ISSUE TITLE
Second PDA initialization failed after upgrading anchor-lang and anchor-spl in Rust Cargo.toml to 0.19.0

### ISSUE THREAD

**Issue by AuroraLantean** [coral-xyz/anchor#1143]
Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    Program xyz123... invoke [1]
    Program log: Instruction: InitPdaAcct
    Program xyz123... consumed 1496 of 200000 compute units
    Program failed to complete: Access violation in stack frame 5 at address 0x200005fd0 of size 8 by instruction #21232
    Program xyz123... failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (...project1/node_modules/@solana/web3.js/src/connection.ts:3689:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Connection.sendRawTransaction (...project1/node_modules/@solana/web3.js/src/connection.ts:3649:20)
    at sendAndConfirmRawTransaction (...project1/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at Provider.send (...project1/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at Object.rpc [as initPdaAcct] (...project1/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:24:23) {
  logs: [
    'Program xyz123... invoke [1]',
    'Program log: Instruction: InitPdaAcct',
    'Program xyz123... consumed 1496 of 200000 compute units',
    'Program failed to complete: Access violation in stack frame 5 at address 0x200005fd0 of size 8 by instruction #21232',
    'Program xyz123... failed: Program failed to complete'
  ]
}

After installing Anchor from 0.18.2 to  0.19.0 via npm global install,  my test file runs fine.
But after changing anchor-lang and anchor-spl from 0.18.2 to 0.19.0 in my Rust program Cargo.toml file then re-compile the Rust program, 
I can initialize a few other PDAs in the same way as initializing this DecimalAcct PDA, but when initializing this DecimalAcct PDA, it failed... WHY?
```
#[derive(Accounts)]
#[instruction(dacct_id: u16)]
pub struct InitDecimalAcct<'info> {
    #[account(
        init,
        seeds = [b"decimal", authority.key().as_ref(), dacct_id.to_string().as_bytes()],
        bump,
        payer = authority, owner = *program_id
    )]
    //pub decimal_acct: Box<Account<'info, DecimalAcct>>, //this Box<> does not work
    pub decimal_acct: AccountLoader<'info, DecimalAcct>,
    #[account(signer)]
    pub authority: AccountInfo<'info>,
    pub system_program: AccountInfo<'info>,
}
#[account(zero_copy)]
#[derive(Default)]
pub struct DecimalAcct {
    pub authority: Pubkey,
    pub decimals: [Decimal; 30],
}
//--------------== test file
    dacctId = 0;
    const decimalAcctBaseB = (
      await PublicKey.findProgramAddress(
        [
          Buffer.from(anchor.utils.bytes.utf8.encode('decimal')),
          walletB0.toBuffer(),
          Buffer.from(anchor.utils.bytes.utf8.encode(dacctId + '')),
        ],
        program.programId
      )
    )[0];
    log1('check1 decimalAcctBaseB:', decimalAcctBaseB.toBase58());
    decimalAcctList[didx] = decimalAcctBaseB;

    await program.rpc.initDecimalAcct(dacctId, {
      accounts: {
        decimalAcct: decimalAcctBaseB,
        authority: walletB0,
        //rent: anchor.web3.SYSVAR_RENT_PUBKEY,
        systemProgram: anchor.web3.SystemProgram.programId,
      },
    });
```
Please advise. Thank you

**Comment by armaniferrante** [comment]
Did you try using `Box<Account<...>>`?

**Comment by AuroraLantean** [comment]
Hi armaniferrante, thank you for the comment. 
I can initialize a few other PDAs in the same way as initializing this DecimalAcct PDA, but when initializing this DecimalAcct PDA, it failed... WHY? I have updated my Rust code and test file code as above...

I tried Box<account<...>> but then the rust-analyzer said the following
```
the trait bound `DecimalAcct: anchor_lang::AccountSerialize` is not satisfied
the trait `anchor_lang::AccountSerialize` is not implemented for `DecimalAcct`rustcE0277
account.rs(13, 30): required by a bound in `anchor_lang::Account`
```
Please help. Thank you
