### ISSUE TITLE
Prevent passing canonical IDL account into IDL Buffer Write instruction

### ISSUE THREAD

**Issue by kevinaud** [coral-xyz/anchor#1149]
It's possible I'm just misunderstanding things but I'm pretty sure there is a bug in the current implementation of IDL account updates via the buffer mechanism.

The flow should work like:

1) Call `CreateBuffer` to create a new buffer account
2) Call `Write` n times to append data to the buffer account
3) Call `SetBuffer` to write the contents of the buffer account into IDL account

The problem is in step 2. The [current `Write` handler](https://github.com/project-serum/anchor/blob/master/lang/syn/src/codegen/program/handlers.rs#L146-L158) is appending data to the _IDL_ account instead of the _buffer_ account.

**Comment by armaniferrante** [comment]
The buffer account is the same type as an IDL account. We could add an extra check to assert that one can't pass in the canonical IDL account there, for extra safety.

**Comment by kevinaud** [comment]
Ahhh okay I see, so the client [creates a new address](https://github.com/project-serum/anchor/blob/master/cli/src/lib.rs#L2127) and passes it into subsequent calls. I saw that the same type was being used, I think I was getting mixed up because I was looking at [the address() method](https://github.com/project-serum/anchor/blob/713d43668b304fbec5c870f3a1d67c113b6dead9/lang/src/idl.rs#L97-L101) on IdlAccount and thinking that it was used to retrieve the account but now I see that is just a helper method and doesn't have any effect on which account gets loaded in.

Yeah I think that would be worth adding, just to be sure that the _only_ way to update the IDL data is to go through the correct flow. I can take a stab at adding that.

**Comment by armaniferrante** [comment]
> Yeah I think that would be worth adding, just to be sure that the _only_ way to update the IDL data is to go through the correct flow. I can take a stab at adding that.

Sounds great!
