### ISSUE TITLE
ts: After installing @project-serum/anchor 0.19.1-beta.1 and then importing it on reactjs app I get these errors

### ISSUE THREAD

**Issue by ntirinigaSr** [coral-xyz/anchor#1194]
ERROR in ./node_modules/@project-serum/anchor/dist/browser/index.js 12:0-28

Module not found: Error: Can't resolve 'assert' in '/home/ntiriniga/Desktop/react-apps/app5/node_modules/@project-serum/anchor/dist/browser'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
	- install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "assert": false }

Any help will be appreciated!!!!

**Comment by fanatid** [comment]
Did you tried other anchor versions?

**Comment by ntirinigaSr** [comment]
Yes after upgrading node from 14 to 16

**Comment by AlberErre** [comment]
This is still an issue on `@project-serum/anchor` version `0.20.01`. 

You can find a workaround here #1290
