### ISSUE TITLE
tests: organise tests/misc

### ISSUE THREAD

**Issue by paul-schaaf** [coral-xyz/anchor#1236]
the misc test program test file is quite unorganized currently. We should at least group similar tests using `describe`

**Comment by migui3230** [comment]
@paul-schaaf i'll take this one on!

**Comment by paul-schaaf** [comment]
Thanks @migui3230 ! This issue is a little outdated in that we should move out tests from misc into their own directories. See https://github.com/project-serum/anchor/issues/1624 and https://github.com/project-serum/anchor/issues/1625. Maybe there are still tests that belong more in misc than in those directories but it would be awesome if you could do #1624 or #1625

**Comment by migui3230** [comment]
@paul-schaaf I'll try that!

**Comment by paul-schaaf** [comment]
@migui3230 have you done work on the issues yet? If yes, please push a PR with your WIP changes. If not, please focus on #1625 as #1624 will likely be handled in https://github.com/project-serum/anchor/issues/1212

**Comment by migui3230** [comment]
@paul-schaaf ok ill focus on #1625

**Comment by migui3230** [comment]
@paul-schaaf #1763

**Comment by Henry-E** [comment]
Thanks for this, the misc tests are still huge but i'm guessing it's much better now.
