### ISSUE TITLE
`fetch` decoding problems, potentially due to bad account size requirements

### ISSUE THREAD

**Issue by Danlowe95** [coral-xyz/anchor#1241]
I have outlined the problem at the following gist in as much detail as I can, with examples.

I cannot say for sure that the problem as I outline it is entirely correct, but have given examples of what works and what does not, with my best guess for potential conclusion.

Please give it a read:
https://gist.github.com/Danlowe95/8ae5767a95e8321c255e2b1345f351fb#file-gistfile2-md

**Comment by Danlowe95** [comment]
Paul sent the following information on discord:
https://docs.rs/anchor-lang/latest/anchor_lang/attr.account.html#zero-copy-deserialization
https://docs.rs/bytemuck/1.7.3/bytemuck/trait.Pod.html#safety

Which likely (in part) explains the problem at hand here.
My structs are using bools and could possibly have padding (hard to say), which is likely causing the decoding issue.

It is pretty hard to understand though, considering my example with 8 bools/Pubkey/5 u8s will decode properly. This leaves me concerned that a currently "working" solution that includes `bool` fields could stop working at some point in the future, even if it is fine now. 

Attempting to build this state without `Option` is hard, and makes the code less readable and more prone to bugs, but it is manageable. Attempting it without `bool` would likely amplify the potential problems (for example, storing bools as `u8` fields and only setting them to `0` or `1`) and could definitely lead to bugged code. However, these could be potential solutions if there is no better alternative.

Posting the above thoughts in case anyone can offer better solutions to work around the finicky-ness of POD safety.

**Comment by Henry-E** [comment]
It sounds like you might have run into some of the issues with zero copy accounts being marked as unsafe and letting you do stuff that will break it.
