### ISSUE TITLE
Compute units profiling

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#1248]
We should have a set of benchmarks to profile compute units for Anchor boilerplate, so that we can understand the cost of all the macro generated code.

**Comment by blasrodri** [comment]
I'd be happy to tackle this one. Any pointer/hints on how to go about it?

**Comment by armaniferrante** [comment]
The main thing I'm interested in is understanding the overhead anchor puts on a program. So writing anchor + non anchor programs side by side and measure the compute differences would be instructive. Other than that this is open ended.

**Comment by Henry-E** [comment]
Would love to see anyone else taking this on. There's a lot happening under the hood in anchor and it would be useful to follow along with what the costs are and where they come from.

**Comment by metaproph3t** [comment]
This can be closed because of [2466](https://github.com/coral-xyz/anchor/pull/2466)
