### ISSUE TITLE
Zero-copy issue v0.20.0

### ISSUE THREAD

**Issue by NorbertBodziony** [coral-xyz/anchor#1255]
Seems like in v0.20.0 after change, there is something wrong with zero-copy. I forked zero-copy example from anchor repo and used v0.20.0 anchor and tests are not passing.
Program fails with `Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS failed: custom program error: 0xbbf`
Which is `AccountOwnedByWrongProgram`

Repo:
https://github.com/NorbertBodziony/bug-zero-copy

**Comment by paul-schaaf** [comment]
I'm not able to reproduce this

**Comment by Henry-E** [comment]
appreciate the effort in making the reproducible repo but it seems like this isn't actionable. At best because it involves CPI, it might mean there's another bug in the CPI stuff that gets exported from the program.
