### ISSUE TITLE
cli: anchor test does not properly use `--provider.cluster` option

### ISSUE THREAD

**Issue by paul-schaaf** [coral-xyz/anchor#1294]
If I set the provider.cluster property in Anchor.toml to `devnet` my tests work.

If I set it to localnet but use `anchor test --provider.cluster=devnet`, my tests should also work but they dont

```
  2) tic-tac-toe
       player one wins:
     Error: failed to send transaction: Transaction simulation failed: This program may not be used for executing instructions
```

**Comment by nasmithan** [comment]
Does this work for you? 

`anchor test --provider.cluster devnet`

**Comment by Logarithmus** [comment]
Having exactly the same issue.

**Comment by jypthemiracle** [comment]
I have the same issue too.

**Comment by smile930307** [comment]
Me too.
Hope to get know the reason.

**Comment by coldnight** [comment]
Same issue too.

**Comment by coldnight** [comment]
Reinstall the latest stable Solana CLI solve this problem: https://docs.solana.com/getstarted/local#install-the-solana-cli

**Comment by Henry-E** [comment]
It sounds like this might be fixed then?
