### ISSUE TITLE
spl: Add new token instructions that don't use rent sysvar

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#1329]
New spl token instructions were added that removed the need to pass in the rent sysvar. We should add apis for them.

**Comment by fanatid** [comment]
Blocked by `solana` crates. Not required `rent` sysvar instructions were introduced in `spl-token:3.3.0` but this version requires `solana-program:^1.9.2`. `1.9.x` is still not stable, we need wait, then update `solana` crates and return to this issue.

**Comment by blockchainlover2019** [comment]
Ok. make sense. Thank you.

**Comment by fanatid** [comment]
Blocked by https://github.com/project-serum/anchor/issues/1669
