### ISSUE TITLE
lang: Token constraints should use token instructions that don't require rent sysvar

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#1330]
Related: https://github.com/project-serum/anchor/issues/1329

**Comment by blockchainlover2019** [comment]
> Related: #1329

armani, give me this task.

**Comment by armaniferrante** [comment]
> > Related: #1329
> 
> armani, give me this task, so that I can contribute to Anchor project.

Done!

**Comment by blockchainlover2019** [comment]
Ok, Thank you. I will go forward.

**Comment by fanatid** [comment]
Blocked by #1329

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2265
