### ISSUE TITLE
avm: option to download binary instead of building from source (binary could also become the default?)

### ISSUE THREAD

**Issue by paul-schaaf** [coral-xyz/anchor#1411]
blocked by https://github.com/project-serum/anchor/issues/1410

**Comment by fanatid** [comment]
If there will be a discussion I'd prefer default is building from the source and binary as an option.

**Comment by armaniferrante** [comment]
> If there will be a discussion I'd prefer default is building from the source and binary as an option.

Excuse my ignorance. Do other version managers do this? What's the argument for this?

**Comment by fanatid** [comment]
> Do other version managers do this? What's the argument for building from source?

Good point :neutral_face: More funny that I'm was that person who added `anchor-cli` with the binary :laughing: Please do not consider my previous message :man_facepalming:
