### ISSUE TITLE
unsafe_zero_copy

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#1440]
The current implementation of zero copy uses some unsafe trait implementations for Pod and Zeroable. We should change the macro name to reflect this. For example, `#[account(unsafe_zero_copy)]`.

**Comment by johnanthos** [comment]
https://github.com/coral-xyz/anchor/pull/2330 seems to have made zero_copy safe by default. Should this issue be closed?

**Comment by acheroncrypto** [comment]
> #2330 seems to have made zero_copy safe by default. Should this issue be closed?

Yes, thanks!
