### ISSUE TITLE
Auto-populate for PDAs using Methods namespace doesn't work for defined types

### ISSUE THREAD

**Issue by danmt** [coral-xyz/anchor#1458]
If a seed is a **defined type** the Auto-populate PDA's feature is failing which makes sense [due to this](https://github.com/project-serum/anchor/blob/master/ts/src/program/accounts-resolver.ts#L217). 

I tried to give this a shot but couldn't make it work reliably. Decided to submit the issue in case somebody else is working on the same issue.

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2824.
