### ISSUE TITLE
Unable to start test validator.

### ISSUE THREAD

**Issue by HotMonkeyWings** [coral-xyz/anchor#1540]
The error log in `.anchor/test-validator.log` simply had the word "Initializing..." in it. I tried running it `solana-test-validator` with the `--no-bpf-jit` flag and `anchor test` with  `--skip-local-validator` but had no luck. I got the following error 

`Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist`

But I noticed that sometimes the tests worked! I finally figured out that if I launch `solana-test-validator` with `--reset` flag, close that terminal or ctrl+c out of it and then run `anchor test`, the tests run smoothly! If I try running `anchor test` again, it goes back to the original error `Unable to start validator`. 

P.S. I use arch btw
Jokes aside, im on Kernel 5.16.11

**UPDATE** : I noticed that the anchor test only fails when I switch terminals. If I stay on the same terminal after resetting, it works! Very odd behaviour. (I guess its because of some env variables?)

**UPDATE 2** : It looks like its completely working on luck right now...sometimes it shows the error, sometimes it doesn't.

**Comment by HotMonkeyWings** [comment]
![image](https://user-images.githubusercontent.com/31684891/156388849-c4f96b5e-4cd9-45bd-a46c-511049bdfa56.png)
Heres a screenshot of it happening.

**Comment by acheroncrypto** [comment]
When tests work only some of the time for seemingly random reasons, it's usually about commitment level/not giving enough time for the test validator to start(e.g. on a slower machine).
