### ISSUE TITLE
PDA Inference Fails with Seeds Outside of Scope

### ISSUE THREAD

**Issue by callensm** [coral-xyz/anchor#1550]
In the current `pda-derivation` test case, the IDL is properly populated with the PDA seeds since the seeds are declared and referenced within the same module/scope as the `Accounts` structs.

If you move the seeds outside of the scope of the struct:

```rs
mod seeds {
    #[constant]
    pub const MY_SEED: &[u8] = b"my_pda_seed";
}

#[derive(Accounts)]
pub struct Init<'info> {
    #[account(
        seeds = [
            seeds::MY_SEED,
            // ...
        ],
        bump,
        // ...
    )]
    pub my_pda: Account<'info, X>,

    // ...
}
```

This will fail to parse and translate the seeds into the IDL with:

```
WARNING: unexpected seed: Path(ExprPath { attrs: [], qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident(seeds), arguments: None }, Colon2, PathSegment { ident: Ident(MY_SEED), arguments: None }] } })
```

...and if you `use` the seed into the module (`use seeds::MY_SEED`) and remove the module scope prefix, it will still fail with the appropriately modified `ident` parsing error.

It seems that only seeds defined within the same scope at the `Accounts` struct that is using them will parse correctly.

**Comment by GuidoDipietro** [comment]
This is especially annoying if you use some external constant from a common program such as `mpl_token_metadata`, it can generate many many warnings.

**Comment by AnderUstarroz** [comment]
This really needs a review, aiming for a more flexible way to generate seeds without breaking IDL or generating the mentioned annoying warnings.

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/2824.
