### ISSUE TITLE
`#[constant]` doesn't evaluate `const fn`s.

### ISSUE THREAD

**Issue by sagefarrenholz** [coral-xyz/anchor#1560]
I would like the IDL to include output from constant functions. I am guessing that it doesn't work because the preprocessor runs before constant function evaluation.

What I have:
```rust
#[constant]
const AccountSize: usize = size_of::<SomeAccount>();
```
The IDL looks like:
```json
"constants": [
  {
    "name": "AccountSize",
    "type": {
      "defined": "usize"
    },
    "value": "mem_macros :: size_of ! (SomeAccount)"
  }
],
```
Is there an idiomatic method to use a constant function in a IDL constant declaration in Anchor?
I also tried switching the `size_of::<SomeAccount>();` to a proc macro but it didn't evaluate either, just copying TokenStream into IDL.

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2824.
