### ISSUE TITLE
Missing Idl Type for imported types

### ISSUE THREAD

**Issue by jkbpvsc** [coral-xyz/anchor#1566]
Anchor doesn't generate IDL definitions for imported types.
Example:
https://github.com/drift-labs/cpi-example/blob/master/programs/drift-client/src/lib.rs#L343

Drift structs need to be redefined and reconstructed for CPI calls.

**Comment by paul-schaaf** [comment]
related : #454

**Comment by theDefiBat** [comment]
is this fixed somewhere or still open ?

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/2824.
