### ISSUE TITLE
`AccountClient.fetchMultiple` returns `Object` instead of `T`

### ISSUE THREAD

**Issue by pawel-betdex** [coral-xyz/anchor#1580]
While trying to optimise fetches from the chain in the clients, we have noticed that `AccountClient` class method `fetchMultiple` erases the type from a return method.
This causes some inconveniences during development of the clients as all the fields are being highlighted as not present.

Instead of returning `Promise<(Object | null)[]>` we think it should be `Promise<(T | null)[]>` where `T` is comes from `AccountClient` declaration.

TBH this looks like something that might have been overlooked since other methods using the same code in the `AccountClient` do return `T`.
```
async fetch( address: Address, commitment?: Commitment ): Promise<T>
async fetchNullable( address: Address, commitment?: Commitment ): Promise<T | null>
```

-----
Sidenote:
This issue is similar to https://github.com/project-serum/anchor/issues/1465 but we are not asking for the replacement of how types are generated - just making the current setup consistent.

**Comment by fastestmannr** [comment]
Do you also want to change the call to `accounts.decode` to be `accounts.decode<T>`?

**Comment by pawel-betdex** [comment]
> Do you also want to change the call to `accounts.decode` to be `accounts.decode<T>`?

Why not. Done.

**Comment by mehtaphysical** [comment]
Can we merge this one? Why nicer this way :).
