### ISSUE TITLE
Runtime errors in browser

### ISSUE THREAD

**Issue by rzcoder** [coral-xyz/anchor#1638]
I'm getting runtime errors when compile project with anchor by webpack. In investigation I found this piece of code in npm module

dist/cjs/utils/common.js:

```
/**
 * Returns true if being run inside a web browser,
 * false if in a Node process or electron app.
 */
exports.isBrowser = process.env.BROWSER ||
    (typeof window !== "undefined" && !((_a = window.process) === null || _a === void 0 ? void 0 : _a.hasOwnProperty("type")));
```

Looks like it will always fail in browser

**Comment by acheroncrypto** [comment]
https://github.com/coral-xyz/anchor/blob/267c4ceab7129c865680b0b9e7dd4376cc785265/ts/packages/anchor/src/utils/common.ts#L3-L9

`typeof window !== "undefined" && !window.process?.hasOwnProperty("type")` should return `true` in browsers. You can try it by opening the browser console and executing this code.

**Comment by devusmanrafiq** [comment]
`process` is `undefined` in browsers and the code fails at run time when evaluation `process.env.BROWSER` the fallback code is not executed and hence we cant use the sdk in browser.
