### ISSUE TITLE
Anchor ts example 4 relies on deprecated anotation #state

### ISSUE THREAD

**Issue by arielsegura** [coral-xyz/anchor#1701]
This is deprecated and needs to be updated 

https://github.com/project-serum/anchor/blob/40596824bf85df8c2b3313a677ebbaef559361c9/examples/tutorial/basic-4/programs/basic-4/src/lib.rs#L10

**Comment by arielsegura** [comment]
I will try to fix it and use the new `method.<methodname>.rpc()` notation. Let me know if there's a better way

**Comment by nazreen** [comment]
@arielsegura you highlighted line 10 which has `#[state]`
does that mean that the state attribute is no longer used?

**Comment by arielsegura** [comment]
it's used, but it's deprecated and it will be removed soon so we should fix the examples

**Comment by armaniferrante** [comment]
We should simply remove the example completely.

**Comment by arielsegura** [comment]
The current example may bring no value at all, but I think that after merging this https://github.com/project-serum/anchor/pull/1700 it will be useful for others

**Comment by acheroncrypto** [comment]
Removed in https://github.com/coral-xyz/anchor/pull/2285.
