### ISSUE TITLE
ts: `AccountClient` isn't properly typed

### ISSUE THREAD

**Issue by callensm** [coral-xyz/anchor#1706]
Querying for accounts like `program.account.myAccount.fetch(addr)` should return an object that is strictly typed for the `myAccount` account type definition.

However, the client currently types the object as being the union of properties between all IDL defined account structs.

![image](https://user-images.githubusercontent.com/13121516/160699766-522fe02a-23d8-4904-a0a6-7691a6a3309d.png)

As seen in the screenshot, the typing on the `listing` account client includes the properties of other account types.

**Comment by paul-schaaf** [comment]
probably for the same reason, using `program.methods.accounts({ .. })` is also not typed properly

**Comment by paul-schaaf** [comment]
it it fixed for you? its not working for me

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2440
