### ISSUE TITLE
Conflict with @solana/web3.js in v >= 0.19

### ISSUE THREAD

**Issue by timlanahan** [coral-xyz/anchor#1747]
`@project-serum/anchor` seems to conflict with `@solana/web3.js` in versions greater than or equal to 0.19.  

See this [SO](https://stackoverflow.com/questions/70652456/solanaweb-3-js-package-typeerror-s-transactioninstruction-is-not-a-constructor).  

The Solana `Connection` object would be `undefined` (or at least it seems to be reassigned) due to the minification / uglification that occurs when using the `terser` plugin.

<img width="931" alt="image" src="https://user-images.githubusercontent.com/101747647/162468122-20db3ca8-1446-407a-98ef-9846437ef8ee.png">

You can see from the image that the bundled code is reassigning `a` to `_e15[1]` (other test builds I have also see this reassigning `s = _vt[[0]` or something similar.  

Then the highlighted line shows `new a.TransactionInstruction` is not an object containing a function called `TransactionInstruction` but the right side inspector does show a global variable called `a` with the `TransactionInstruction` function from the `@solana/web3.js` connection object.

Is it possible to somehow modify the build to prevent conflicts like this?

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2263.
