### ISSUE TITLE
anchor-cli should automatically use the `anchor-lang` dependency version in anchor programs

### ISSUE THREAD

**Issue by daweth** [coral-xyz/anchor#1760]
If I clone a repo using an older version of Anchor, I need to run `avm install 0.XX.0` followed by `avm use 0.XX.0`. It would be nice if anchor could autodetect the versions being used so that running `anchor build` or `anchor test` `does not require manually changing the verisons.

**Comment by acheroncrypto** [comment]
You wouldn't necessarily need to use the same `anchor-cli` version as the `anchor-lang` version but this can now be automated by specifying `toolchain.anchor_version`(https://github.com/coral-xyz/anchor/pull/2649):

```toml
[toolchain]
anchor_version = "0.29.0"
```
