### ISSUE TITLE
lang: parser should error if `init` is used with `token::mint = X` and X is not a field in the account struct 

### ISSUE THREAD

**Issue by paul-schaaf** [coral-xyz/anchor#1797]

**Comment by yourarj** [comment]
@paul-schaaf  Please add some description so it'll be clear. May be some pseudo code too.

**Comment by sapphire-alysa-star** [comment]
![Parser](https://user-images.githubusercontent.com/96838947/163686196-ec2e216c-92b7-4a14-9cc8-9e65d45061ca.png)

Copied the motivating example from discord. In this case token::mint was a Pubkey not an account.

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/1804
