### ISSUE TITLE
Why were all versions yanked in crates.io?

### ISSUE THREAD

**Issue by auterium** [coral-xyz/anchor#1816]
I've been surprised today that my CI pipelines stopped working out of nowhere just to realize that the version I had pinned on my project was no longer available in crates.io as it got yanked. I got even more surprised to see that _all_ but the latest version of anchor were yanked:
![image](https://user-images.githubusercontent.com/4732632/164257959-7be8bf39-13b9-46a6-af45-bbbc3f41f165.png)

Is there a reason why this was done? Or was it a mistake?

Thanks!

**Comment by armaniferrante** [comment]
Not a mistake. If one wants to use an old version, one can use a git dependency with a versioned tag. However, each latest version tends to have very important security features, and in the case of some releases, critical bug fixes. Yanking all old releases will be the policy going forward, unless there's a crucial reason to not do so.

**Comment by auterium** [comment]
Thanks for the response. Out of curiosity, why the sudden decision? Wouldn't this change break reproducible builds? I personally don't mind the push for the use of newer, more secure version, but my project depends on another project that uses older versions, and I would have to patch that other project (Drift) to get it working as a dependency. I did try to use a tag-based patch, but it's still breaking other dependencies that are depending on a different version than Drift, so I'm not sure how to patch 2 dependencies. Any pointers on how to do so would me much appreciated.

**Comment by bennofs** [comment]
Cargo will use yanked versions as long as they are already in the lockfile. So if you generate a Cargo.lock before the version is yanked, you will still be able to build this project after the version is yanked if you keep the same lockfile. Thus this won't break reproducible builds.

**Comment by acheroncrypto** [comment]
We haven't yanked since `0.24.2`.
