### ISSUE TITLE
Error testing anchor project

### ISSUE THREAD

**Issue by Emma66886** [coral-xyz/anchor#1822]
While I was trying to test the project I built, it's returning cannot read properties of undefined (reading 'methods') from the program

![IMG_20220421_194348_407.jpg](https://user-images.githubusercontent.com/52328102/164531615-177ec3d1-00ee-44b1-acf5-8e103b5fdf11.jpg)

**Comment by mateolafalce** [comment]
Check your Typescript version.
Install it
`npm install -g typescript`

**Comment by acheroncrypto** [comment]
This could happen if you renamed your program but not updated the program name in all necessary places.

Most important part is to make sure the program name declared in `lib.rs`

```rs
#[program]
mod program_name {
    // ...
}
```

matches in TypeScript side:

```ts
const program = anchor.workspace.programName;
```
