### ISSUE TITLE
lang: program constants defined as constant expressions are stored literally in IDL

### ISSUE THREAD

**Issue by cavemanloverboy** [coral-xyz/anchor#1830]
if one defines some
```rust
#[constant]
/// This is a useful constant
pub const USEFUL_CONSTANT: usize = 2_usize.pow(8);
```
then the idl will store "2_usize.pow(8)" literally instead of "256". 

If there is an easy way to evaluate const expressions before storing it in the IDL, I personally think that is a better outcome. This would allow for easy use of `parseInt` or similar fn's in typescript.

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/2824.
