### ISSUE TITLE
Dependency issues with Cannot find module @solana/web3.js

### ISSUE THREAD

**Issue by emberist** [coral-xyz/anchor#1838]
It seems there is a problem with the `@solana/web3.js` library:

```
Cannot find module '.../node_modules/@solana/web3.js/lib/index.cjs.js'.
Please verify that the package.json has a valid "main" entry
```

Does anyone know the problem?

**Comment by Anan7Codes** [comment]
Facing the same issue right now.

**Comment by acheroncrypto** [comment]
This doesn't seem like it's related to Anchor but `yarn add @solana/web3.js` or `rm -rf node_modules && yarn` should solve it.
