### ISSUE TITLE
anchor test fails on Linux arm64

### ISSUE THREAD

**Issue by causevic** [coral-xyz/anchor#1846]
I've created a basic project with anchor init ... --javascript

When I try to run it using anchor test --skip-local-validator I get the following error:

ps@ubuntu-linux-20-04:~/src/solana/epicproject$ anchor test --skip-local-validator
BPF SDK: /home/parallels/solana/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
/home/parallels/.rustup/toolchains/bpf/bin/cargo: 1: ELF: not found
/home/parallels/.rustup/toolchains/bpf/bin/cargo: 2: Syntax error: ")" unexpected

Running a Linux Ubuntu in Parallels Desktop on an M1 Max Macbook.

**Comment by acheroncrypto** [comment]
Anchor uses Solana's build tools under the hood and I don't think Solana releases ARM builds so you'd have to [build from source](https://docs.solana.com/cli/install-solana-cli-tools#build-from-source) to make it work.
