### ISSUE TITLE
Unable to get latest blockhash. Test validator does not look started. Check .anchor/test-ledger/test-ledger-log.txt for errors. Consider increasing [test.startup_wait] in Anchor.toml.

### ISSUE THREAD

**Issue by Rickyip** [coral-xyz/anchor#1861]
In basic-0 example
I run `anchor test`, it results in this error
![image](https://user-images.githubusercontent.com/12053934/166252959-52bb00bc-c6a0-4287-b6d9-8239799c9943.png)

my environment:
M1 Mac with macOS 12.3.1
cargo 1.60.0
solana-cli 1.10.8

**Comment by tomlinton** [comment]
Does `solana-test-validator` on its own work? Does the referenced log contain anything?

**Comment by Rickyip** [comment]
When I run `solana-test-validator` on its own, it mentioned there are illegal instruction :

```
Ricks-M1-Air:basic-0 rickyip$ solana-test-validator
Ledger location: test-ledger
Log: test-ledger/validator.log
⠙ Initializing...
Illegal instruction: 4
```

The log does not ring any bell to me either:
```
[0m[38;5;8m[[0m2022-05-08T14:20:20.016129000Z [0m[32mINFO [0m solana_test_validator[0m[38;5;8m][0m solana-validator 1.10.8 (src:623ac656; feat:1122441720)
[0m[38;5;8m[[0m2022-05-08T14:20:20.016184000Z [0m[32mINFO [0m solana_test_validator[0m[38;5;8m][0m Starting validator with: ArgsOs {
        inner: [
            "solana-test-validator",
        ],
    }
[0m[38;5;8m[[0m2022-05-08T14:20:20.016481000Z [0m[33mWARN [0m solana_perf[0m[38;5;8m][0m CUDA is disabled
[0m[38;5;8m[[0m2022-05-08T14:20:20.039046000Z [0m[32mINFO [0m solana_faucet::faucet[0m[38;5;8m][0m Faucet started. Listening on: 0.0.0.0:9900
[0m[38;5;8m[[0m2022-05-08T14:20:20.039067000Z [0m[32mINFO [0m solana_faucet::faucet[0m[38;5;8m][0m Faucet account address: 5ANxWjYXXXXXXXXXXXZpWRD
[0m[38;5;8m[[0m2022-05-08T14:20:20.043867000Z [0m[32mINFO [0m solana_ledger::blockstore[0m[38;5;8m][0m Maximum open file descriptors: 500000
[0m[38;5;8m[[0m2022-05-08T14:20:20.043887000Z [0m[32mINFO [0m solana_ledger::blockstore[0m[38;5;8m][0m Opening database at "test-ledger/rocksdb"
[0m[38;5;8m[[0m2022-05-08T14:20:20.284472000Z [0m[32mINFO [0m solana_ledger::blockstore[0m[38;5;8m][0m "test-ledger/rocksdb" open took 240ms

```

**Comment by saurabhnative** [comment]
Adding 
```
[test]
startup_wait = 10000
```
in Anchor.toml fixed the issue for me.
Reference:- https://book.anchor-lang.com/anchor_references/anchor-toml_reference.html

**Comment by cthackt** [comment]
> Adding
> 
> ```
> [test]
> startup_wait = 10000
> ```
> 
> in Anchor.toml fixed the issue for me. Reference:- https://book.anchor-lang.com/anchor_references/anchor-toml_reference.html

Thank you! This worked for me.

**Comment by acheroncrypto** [comment]
See https://github.com/solana-labs/solana/issues/28899

**Comment by KaluArunsi** [comment]
If you decide to run `solana-test-validator` on another terminal, it would be good to execute `anchor run test` instead of `anchor test` so anchor uses your own local validator and not anchor's, if the problem persists.

See here - https://solana.stackexchange.com/questions/3117/anchor-test-error-your-configured-rpc-port-8899-is-already-in-use

**Comment by CharlieAIO** [comment]
> I meet the same problem, but the above ways do not solve my error. This is my configurations:
> 
> [toolchain]
> 
> [features]
> resolution = true
> skip-lint = false
> 
> [programs.localnet]
> burry_escrow = "6d2fJan62kCY1BYxP7ZTKBxfzdjMkq8ncnCravQKwSM6"
> 
> [registry]
> url = "https://api.apr.dev"
> 
> [provider]
> cluster = "Localnet"
> wallet = "~/.config/solana/id.json"
> 
> [scripts]
> test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
> 
> [test]
> startup_wait = 50000
> shutdown_wait = 2000
> upgradeable = false
> 
> [test.validator]
> bind_address = "0.0.0.0"
> url = "https://api.devnet.solana.com"
> ledger = ".anchor/test-ledger"
> rpc_port = 8899
> 
> [[test.validator.clone]] # switchboard-solana devnet programID
> address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"
> 
> [[test.validator.clone]] # switchboard-solana devnet IDL
> address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"
> 
> [[test.validator.clone]] # switchboard-solana SOL/USD Feed
> address = "GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR"
> Error:
> 
> ```
> Unable to get latest blockhash. Test validator does not look started. Check ".anchor/test-ledger/test-ledger-log.txt" for errors. Consider increasing [test.startup_wait] in Anchor.toml.
> ```
> 
> The logs in `test-ledger-log.txt`:
> 
> ```
> Ledger location: .anchor/test-ledger
> Log: .anchor/test-ledger/validator.log
> Initializing...
> Waiting for fees to stabilize 1...
> Connecting...
> Identity: B3azSStom8rkXLTfVYvK1ZRB14kCcRJoXKGjfygxPXZK
> Genesis Hash: 3RbP86J4SGpKrqkgyr9EKALaNnvVDWHYYTBWcMivCkdr
> Version: 2.0.16
> Shred Version: 2004
> Gossip Address: 127.0.0.1:1024
> TPU Address: 127.0.0.1:1027
> JSON RPC URL: http://127.0.0.1:8899
> WebSocket PubSub URL: ws://127.0.0.1:8900
> 00:00:04 | Processed Slot: 4 | Confirmed Slot: 4 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 3 | ◎499.999985000
> 00:00:04 | Processed Slot: 5 | Confirmed Slot: 4 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 4 | ◎499.999985000
> 00:00:04 | Processed Slot: 5 | Confirmed Slot: 5 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 4 | ◎499.999980000
> 00:00:04 | Processed Slot: 6 | Confirmed Slot: 6 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 5 | ◎499.999975000
> 00:00:05 | Processed Slot: 6 | Confirmed Slot: 6 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 5 | ◎499.999975000
> 00:00:05 | Processed Slot: 7 | Confirmed Slot: 7 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 6 | ◎499.999970000
> 00:00:05 | Processed Slot: 7 | Confirmed Slot: 7 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 6 | ◎499.999970000
> 00:00:06 | Processed Slot: 8 | Confirmed Slot: 8 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 7 | ◎499.999965000
> 00:00:06 | Processed Slot: 9 | Confirmed Slot: 9 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 8 | ◎499.999960000
> 00:00:06 | Processed Slot: 9 | Confirmed Slot: 9 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 8 | ◎499.999960000
> 00:00:06 | Processed Slot: 10 | Confirmed Slot: 10 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 9 | ◎499.999955000
> 00:00:07 | Processed Slot: 10 | Confirmed Slot: 10 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 9 | ◎499.999955000
> 00:00:07 | Processed Slot: 11 | Confirmed Slot: 11 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 10 | ◎499.999950000
> 00:00:07 | Processed Slot: 11 | Confirmed Slot: 11 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 10 | ◎499.999950000
> 00:00:07 | Processed Slot: 12 | Confirmed Slot: 12 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 11 | ◎499.999945000
> 00:00:08 | Processed Slot: 13 | Confirmed Slot: 13 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 12 | ◎499.999940000
> 00:00:08 | Processed Slot: 13 | Confirmed Slot: 13 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 12 | ◎499.999940000
> 00:00:08 | Processed Slot: 14 | Confirmed Slot: 14 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 13 | ◎499.999935000
> 00:00:09 | Processed Slot: 14 | Confirmed Slot: 14 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 13 | ◎499.999935000
> 00:00:09 | Processed Slot: 15 | Confirmed Slot: 15 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 14 | ◎499.999930000
> 00:00:09 | Processed Slot: 15 | Confirmed Slot: 15 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 14 | ◎499.999930000
> 00:00:09 | Processed Slot: 16 | Confirmed Slot: 16 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 15 | ◎499.999925000
> 00:00:10 | Processed Slot: 17 | Confirmed Slot: 16 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 16 | ◎499.999925000
> 00:00:10 | Processed Slot: 17 | Confirmed Slot: 17 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 16 | ◎499.999920000
> 00:00:10 | Processed Slot: 18 | Confirmed Slot: 18 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 17 | ◎499.999915000
> 00:00:10 | Processed Slot: 18 | Confirmed Slot: 18 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 17 | ◎499.999915000
> 00:00:11 | Processed Slot: 19 | Confirmed Slot: 19 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 18 | ◎499.999910000
> 00:00:11 | Processed Slot: 19 | Confirmed Slot: 19 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 18 | ◎499.999910000
> 00:00:11 | Processed Slot: 20 | Confirmed Slot: 20 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 19 | ◎499.999905000
> 00:00:11 | Processed Slot: 21 | Confirmed Slot: 21 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 20 | ◎499.999900000
> 00:00:12 | Processed Slot: 21 | Confirmed Slot: 21 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 20 | ◎499.999900000
> 00:00:12 | Processed Slot: 22 | Confirmed Slot: 22 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 21 | ◎499.999895000
> 00:00:12 | Processed Slot: 22 | Confirmed Slot: 22 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 21 | ◎499.999895000
> 00:00:13 | Processed Slot: 23 | Confirmed Slot: 23 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 22 | ◎499.999890000
> 00:00:13 | Processed Slot: 23 | Confirmed Slot: 23 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 22 | ◎499.999890000
> 00:00:13 | Processed Slot: 24 | Confirmed Slot: 24 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 23 | ◎499.999885000
> 00:00:13 | Processed Slot: 25 | Confirmed Slot: 25 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 24 | ◎499.999880000
> 00:00:14 | Processed Slot: 25 | Confirmed Slot: 25 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 24 | ◎499.999880000
> 00:00:14 | Processed Slot: 26 | Confirmed Slot: 26 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 25 | ◎499.999875000
> 00:00:14 | Processed Slot: 26 | Confirmed Slot: 26 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 25 | ◎499.999875000
> 00:00:14 | Processed Slot: 27 | Confirmed Slot: 27 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 26 | ◎499.999870000
> 00:00:15 | Processed Slot: 27 | Confirmed Slot: 27 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 26 | ◎499.999870000
> 00:00:15 | Processed Slot: 28 | Confirmed Slot: 28 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 27 | ◎499.999865000
> 00:00:15 | Processed Slot: 29 | Confirmed Slot: 29 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 28 | ◎499.999860000
> 00:00:16 | Processed Slot: 29 | Confirmed Slot: 29 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 28 | ◎499.999860000
> 00:00:16 | Processed Slot: 30 | Confirmed Slot: 30 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 29 | ◎499.999855000
> 00:00:16 | Processed Slot: 30 | Confirmed Slot: 30 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 29 | ◎499.999855000
> 00:00:16 | Processed Slot: 31 | Confirmed Slot: 31 | Finalized Slot: 0 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 30 | ◎499.999850000
> 00:00:17 | Processed Slot: 32 | Confirmed Slot: 31 | Finalized Slot: 1 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 31 | ◎499.999850000
> 00:00:17 | Processed Slot: 32 | Confirmed Slot: 32 | Finalized Slot: 1 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 31 | ◎499.999845000
> 00:00:17 | Processed Slot: 33 | Confirmed Slot: 33 | Finalized Slot: 2 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 32 | ◎499.999840000
> 00:00:17 | Processed Slot: 33 | Confirmed Slot: 33 | Finalized Slot: 2 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 32 | ◎499.999840000
> 00:00:18 | Processed Slot: 34 | Confirmed Slot: 34 | Finalized Slot: 3 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 33 | ◎499.999835000
> 00:00:18 | Processed Slot: 34 | Confirmed Slot: 34 | Finalized Slot: 3 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 33 | ◎499.999835000
> 00:00:18 | Processed Slot: 35 | Confirmed Slot: 35 | Finalized Slot: 4 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 34 | ◎499.999830000
> 00:00:18 | Processed Slot: 35 | Confirmed Slot: 35 | Finalized Slot: 4 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 35 | ◎499.999830000
> 00:00:19 | Processed Slot: 36 | Confirmed Slot: 36 | Finalized Slot: 5 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 35 | ◎499.999825000
> 00:00:19 | Processed Slot: 37 | Confirmed Slot: 37 | Finalized Slot: 6 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 36 | ◎499.999820000
> 00:00:19 | Processed Slot: 37 | Confirmed Slot: 37 | Finalized Slot: 6 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 36 | ◎499.999820000
> 00:00:20 | Processed Slot: 38 | Confirmed Slot: 38 | Finalized Slot: 7 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 37 | ◎499.999815000
> 00:00:20 | Processed Slot: 38 | Confirmed Slot: 38 | Finalized Slot: 7 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 37 | ◎499.999815000
> 00:00:20 | Processed Slot: 39 | Confirmed Slot: 39 | Finalized Slot: 8 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 38 | ◎499.999810000
> 00:00:20 | Processed Slot: 40 | Confirmed Slot: 39 | Finalized Slot: 9 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 39 | ◎499.999805000
> 00:00:21 | Processed Slot: 40 | Confirmed Slot: 40 | Finalized Slot: 9 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 39 | ◎499.999805000
> 00:00:21 | Processed Slot: 41 | Confirmed Slot: 41 | Finalized Slot: 10 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 40 | ◎499.999800000
> 00:00:21 | Processed Slot: 41 | Confirmed Slot: 41 | Finalized Slot: 10 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 40 | ◎499.999800000
> 00:00:21 | Processed Slot: 42 | Confirmed Slot: 42 | Finalized Slot: 11 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 41 | ◎499.999795000
> 00:00:22 | Processed Slot: 42 | Confirmed Slot: 42 | Finalized Slot: 11 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 41 | ◎499.999795000
> 00:00:22 | Processed Slot: 43 | Confirmed Slot: 43 | Finalized Slot: 12 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 42 | ◎499.999790000
> 00:00:22 | Processed Slot: 44 | Confirmed Slot: 43 | Finalized Slot: 13 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 43 | ◎499.999785000
> 00:00:23 | Processed Slot: 44 | Confirmed Slot: 44 | Finalized Slot: 13 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 43 | ◎499.999785000
> 00:00:23 | Processed Slot: 45 | Confirmed Slot: 45 | Finalized Slot: 14 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 44 | ◎499.999780000
> 00:00:23 | Processed Slot: 45 | Confirmed Slot: 45 | Finalized Slot: 14 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 44 | ◎499.999780000
> 00:00:23 | Processed Slot: 46 | Confirmed Slot: 46 | Finalized Slot: 15 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 45 | ◎499.999775000
> 00:00:24 | Processed Slot: 46 | Confirmed Slot: 46 | Finalized Slot: 15 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 45 | ◎499.999775000
> 00:00:24 | Processed Slot: 47 | Confirmed Slot: 47 | Finalized Slot: 16 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 46 | ◎499.999770000
> 00:00:24 | Processed Slot: 48 | Confirmed Slot: 47 | Finalized Slot: 17 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 47 | ◎499.999765000
> 00:00:24 | Processed Slot: 48 | Confirmed Slot: 48 | Finalized Slot: 17 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 47 | ◎499.999765000
> 00:00:25 | Processed Slot: 49 | Confirmed Slot: 49 | Finalized Slot: 18 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 48 | ◎499.999760000
> 00:00:25 | Processed Slot: 49 | Confirmed Slot: 49 | Finalized Slot: 18 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 48 | ◎499.999760000
> 00:00:25 | Processed Slot: 50 | Confirmed Slot: 50 | Finalized Slot: 19 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 49 | ◎499.999755000
> 00:00:25 | Processed Slot: 50 | Confirmed Slot: 50 | Finalized Slot: 19 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 49 | ◎499.999755000
> 00:00:26 | Processed Slot: 51 | Confirmed Slot: 51 | Finalized Slot: 20 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 50 | ◎499.999750000
> 00:00:26 | Processed Slot: 52 | Confirmed Slot: 52 | Finalized Slot: 21 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 51 | ◎499.999745000
> 00:00:26 | Processed Slot: 52 | Confirmed Slot: 52 | Finalized Slot: 21 | Full Snapshot Slot: - | Incremental Snapshot Slot: - | Transactions: 51 | ◎499.999745000
> ```
> 
> [@acheroncrypto](https://github.com/acheroncrypto) Could we reopen this issue? Thanks!

Hey, if you are still running into this issue i managed to fix mine using

`bind_address = "127.0.0.1"` instead of `bind_address = "0.0.0.0"`
