### ISSUE TITLE
Tests fail out the gate

### ISSUE THREAD

**Issue by developdeez** [coral-xyz/anchor#1865]
Keep getting this error when testing the base model.
       Is initialized!:
     Error: failed to get recent blockhash: FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED ::1:8899

I've tried while running validator locally and not. It doesn't work.
Is there a fix coming?

**Comment by developdeez** [comment]
Tried to send on discord but as the many who have tried to verify will tell you. it doesn't work :/

**Comment by tomlinton** [comment]
> FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED

If you've started a validator locally I can't see how it is possible that nothing is running on this port.

How are you running the tests? Does `solana-test-validator` give you any error output?

**Comment by tomlinton** [comment]
Actually maybe use node 16 per https://github.com/solana-labs/example-helloworld/issues/392#issuecomment-1014965594

**Comment by acheroncrypto** [comment]
This could be related to Node version as the previous comment suggested but it also could be a Solana setup issue.

Closing because it's an old issue and there isn't enough information.
