### ISSUE TITLE
Error: AnchorError occurred. Error Code: InstructionFallbackNotFound. Error Number: 101. Error Message: Fallback functions are not supported.

### ISSUE THREAD

**Issue by springrainroni** [coral-xyz/anchor#1872]
Error: AnchorError occurred. Error Code: InstructionFallbackNotFound. Error Number: 101. Error Message: Fallback functions are not supported.
I just want to mint nft. It shows me error in invoke method. When i remove invoke function from smart contract it executes. Please help me to get rid of this problem. Code github repo- https://github.com/springrainroni/nft_anchor.git

**Comment by yangyangpig** [comment]
can you solve the question？

**Comment by philetos** [comment]
make sure you have the most up to date IDL...checking this helped me solve this error
