### ISSUE TITLE
Anchor discord invite link broke

### ISSUE THREAD

**Issue by SuperCipher** [coral-xyz/anchor#1879]
⚠️ Don't use issues for support questions ("How does x feature work in Anchor? How to do x in Anchor?"). Use the discord instead https://discord.gg/GVRw4kHB (but don't ping maintainers). ⚠️
The discord link above ^ broke in the issue template. 
https://github.com/project-serum/anchor/blame/master/.github/issue_template.md#L1
![Screen Shot 2022-05-08 at 23 34 57](https://user-images.githubusercontent.com/6429197/167305907-44e0c641-fe99-4d1d-84a6-c6195e1d151f.png)

**Comment by acheroncrypto** [comment]
Anchor Discord invite link is https://discord.gg/NHHGSXAnXk.
