### ISSUE TITLE
No transaction simulation logs on failing test

### ISSUE THREAD

**Issue by nathanleclaire** [coral-xyz/anchor#1935]
An `anchor test` failing because of a transaction simulation failing only provides limited info on the failure. It would be good to dump the transaction simulation logs for that specific test like how `anchor.utils.features.set("debug-logs")` does.

**Comment by acheroncrypto** [comment]
Added in https://github.com/solana-labs/solana-web3.js/pull/2736, see https://github.com/coral-xyz/anchor/issues/2980#issuecomment-2160328549
