### ISSUE TITLE
Anchor Version Manager is Redundant

### ISSUE THREAD

**Issue by daweth** [coral-xyz/anchor#1940]
If there is only one active version of Anchor (0.24.2), why does AVM need to exist?

**Comment by daweth** [comment]
NVM. If there is only one version of Anchor, why does AVM need to exist?

**Comment by tomlinton** [comment]
There was/will be more versions. Plus you going to have to upgrade to the next active version somehow.

**Comment by acheroncrypto** [comment]
It's very useful for switching between versions.
