### ISSUE TITLE
Is it planned to have an unblocked client for Rust developpers?

### ISSUE THREAD

**Issue by Aursen** [coral-xyz/anchor#1980]
Hi,
For the moment there is only blocked client for Rust developers. In the update of Solana version 1.10.*, is it planned to integrate the non-blocking client in Anchor? Maybe with two features: blocking and non-blocking. And by default we have blocking one.

**Comment by armaniferrante** [comment]
No current plans but would love to see this!

**Comment by nabeel99** [comment]
A bit confused what do you mean by blocking/unblocking in terms of the client ? (noob here)

**Comment by fanatid** [comment]
> A bit confused what do you mean by blocking/unblocking in terms of the client ? (noob here)

sync vs async

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2488
