### ISSUE TITLE
Error: 'src.toArrayLike is not a function' found

### ISSUE THREAD

**Issue by dev-tom-0108** [coral-xyz/anchor#1981]
I have coded with anchor and have an error.
```js
 pub fn create_project(
        ctx: Context<CreateProject>,
        milestones: u8,
        _create_time: u64,
        m_amount: Vec<u64>,
        m_date: Vec<i64>,
    ) -> Result<()> {
```
and test typescript code is 
```js
    let mAmount: anchor.BN[] = [];
    let mDate: anchor.BN[]= [];
    for(let i = 0; i < milestones; i++) { 
        mAmount[i] = new anchor.BN(milestoneAmount[i]*DECIMALS);
        mDate[i] = new anchor.BN(milestoneDate[i]);
    } 
    console.log('==>creating project');

    tx.add(program.instruction.createProject(
        milestones, createTime, mAmount, mDate, {
        accounts: {
            creator: userAddress,
            taskList,
            systemProgram: SystemProgram.programId,
            rent: SYSVAR_RENT_PUBKEY,
        },
        instructions: [],
        signers: [],
    }));
```
and I got this error.
```shell
TypeError: src.toArrayLike is not a function
    at BNLayout.encode (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/borsh/src/index.ts:61:11)
    at Structure.encode (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/buffer-layout/lib/Layout.js:1263:26)
    at BorshInstructionCoder._encode (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/anchor/src/coder/borsh/instruction.ts:92:24)
    at BorshInstructionCoder.encode (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/anchor/src/coder/borsh/instruction.ts:75:17)
    at /home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/anchor/src/program/namespace/index.ts:64:43
    at Object.ix [as createProject] (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:60:15)
    at /home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/cli/script.ts:276:32
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/cli/script.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```
How can I fix it?

**Comment by anoushk1234** [comment]
> I have coded with anchor and have an error.
> 
> ```js
>  pub fn create_project(
>         ctx: Context<CreateProject>,
>         milestones: u8,
>         _create_time: u64,
>         m_amount: Vec<u64>,
>         m_date: Vec<i64>,
>     ) -> Result<()> {
> ```
> 
> and test typescript code is
> 
> ```js
>     let mAmount: anchor.BN[] = [];
>     let mDate: anchor.BN[]= [];
>     for(let i = 0; i < milestones; i++) { 
>         mAmount[i] = new anchor.BN(milestoneAmount[i]*DECIMALS);
>         mDate[i] = new anchor.BN(milestoneDate[i]);
>     } 
>     console.log('==>creating project');
> 
>     tx.add(program.instruction.createProject(
>         milestones, createTime, mAmount, mDate, {
>         accounts: {
>             creator: userAddress,
>             taskList,
>             systemProgram: SystemProgram.programId,
>             rent: SYSVAR_RENT_PUBKEY,
>         },
>         instructions: [],
>         signers: [],
>     }));
> ```
> 
> and I got this error.
> 
> ```shell
> TypeError: src.toArrayLike is not a function
>     at BNLayout.encode (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/borsh/src/index.ts:61:11)
>     at Structure.encode (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/buffer-layout/lib/Layout.js:1263:26)
>     at BorshInstructionCoder._encode (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/anchor/src/coder/borsh/instruction.ts:92:24)
>     at BorshInstructionCoder.encode (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/anchor/src/coder/borsh/instruction.ts:75:17)
>     at /home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/anchor/src/program/namespace/index.ts:64:43
>     at Object.ix [as createProject] (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:60:15)
>     at /home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/cli/script.ts:276:32
>     at Generator.next (<anonymous>)
>     at fulfilled (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/cli/script.ts:28:58)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> error Command failed with exit code 1.
> ```
> 
> How can I fix it?

milestones and createTime should be converted to BigNumber before passing them in, wrap them in anchor.BN()

**Comment by dev-tom-0108** [comment]
Great! I have fixed!
