### ISSUE TITLE
`Cross-program invocation with unauthorized signer or writable account` with Seed, bump

### ISSUE THREAD

**Issue by dev-tom-0108** [coral-xyz/anchor#1983]
I have coded like this:
```js
#[derive(Accounts)]
#[instruction(_create_time: u32)]
pub struct CreateProject<'info> {
    #[account(mut)]
    pub creator: Signer<'info>,

    #[account(
        init_if_needed,
        seeds = [creator.key().as_ref(), _create_time.to_string().as_bytes(),],
        bump,
        payer = creator,
        space = TaskList::LEN)]
    pub task_list: Account<'info, TaskList>,

    pub system_program: Program<'info, System>,
    pub rent: Sysvar<'info, Rent>,
}
```
In cli test code:
```js
 const [taskList, bump] = await PublicKey.findProgramAddress(
        [userAddress.toBuffer(), Buffer.from(createTime.toString())],
        PAYMENT_PROGRAM_ID,
 );

    tx.add(program.instruction.createProject(
        milestones, cTime, mAmount, mDate, {
        accounts: {
            creator: userAddress,
            taskList,
            systemProgram: SystemProgram.programId,
            rent: SYSVAR_RENT_PUBKEY,
        },
        instructions: [],
        signers: [],
    }));
```
And I got this error:
```ps
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Cross-program invocation with unauthorized signer or writable account
    at Connection.sendEncodedTransaction (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@solana/web3.js/src/connection.ts:4248:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Connection.sendRawTransaction (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@solana/web3.js/src/connection.ts:4210:20)
    at Connection.sendTransaction (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@solana/web3.js/src/connection.ts:4198:12)
error Command failed with exit code 1.
```
How can I fix it?

**Comment by guardian02262** [comment]
I solved that problem.

#[derive(Accounts)]
#[instruction(mission_id: String, bump: u8)]
pub struct CreateMissionPoolsContext<'info> {
    #[account(init, seeds=[b"mission".as_ref(), mission_id.as_ref()], bump, payer = admin, space = 8 + 32 + 1 + CUSTOM_STORATE)]
    pub mission_pool: Account<'info, MissionPool>,
    #[account(init, seeds=[b"rent".as_ref(), mission_id.as_ref()], bump, payer = admin, space = 8 + 32 + 1 + CUSTOM_STORATE)]
    pub rent_pool: Account<'info, MissionPool>,
    #[account(mut/*, constraint = admin.key() == ADMIN_KEY*/)]
    pub admin: Signer<'info>,
    pub system_program: Program<'info, System>
}

pub fn create_mission_pools(ctx: Context<CreateMissionPoolsContext>, mission_id: String, bump: u8) -> Result<()> {
        let mission_pool = &mut ctx.accounts.mission_pool;
        let rent_pool = &mut ctx.accounts.rent_pool;

        mission_pool.mission_id = mission_id.clone();
        mission_pool.bump = bump;
        rent_pool.mission_id = mission_id.clone();
        rent_pool.bump = bump;
        Ok(())
 }

**Comment by guardian02262** [comment]
let [rentPoolPda, bumpRent] = await anchor.web3.PublicKey.findProgramAddress
(
      [Buffer.from(RENT_POOL_SEED), Buffer.from(missionId)],
      new PublicKey(PROGRAM_ID)
    );

**Comment by guardian02262** [comment]
I am going to add web3 code to help out you.

  ```
export const makeCreateMissionPoolsTx = async (missionId: string) => {
    try {
      const program = getProgram();
      let instructions: any[] = [], signers: any[] = [];
      let [missionPoolPda, bumpmMission] = await anchor.web3.PublicKey.findProgramAddress(
        [Buffer.from(MISSION_POOL_SEED), Buffer.from(missionId)],
        new PublicKey(PROGRAM_ID)
      );
  
      let [rentPoolPda] = await anchor.web3.PublicKey.findProgramAddress(
        [Buffer.from(RENT_POOL_SEED), Buffer.from(missionId)],
        new PublicKey(PROGRAM_ID)
      );
  
      instructions.push(program.instruction.createMissionPools(missionId, bumpmMission, {
        accounts: {
          missionPool: missionPoolPda,
          rentPool: rentPoolPda,
          admin: ADMIN_WALLET.publicKey,
          systemProgram: SystemProgram.programId
        }
      }))
      signers.push(ADMIN_WALLET);
      const transaction = await makeTransaction(connection, instructions, signers, ADMIN_WALLET.publicKey);
      return transaction;
    }
    catch (error) {
      console.log('error', error);
    }
  
    return null;
  }
```

**Comment by dhruvja** [comment]
> I have coded like this:
> 
> ```js
> #[derive(Accounts)]
> #[instruction(_create_time: u32)]
> pub struct CreateProject<'info> {
>     #[account(mut)]
>     pub creator: Signer<'info>,
> 
>     #[account(
>         init_if_needed,
>         seeds = [creator.key().as_ref(), _create_time.to_string().as_bytes(),],
>         bump,
>         payer = creator,
>         space = TaskList::LEN)]
>     pub task_list: Account<'info, TaskList>,
> 
>     pub system_program: Program<'info, System>,
>     pub rent: Sysvar<'info, Rent>,
> }
> ```
> 
> In cli test code:
> 
> ```js
>  const [taskList, bump] = await PublicKey.findProgramAddress(
>         [userAddress.toBuffer(), Buffer.from(createTime.toString())],
>         PAYMENT_PROGRAM_ID,
>  );
> 
>     tx.add(program.instruction.createProject(
>         milestones, cTime, mAmount, mDate, {
>         accounts: {
>             creator: userAddress,
>             taskList,
>             systemProgram: SystemProgram.programId,
>             rent: SYSVAR_RENT_PUBKEY,
>         },
>         instructions: [],
>         signers: [],
>     }));
> ```
> 
> And I got this error:
> 
> ```postscript
> Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Cross-program invocation with unauthorized signer or writable account
>     at Connection.sendEncodedTransaction (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@solana/web3.js/src/connection.ts:4248:13)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Connection.sendRawTransaction (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@solana/web3.js/src/connection.ts:4210:20)
>     at Connection.sendTransaction (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@solana/web3.js/src/connection.ts:4198:12)
> error Command failed with exit code 1.
> ```
> 
> How can I fix it?

This error means that you are not passing the right seeds while doing the CPI call. You should share the function code to debug further. But it has to do mainly with the seeds.

**Comment by dhruvja** [comment]
> And I also did like this:
> 
> ```js
> #[derive(Accounts)]
> #[instruction(_create_time: String)]
> pub struct CreateProject<'info> {
>     #[account(mut)]
>     pub creator: Signer<'info>,
> 
>     #[account(
>         init_if_needed,
>         seeds = [creator.key().as_ref(), _create_time.as_ref()],
>         bump,
>         payer = creator,
>         space = TaskList::LEN)]
>     pub task_list: Account<'info, TaskList>,
> 
>     pub system_program: Program<'info, System>,
>     pub rent: Sysvar<'info, Rent>,
> }
> ```
> 
> ```js
> let cTime = createTime.toString();
>     // Get taskList publickey and bump
>     const [taskList, bump] = await PublicKey.findProgramAddress(
>         [userAddress.toBuffer(), Buffer.from(cTime)],
>         PAYMENT_PROGRAM_ID,
>     );
>     
>     let tx = new Transaction();
>     let mAmount: anchor.BN[] = [];
>     let mDate: anchor.BN[]= [];
>     for(let i = 0; i < milestones; i++) { 
>         mAmount[i] = new anchor.BN(milestoneAmount[i]*DECIMALS);
>         mDate[i] = new anchor.BN(milestoneDate[i]);
>     }
>     console.log('==>creating project');
>     console.log(taskList.toBase58());
>     console.log(userAddress.toBase58());
> 
>     tx.add(program.instruction.createProject(
>         milestones, cTime, mAmount, mDate, {
>         accounts: {
>             creator: userAddress,
>             taskList,
>             systemProgram: SystemProgram.programId,
>             rent: SYSVAR_RENT_PUBKEY,
>         },
>         instructions: [],
>         signers: [],
>     }));
> ```
> 
> I got this error
> 
> ```postscript
> Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x66
>     at Connection.sendEncodedTransaction (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@solana/web3.js/src/connection.ts:4248:13)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Connection.sendRawTransaction (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@solana/web3.js/src/connection.ts:4210:20)
>     at Connection.sendTransaction (/home/ubuntu/apollo/Web3Connect-SmartContract/freelancer/node_modules/@solana/web3.js/src/connection.ts:4198:12)
> error Command failed with exit code 1.
> ```

Well this error means that the instruction did not serialize which has to do with arguments you are passing i suppose. Please look into that.

**Comment by acheroncrypto** [comment]
Not a problem with Anchor, usage questions should be asked in [Solana StackExchange](https://solana.stackexchange.com/) or [Anchor Discord](https://discord.gg/NHHGSXAnXk).
