### ISSUE TITLE
Add implementation of `Discriminator` & `Owner` to instruction

### ISSUE THREAD

**Issue by cyphersnake** [coral-xyz/anchor#1994]
The discriminator is currently computed at compile time and inserted as a constant, inside `impl InstructionData`. I propose to move it to a separate implenatation for instructions, which will allow them to be used in any form. 

It may be worth move this to a separate trait so as not to confuse different entities for accounts and instructions, but in its current form, getting a discriminator through serialization of a mock instruction looks strange

**Comment by cyphersnake** [comment]
Added the `Owner` implementation here. In fact, if you are working with anchor-instructions from Rust, then without these traits it will be difficult for you to do any complicated things other than simple deserialization

I am now making a [tool](https://github.com/debridge-finance/solana-events-parser/blob/9a474369a76295b59d725b399a6652d999cc7de7/src/transaction_parser.rs#L63-L68) for working with logs, in conjunction with instructions, the absence of these traits is very felt there.

**Comment by cyphersnake** [comment]
And this will also allow to add an automatic implementation for `InstructionData`
```rust
pub trait InstructionData: Owner + Discriminator + AnchorSerialize {
    fn data(&self) -> Vec<u8> {
        let mut d = Self::discriminator().to_vec();
        d.append(&mut self.try_to_vec().expect("Should always serialize"));
        d
    }
}
```

**Comment by nabeel99** [comment]
Honestly wanted to do something similar, as a dapp which implement instruction introspection need this,  to do a more thorough validation, i implemented this as a seperate proc macro,
https://github.com/nabeel99/Sighash-Discriminator-Proc-Macro/tree/main/src
but would love to see if its implemented builtin such that there is no need to add another crate to do what is already done builtin

**Comment by cyphersnake** [comment]
@josephfernandez https://doc.rust-lang.org/reference/procedural-macros.html
@nabeel99 We also made a solution using a local macro, but now the general solution is waiting in the PR
