### ISSUE TITLE
avm install latest AND avm use latest NOT WORKING

### ISSUE THREAD

**Issue by scn-2000** [coral-xyz/anchor#1996]
Hey,
I've installed Anchor Version Manager. however, I can't install Anchor.
This is the output when I type "avm install latest" or "avm use latest":

Command 'avm' not found, did you mean:

  command 'pvm' from deb pvm (3.4.6-2build2)
  command 'lvm' from deb lvm2 (2.03.07-1ubuntu1)
  command 'vam' from deb vim-addon-manager (0.5.10)
  command 'vm' from deb mgetty-voice (1.2.1-1)
  command 'acm' from deb acm (5.0-29.2ubuntu1)
  command 'kvm' from deb qemu-kvm (1:4.2-3ubuntu6.23)

Try: sudo apt install <deb name>

What should I do?
Thanks for helping out :)

**Comment by sohrab-** [comment]
It looks like `avm` wasn't installed successfully. This is probably a question for [Discord](https://discord.gg/ysZcVS5N) than GitHub Issues.

**Comment by tomlinton** [comment]
As above 🙂

**Comment by CoolSaki** [comment]
Hello everyone!
I 'm trying build solana nft minting smart contract with rust so I'm going to use Anchor.
but I can't install Anchor in Linux.
This is the output when I type "avm install latest" or "avm use latest":

Command 'avm' not found, did you mean:

  command 'gvm' from snap gvm (1.1.0)
  command 'kvm' from deb qemu-kvm (1:4.2-3ubuntu6.23)
  command 'lvm' from deb lvm2 (2.03.07-1ubuntu1)
  command 'pvm' from deb pvm (3.4.6-2build2)
  command 'acm' from deb acm (5.0-29.2ubuntu1)
  command 'vm' from deb mgetty-voice (1.2.1-1)
  command 'vam' from deb vim-addon-manager (0.5.10)

See 'snap info <snapname>' for additional versions.
 Please help me.
Kind regards
