### ISSUE TITLE
Update inner dependency of crates `anchor-spl` and `anchor-lang`

### ISSUE THREAD

**Issue by sham789** [coral-xyz/anchor#1998]
⚠️ Don't use issues for support questions ("How does x feature work in Anchor? How to do x in Anchor?"). Use the discord instead https://discord.gg/GVRw4kHB (but don't ping maintainers). ⚠️

https://crates.io/crates/anchor-spl/0.24.2/dependencies

These crates versions as inner dependencies must be updated:
1. `spl-token`
2. `solana-program`
3. `spl-associated-token-account`

**Comment by sham789** [comment]
Dependant crates (these are used for Solend as oracle provider):

1. https://crates.io/crates/switchboard-v2
2. https://crates.io/crates/switchboard-program

**Comment by HgAmiui9** [comment]
```
[dependencies]
anchor-lang = "0.25.0"
```

**Comment by armaniferrante** [comment]
Can this be closed?
