### ISSUE TITLE
Anchor Build not Working 0.21.0

### ISSUE THREAD

**Issue by jakedamon** [coral-xyz/anchor#2007]
Trying to run `anchor build`
But I get 
`Failed to obtain package metadata: 'cargo metadata' exited with an error:     Updating crates.io index
error: failed to select a version for the requirement 'anchor-lang = "^0.21.0"'
candidate versions found which didn't match: 0.24.2
location searched: crates.io index
required by package 'programs v0.1.0 (/home/nomadicspark/Code/profile-solana/programs/programs/programs)'`

anchor-cli 0.21.0
avm 0.24.2
cargo 1.61.0
rustc 1.61.0
solana-cli 1.10.27

**Comment by callensm** [comment]
Older versions of anchor crates are yanked from `crates.io`. If you need to use an older version than the latest semver, you can use git dependencies and target a certain repository tag or ref.

**Comment by jakedamon** [comment]
Can you provide the terminal commands I would use to accomplish that?

**Comment by jakedamon** [comment]
I made the change, but still having issues.

`Failed to obtain package metadata: `cargo metadata` exited with an error:     Updating git repository `https://github.com/coral-xyz/anchor`
error: failed to get `anchor-lang` as a dependency of package `programs v0.1.0 (/home/nomadicspark/Code/profile-solana/programs/programs/programs)`

Caused by:
  failed to load source for dependency `anchor-lang`

Caused by:
  Unable to update https://github.com/coral-xyz/anchor?tag=0.21.0

Caused by:
  failed to find tag `0.21.0`

Caused by:
  reference 'refs/remotes/origin/tags/0.21.0' not found; class=Reference (4); code=NotFound (-3)`

**Comment by jakedamon** [comment]
Yes, thank you very much @callensm

**Comment by jakedamon** [comment]
I want to add that I also had to do
`wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1_amd64.deb
sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1_amd64.deb 
`
because I still had issues with another error. Just adding this here in case anyone else gets a similar error
`error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by zbcoding** [comment]
```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
```
https://solana.stackexchange.com/questions/3029/anchor-test-error-while-loading-shared-libraries-libssl-so-1-1
