### ISSUE TITLE
add skip-lint to Anchor.toml

### ISSUE THREAD

**Issue by dnut** [coral-xyz/anchor#2021]
There are plenty of good reasons to use unchecked accounts. `/// CHECK:` serves no purpose once you acknowledge that `AccountInfo` means "this doesn't need to be checked here". We decided to avoid the clutter and simply use `--skip-lint` all the time. That works, but it's kind of annoying. It would be nice if we could configure this at the project level with something in `Anchor.toml` like:
```toml
skip-lint = true
```

**Comment by armaniferrante** [comment]
An Anchor.toml override sounds good!

**Comment by armaniferrante** [comment]
Closed by #2026.
