### ISSUE TITLE
The test validator that Anchor test starts does not collect transaction fee (5000 lamports per signature)

### ISSUE THREAD

**Issue by littleV** [coral-xyz/anchor#2033]
My anchor version: `anchor-cli 0.24.2`
solana and solana-test-validator version: `solana-cli 1.10.0 (src:7dbde224; feat:275730699)`

To reproduce:

Start an empty project with: `anchor init test --javascript`

Replace the test.js in tests with the following code:
```
const anchor = require("@project-serum/anchor");
const splToken = require("@solana/spl-token");
const assert = require("assert");

describe("test", () => {
  it("Fee collected", async () => {
    // Add your test here.
    const provider = anchor.AnchorProvider.env();
    anchor.setProvider(provider);
    const program = anchor.workspace.Test;
    const alice = anchor.web3.Keypair.generate();
    await provider.connection.confirmTransaction(
      await provider.connection.requestAirdrop(
        alice.publicKey,
        100 * anchor.web3.LAMPORTS_PER_SOL
      ),
      "processed"
    );
    const aliceBalanceAfterAirdrop = await provider.connection.getBalance(alice.publicKey);
    const mint = await splToken.createMint(
      provider.connection,
      alice,
      alice.publicKey,
      alice.publicKey,
      9
    );
    const aliceBalanceAfterCreateMint = await provider.connection.getBalance(alice.publicKey);
    const mintRent = await provider.connection.getMinimumBalanceForRentExemption(splToken.MintLayout.span);
    // CreateMint charges 2 transaction fees (5000 lamports each)
    assert.equal(aliceBalanceAfterAirdrop, aliceBalanceAfterCreateMint +  mintRent + 5000 *2);
  });
});
```

Run with `anchor test` this fails with the following message:
```
 Fee collected:

      AssertionError [ERR_ASSERTION]: 100000000000 == 100000010000
      + expected - actual

      -100000000000
      +100000010000

      at Context.<anonymous> (tests/test.js:30:12)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Because the test validator that the anchor test starts does not collect any transaction fees.

However, if I run `solana-test-validator` separately, then run `anchor run test`, this test passes. Which means this test-validator collects the transaction fee properly.

I'm not sure if this is the intended behavior but I do not see any configuration on the `solana-test-validator` that disables the transaction fee.

**Comment by acheroncrypto** [comment]
I can reproduce this behavior but it seems to be an issue with `splToken.createMint` function rather than how Anchor initializes the test validator because sleeping 13s before the `splToken.createMint` function makes the test pass — interestingly sleeping 12s still makes it fail which leads me to believe the function somehow expects 32 blocks to be available after genesis(32 * ~400ms = 12.8s). Also, changing `splToken.createMint` function to another instruction e.g. `SystemInstruction.transfer` makes the test pass without having to wait.
