### ISSUE TITLE
anchor-spl has a version mismatch with spl_associated_token_account

### ISSUE THREAD

**Issue by cavemanloverboy** [coral-xyz/anchor#2035]
### Issue

 When trying to build something that uses anchor-spl 0.25.0, I got the following error:

```rust
error[E0433]: failed to resolve: could not find `instruction` in `spl_associated_token_account`
 --> [REDACTED]/anchor-spl-0.25.0/src/associated_token.rs:9:44
  |
9 |     let ix = spl_associated_token_account::instruction::create_associated_token_account(
  |                                            ^^^^^^^^^^^ could not find `instruction` in `spl_associated_token_account`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `anchor-spl` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It appears that anchor-spl lists `spl-associated-token-account = 1.0.3` as minimum version but the structure of that crate changed from 1.0.3 to 1.0.5 (i.e. not using semantic versioning) in a breaking way.

### Solution
Change 
```
spl-associated-token-account = "1.0.3"
```
to
```
spl-associated-token-account = "1.0.5"
```
in the anchor-spl Cargo.toml

**Comment by cavemanloverboy** [comment]
In 1.0.5, it is under [spl_associated_token_account](https://docs.rs/spl-associated-token-account/1.0.5/spl_associated_token_account/index.html)::[instruction](https://docs.rs/spl-associated-token-account/1.0.5/spl_associated_token_account/instruction/index.html)::[create_associated_token_account](https://docs.rs/spl-associated-token-account/1.0.5/spl_associated_token_account/instruction/fn.create_associated_token_account.html#)

In 1.0.3, it is under [spl_associated_token_account](https://docs.rs/spl-associated-token-account/1.0.3/spl_associated_token_account/index.html)::[create_associated_token_account](https://docs.rs/spl-associated-token-account/1.0.3/spl_associated_token_account/fn.create_associated_token_account.html#)

**Comment by cavemanloverboy** [comment]
For anyone that needs to fix this now and can't wait for 0.25.1, you can hacky fix this by forcing that "~1.0.3" to upgrade to "1.0.5" via
```
[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
spl-associated-token-account = "1.0.5"
```

**Comment by AnderUstarroz** [comment]
```
[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
spl-associated-token-account = "1.0.5"
```
Failed to obtain package metadata: `cargo metadata` exited with an error:     Blocking waiting for file lock on package cache
    Updating crates.io index
error: failed to select a version for `spl-associated-token-account`.
    ... required by package `anchor-spl v0.25.0`
    ... which satisfies dependency `anchor-spl = "^0.25.0"` of package `my_app v0.1.0 (/Users/anderustarroz/Sites/work/rust/my_app/programs/sol_games)`
versions that meet the requirements `~1.0.3` are: 1.0.5, 1.0.3

all possible versions conflict with previously selected packages.

  previously selected package `spl-associated-token-account v1.1.1`
    ... which satisfies dependency `spl-associated-token-account = "=1.1.1"` of package `solana-transaction-status v1.10.38`
    ... which satisfies dependency `solana-transaction-status = "=1.10.38"` of package `solana-client v1.10.38`
    ... which satisfies dependency `solana-client = "=1.10.38"` of package `solana-banks-server v1.10.38`
    ... which satisfies dependency `solana-banks-server = "=1.10.38"` of package `solana-program-test v1.10.38`
    ... which satisfies dependency `solana-program-test = "=1.10.38"` of package `my_app v0.1.0 (/Users/anderustarroz/Sites/work/rust/my_app/programs/sol_games)`
    ```

**Comment by AnderUstarroz** [comment]
The following dependencies fail when running `anchor build`:
```
[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
spl-associated-token-account = "1.0.5"
```
```
Failed to obtain package metadata: `cargo metadata` exited with an error:     Blocking waiting for file lock on package cache
    Updating crates.io index
error: failed to select a version for `spl-associated-token-account`.
    ... required by package `anchor-spl v0.25.0`
    ... which satisfies dependency `anchor-spl = "^0.25.0"` of package `my_app v0.1.0 (/Users/anderustarroz/Sites/work/rust/my_app/programs/sol_games)`
versions that meet the requirements `~1.0.3` are: 1.0.5, 1.0.3

all possible versions conflict with previously selected packages.

  previously selected package `spl-associated-token-account v1.1.1`
    ... which satisfies dependency `spl-associated-token-account = "=1.1.1"` of package `solana-transaction-status v1.10.38`
    ... which satisfies dependency `solana-transaction-status = "=1.10.38"` of package `solana-client v1.10.38`
    ... which satisfies dependency `solana-client = "=1.10.38"` of package `solana-banks-server v1.10.38`
    ... which satisfies dependency `solana-banks-server = "=1.10.38"` of package `solana-program-test v1.10.38`
    ... which satisfies dependency `solana-program-test = "=1.10.38"` of package `my_app v0.1.0 (/Users/anderustarroz/Sites/work/rust/my_app/programs/sol_games)`
    ```

**Comment by AnderUstarroz** [comment]
The following dependencies fail when running `anchor build`:
```
[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
spl-associated-token-account = "1.0.5"
```
Error log:
```
Failed to obtain package metadata: `cargo metadata` exited with an error:     Blocking waiting for file lock on package cache
    Updating crates.io index
error: failed to select a version for `spl-associated-token-account`.
    ... required by package `anchor-spl v0.25.0`
    ... which satisfies dependency `anchor-spl = "^0.25.0"` of package `my_app v0.1.0 (/Users/my_pc/Sites/work/rust/my_app/programs/sol_games)`
versions that meet the requirements `~1.0.3` are: 1.0.5, 1.0.3

all possible versions conflict with previously selected packages.

  previously selected package `spl-associated-token-account v1.1.1`
    ... which satisfies dependency `spl-associated-token-account = "=1.1.1"` of package `solana-transaction-status v1.10.38`
    ... which satisfies dependency `solana-transaction-status = "=1.10.38"` of package `solana-client v1.10.38`
    ... which satisfies dependency `solana-client = "=1.10.38"` of package `solana-banks-server v1.10.38`
    ... which satisfies dependency `solana-banks-server = "=1.10.38"` of package `solana-program-test v1.10.38`
    ... which satisfies dependency `solana-program-test = "=1.10.38"` of package my_app v0.1.0 (/Users/my_pc/Sites/work/rust/my_app/programs/sol_games)
```

**Comment by cavemanloverboy** [comment]
There must be some other dependency that is causing this issue because v0.25.0 uses solana v1.10.29 and you have
```
`spl-associated-token-account = "=1.1.1"` of package `solana-transaction-status v1.10.38`
```
