### ISSUE TITLE
Update anchor to v0.24.2 

### ISSUE THREAD

**Issue by HgAmiui9** [coral-xyz/anchor#2045]
Anchor is update to v0.24.2, keep up to date will make anchor more popular.

- Anchor book name. v0.24.0 -> v0.24.2
- Install way:
    Build from source for other operating systems without avm
    update to :
         ```cargo install --git https://github.com/project-serum/anchor --tag v0.24.2 anchor-cli --locked```

Maybe there are any other thing.

**Comment by callensm** [comment]
can you explain more what the issue you're reporting or trying to solve is?

**Comment by callensm** [comment]
@HgAmiui9 can this issue be closed?

**Comment by SkyYap** [comment]
I think he means this.
![Screenshot 2022-08-14 012653](https://user-images.githubusercontent.com/32660903/184504513-fb550607-6341-499f-913d-35003f08f23b.png)

In addition, I think update this https://www.anchor-lang.com/docs/installation

`cargo install --git https://github.com/coral-xyz/anchor --tag v0.24.1 anchor-cli --locked` 

to `cargo install --git https://github.com/coral-xyz/anchor --tag v0.25.0 anchor-cli --locked`
