### ISSUE TITLE
New Package `Not Found: Token`

### ISSUE THREAD

**Issue by dev-tom-0108** [coral-xyz/anchor#2049]
Before I have built the script code with @solana/spl-token --version "^0.1.8".
Then I used
```js
import { Token, TOKEN_PROGRAM_ID, AccountLayout, MintLayout, ASSOCIATED_TOKEN_PROGRAM_ID } from "@solana/spl-token";
```
And now I want to use the version "^0.2.0"
```js
import { @_Token_, TOKEN_PROGRAM_ID, AccountLayout, MintLayout, ASSOCIATED_TOKEN_PROGRAM_ID } from "@solana/spl-token";
```
This class `Token` is not allow to access in this version.

**Comment by armaniferrante** [comment]
Is there a reason to think this is related to Anchor?

**Comment by SkyYap** [comment]
Please open this issue in solana or spl-token related place. But I think I can tell you the reason is because Token is depreciated. Do refer to documentation.
