### ISSUE TITLE
Support for generating Typescript types for events

### ISSUE THREAD

**Issue by mcintyre94** [coral-xyz/anchor#2050]
Currently, given an IDL type `IDL` we can derive Typescript types for its accounts using eg. `IdlAccounts<IDL>['pixel']`

There doesn't seem to be an equivalent for event types. It'd be useful to have this so that we can use this type in event handling code on the client without manually re-writing the types. 

It seems that the IDL behaviour is similar to accounts, and we already have TS-friendly field names. So I think it'd just be a case of adding a similar utility type to `IdlAccounts<IDL>` that can handle events.

**Comment by acheroncrypto** [comment]
`IdlEvents` type was added in https://github.com/coral-xyz/anchor/pull/2185 .

Related: `Program.addEventListener` is now strongly typed(https://github.com/coral-xyz/anchor/pull/2627).
