### ISSUE TITLE
Camel casing breaks account discriminator for some names

### ISSUE THREAD

**Issue by KartikSoneji** [coral-xyz/anchor#2058]
The current implementation of `BorshAccountsCoder.accountDiscriminator()` blindly camel-cases the account names.
https://github.com/coral-xyz/anchor/blob/ae0131dbb42c142a5ef95e73da70c6780d49d5ad/ts/src/coder/borsh/accounts.ts#L97-L101

This breaks for names with consecutive capital letters, for example `CollectionPDA` is converted to `CollectionPda`.

```console
> printf "account:CollectionPDA" | sha256sum | head -c 16
32b77f6704d55c35

> printf "account:CollectionPda" | sha256sum | head -c 16
cb80777dea59e89d

# node
> anchor.BorshAccountsCoder.accountDiscriminator("CollectionPDA").toString("hex")
'cb80777dea59e89d'
```

The on-chain data uses `32b77f6704d55c35` as the account discriminator, so fetching the account results in `Error: Invalid account discriminator`

**Comment by bonham000** [comment]
Can also confirm this behavior is inconsistent based on how the account name is camelcased in generated TS clients.

**Comment by billythedummy** [comment]
> Can also confirm this behavior is inconsistent based on how the account name is camelcased in generated TS clients.

It seems like for defined structs, the generated `idl.json` has the name in PascalCase while the generated `idl.ts` has the name in camelCase

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/2824.
