### ISSUE TITLE
[avm] Globally installed anchor version is not correct

### ISSUE THREAD

**Issue by kingsframe** [coral-xyz/anchor#2060]
I have just encountered an issue updating anchor to latest using avm. After the update, anchor command no longer works 

```
anchor init anchor-hello-world
Only x86_64 / Linux distributed in NPM package right now.
Trying globally installed anchor.
Globally installed anchor version is not correct. Expected "anchor-cli 0.24.2", found "anchor-cli 0.25.0".
```
Anyone else encounter this issue? how should I delete the old version?

**Comment by hydrogenbond007** [comment]
I am facing this too! i gues I one installed it with npm and once with cargo which maybe caused some error

**Comment by tomlinton** [comment]
It is recommended you uninstall the npm based one with `npm uninstall -g @project-serum/anchor` and only use avm. Please ask support questions in Discord.

**Comment by hydrogenbond007** [comment]
@tomlinton  its still giving the same error, I did try this after asking in discord. 
Error - **Only x86_64 / Linux distributed in NPM package right now.
Trying globally installed anchor.
Globally installed anchor version is not correct. Expected "anchor-cli 0.24.2", found "anchor-cli 0.25.0".**

**Comment by kingsframe** [comment]
@tomlinton thanks for getting back to us. I really appreciate it. I have asked multiple times in the discord channel, but no one responds.

in terms of `npm uninstall -g @project-serum/anchor`. both npm and yarn says i never have installed the package?
```
yarn global remove @project-serum/anchor
yarn global v1.22.15
warning package.json: No license field
[1/2] 🗑  Removing module @project-serum/anchor...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
So i don't think it works right now, @hydrogenbond007 I have tried downgrading to 0.24.2 and that seems to work

**Comment by tomlinton** [comment]
Run `which anchor` and do whatever it takes to get rid of the NPM version

**Comment by hydrogenbond007** [comment]
@tomlinton been trying to do that, deleted the npm packages several times, and still getting the same error. I used avm to set the older version but 😅 didn't work

**Comment by vitordhers** [comment]
For Ubuntu users whom it may concern: my problem was that I'm using zsh instead of regular bash on Ubuntu. So that, I added the following to my .zshrc file (should be at home):

`export PATH="/home/**[username]**/.local/share/solana/install/active_release/bin:$PATH"`

also, uninstall npm anchor globally:
`npm uninstall -g @project-serum/anchor-cli` -- you might need to use sudo (thanks @tomlinton)

**Comment by dmrdvn** [comment]
in Terminal:

`$which anchor`
`$rm <File Path Shown on Screen>`
