### ISSUE TITLE
@project-serum/anchor-cli 0.25.0 now only comes with arm64 anchor binary

### ISSUE THREAD

**Issue by rado0x54** [coral-xyz/anchor#2076]
Hey,

my CI is failing with `"@project-serum/anchor-cli": "^0.25.0",` with the following error:

```
Failed to get version of local binary: /home/runner/work/sol-did/sol-did/program_v2/node_modules/@project-serum/anchor-cli/anchor: 1: Syntax error: "(" unexpected
```
it seems like the latest version only comes with an `arm64` binary:
```
root@8fd55d5c2037:/tmp/test# ./node_modules/\@project-serum/anchor-cli/anchor
bash: ./node_modules/@project-serum/anchor-cli/anchor: cannot execute binary file: Exec format error
root@8fd55d5c2037:/tmp/test# file ./node_modules/\@project-serum/anchor-cli/anchor
./node_modules/@project-serum/anchor-cli/anchor: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
```
Since we do not want to compile anchor manually on CLI, `@project-serum/anchor-cli` was an easy way to pull that in. Therefore I'd still prefer an only-x64 binary over an only-arm64 one. Ideal would be one that supports both architectures.

Thanks.

**Comment by kklas** [comment]
I also ran into this and as a workaround I used the one built by my github job in the `kklas/anchor-nightly` repo

```
"@project-serum/anchor-cli": "https://github.com/kklas/anchor-nightly/releases/download/anchor-cli-latest/anchor-cli-0.25.0-7eb8ca8.tgz",
```

Armani said on discord that he accidentally built it on his macbook instead of his linux machine and will fix it soon though.

**Comment by rado0x54** [comment]
Wow, thanks for the workaround. Will use until Armani updates the release.

**Comment by eoin-betdex** [comment]
@armaniferrante any chance of a 0.25.1 with an x64 binary?

**Comment by esemeniuc** [comment]
Also running into this issue

**Comment by kyanokashi** [comment]
me too

**Comment by sohrab-** [comment]
I'm guessing this won't be resolved till the next version?

**Comment by sohrab-** [comment]
I dunno if this helps anyone but I built the x86_64 binary from 0.25.0 crate and made it available here: https://github.com/labeleven-dev/anchor-binaries/releases/tag/1.0.0

More info in [README.md](https://github.com/labeleven-dev/anchor-binaries/blob/main/README.md)

**Comment by esemeniuc** [comment]
Any update on this?

**Comment by sohrab-** [comment]
0.26.0 has been released with the correct binaries now.
