### ISSUE TITLE
Installation incompatible with window 11

### ISSUE THREAD

**Issue by prakhardubey2002** [coral-xyz/anchor#2080]
Caused by:
  process didn't exit successfully: `C:\Users\Dell\AppData\Local\Temp\cargo-installbxk00K\release\build\lz4-sys-04cc6fce4401a058\build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  CC_x86_64-pc-windows-gnu = None
  CC_x86_64_pc_windows_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-gnu = None
  CFLAGS_x86_64_pc_windows_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-Wall" "-Wextra" "-o" "C:\\Users\\Dell\\AppData\\Local\\Temp\\cargo-installbxk00K\\release\\build\\lz4-sys-b1f17b681a26919f\\out\\liblz4/lib/lz4.o" "-c" "liblz4/lib/lz4.c"
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-Wall" "-Wextra" "-o" "C:\\Users\\Dell\\AppData\\Local\\Temp\\cargo-installbxk00K\\release\\build\\lz4-sys-b1f17b681a26919f\\out\\liblz4/lib/lz4frame.o" "-c" "liblz4/lib/lz4frame.c"

  --- stderr

  error occurred: Failed to find tool. Is `gcc.exe` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)

error: failed to run custom build command for `zstd-sys v2.0.1+zstd.1.5.2`

Caused by:
  process didn't exit successfully: `C:\Users\Dell\AppData\Local\Temp\cargo-installbxk00K\release\build\zstd-sys-6835696c1a4a47d2\build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  CC_x86_64-pc-windows-gnu = None
  CC_x86_64_pc_windows_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-gnu = None
  CFLAGS_x86_64_pc_windows_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-fvisibility=hidden" "-DZSTD_DISABLE_ASM=" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZDICTLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-DZSTD_LEGACY_SUPPORT=1" "-o" "C:\\Users\\Dell\\AppData\\Local\\Temp\\cargo-installbxk00K\\release\\build\\zstd-sys-5f68ba3594c32673\\out\\zstd/lib/common\\debug.o" "-c" "zstd/lib/common\\debug.c"
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-fvisibility=hidden" "-DZSTD_DISABLE_ASM=" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZDICTLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-DZSTD_LEGACY_SUPPORT=1" "-o" "C:\\Users\\Dell\\AppData\\Local\\Temp\\cargo-installbxk00K\\release\\build\\zstd-sys-5f68ba3594c32673\\out\\zstd/lib/common\\entropy_common.o" "-c" "zstd/lib/common\\entropy_common.c"

  --- stderr

  error occurred: Failed to find tool. Is `gcc.exe` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)

error: failed to compile `anchor-cli v0.25.0 (https://github.com/coral-xyz/anchor?tag=v0.25.0#6baed77e)`, intermediate artifacts can be found at `C:\Users\Dell\AppData\Local\Temp\cargo-installbxk00K`
Error: Failed to install 0.25.0, is it a valid version?

**Comment by SkyYap** [comment]
Reference: https://www.anchor-lang.com/docs/installation

Did you install using _Anchor version manager (avm) (recommended)_? 

I recommended installing through _Build from source for other operating systems without avm_

**Comment by prakhardubey2002** [comment]
I have fixed this problem by switching my rust toolchain and installing VS studio packages
