### ISSUE TITLE
Rust to JS case translation leads to "Invalid account discriminator" error thrown when borsh decoding within JS anchorClient

### ISSUE THREAD

**Issue by long-banana** [coral-xyz/anchor#2104]
## Issue:
When using multiple uppercased letters in the beginning of a struct name using the `#[account]` macro, the anchor JS client throws an unexpected invalid discriminator error when borsh decoding the account. 

## Steps to reproduce: 

Struct in contract is defined as

`pub struct NFTSetRedemptionState`

When calling fetch for this account within the anchor JS client

`anchorClient.account.nftSetRedemptionState.fetch(...)`

the following error is thrown even though borsh can successfully decode the account data

`Error( "Invalid account discriminator");`

Modifying the casing of the struct name in the contract avoids the issue within the JS client's Rust to JS case translating function

`pub struct NftSetRedemptionState`

## Expected behavior:
Improved Rust to JS case translation handling or error messaging in this context is needed.

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/2824.
