### ISSUE TITLE
I wanna transfer NFT's UpdateAuthority.

### ISSUE THREAD

**Issue by dev-tom-0108** [coral-xyz/anchor#2108]
Hi.
I am developing NFT mutation contract and hope to know how to transfer NFT's updateauthority to the program.
Plz answer~~

**Comment by acheroncrypto** [comment]
Please ask development related questions on [Solana StackExchange](https://solana.stackexchange.com) or [Anchor Discord](https://discord.gg/5bhZyEFGY8) instead.
