### ISSUE TITLE
build failed with anchor-client  0.25.0 

### ISSUE THREAD

**Issue by ViktorKirjanov** [coral-xyz/anchor#2109]
Hi, 
i have no idea how to make a build with anchor-clien. I got an error:

```
error[E0583]: file not found for module `sys`
   --> src/lib.rs:124:1
    |
124 | mod sys;
    | ^^^^^^^^
    |
    = help: to create the module `sys`, create file "/Users/viktor/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/sys.rs" or "/Users/viktor/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/sys/mod.rs"
```

i have only 3 dependencies and it is possible to make a build without anchor-client. Any ideas?
```
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
anchor-client = "0.25.0"
```

anchor-cli 0.25.0
rustc 1.62.1 (e092d0b6b 2022-07-16)

**Comment by SkyYap** [comment]
You import a module called sys but didn't include in your code. I think it is not related to dependencies.

**Comment by acheroncrypto** [comment]
`anchor-client` cannot be used on-chain. See [restrictions](https://docs.solana.com/developing/on-chain-programs/developing-rust#restrictions) of on-chain programs.
