### ISSUE TITLE
anchor init results in broken rust-analyzer

### ISSUE THREAD

**Issue by TovarishFin** [coral-xyz/anchor#2111]
It seems that there was an update from anyhow which breaks rust-analyzer. I am not an expert in rust, but AFAIK, version 1.0.60 uses "backtrace" features which breaks due to needing nightly. using version 1.0.58 allows everything to work normally again. Can you pin the dependency to use 1.0.58 so that rust-analyzer works?

**Comment by TovarishFin** [comment]
For the record, my current band-aid for this is to override the `Cargo.lock` entry for `anyhow` like so:
```toml
[[package]]
name = "anyhow"
version = "1.0.58"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb07d2053ccdbe10e2af2995a2f116c1330396493dc1269f6a91d0ae82e19704"
```

**Comment by TovarishFin** [comment]
Adding initial error received when using neovim (coc-rust-analyzer) & vscode rust-analyzer extension for more visibility:
I got this error:
```
failed to run build scripts
Check the server logs for additional info.
```

Hopefully anyone else running into this issue stumbles onto this issue.

**Comment by 0xPratik** [comment]
I am getting the same error when i do anchor init

**Comment by zkRemda** [comment]
I'm getting the same issue. 0.25.0  (latest, installed, current)

**Comment by 0xPratik** [comment]
Did anyone got a fix for it ?

**Comment by TovarishFin** [comment]
> Did anyone got a fix for it ?

I already gave the fix in this issue:
https://github.com/coral-xyz/anchor/issues/2111#issuecomment-1209524622

**Comment by TovarishFin** [comment]
This problem has been fixed by `anyhow` itself in it's latest release: https://github.com/dtolnay/anyhow/releases/tag/1.0.61

`anchor init` will automatically pull down this version rather than version `1.0.60` which was breaking things. 

I will go ahead and close this issue since it is no longer relevant.
