### ISSUE TITLE
Don't use wallet object for `account.createInstruction` function

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#2112]
Instead, we should just use the `publicKey` on the provider object directly. Accessing the `wallet` on the provider is no longer necessary. See https://github.com/coral-xyz/anchor/blob/master/ts/src/program/namespace/account.ts#L291-L295

**Comment by Niceural** [comment]
Hi! 
Can I start working on this issue and propose a PR? 
Thanks!

**Comment by Niceural** [comment]
PR #2116

**Comment by aroraprince** [comment]
This issue can be closed since the above PR has been merged!
