### ISSUE TITLE
Wrong exit status

### ISSUE THREAD

**Issue by RuvenSalamon** [coral-xyz/anchor#2117]
# Description
Anchor commands (that wrap around other commands like `cargo build-bpf`) that result in something failing still return exit status 0.

# Steps to reproduce
```
anchor init some-name
cd some-name
echo mistake >> programs/some-name/src/lib.rs
anchor build
echo $?
```

# Actual result
exit status is 0

# Expected result
exit status is equal to the exit status of the underlying command. (something non zero as compilation fails)

# System
anchor-cli: 0.24.2
avm: 0.24.2
Apple M1 Pro
rustc 1.63.0
solana-cargo-build-bpf 1.10.32
bpf-tools v1.27

**Comment by RuvenSalamon** [comment]
I've had the same result when using anchor-cli 0.25.0
I've investigated commit `6baed77eb57d41455a5f3c1e026d86da756d1c8e` and seen that the correct exit status reaches this point https://github.com/coral-xyz/anchor/blob/master/cli/src/lib.rs#L2030 but I'm then stuck and not able to explain why it goes wrong.

**Comment by RuvenSalamon** [comment]
I'm on a Apple M1 Pro btw, forgot to add that to the description.

**Comment by RuvenSalamon** [comment]
if you run `cargo build-bpf; echo $?` you will see an exit status of 1

**Comment by RuvenSalamon** [comment]
Same happens with `anchor test`. It also happens in our pipelines (they were green but should have been red because of failing tests) which run linux. This has the risk of buggy code being merged and maybe released.

**Comment by dnut** [comment]
> Same happens with anchor test. It also happens in our pipelines (they were green but should have been red because of failing tests) which run linux. This has the risk of buggy code being merged and maybe released.

Yeah this is causing us the same issue in github workflows. I'd like to see this issue get fixed. It's probably an easy fix, but I have too much on my plate at the moment.

**Comment by richardwu** [comment]
Looks like this is fixed upstream (tested when building from source). 

The reason `cargo install --git https://github.com/project-serum/anchor avm --locked` and `avm install latest` doesn't pick up latest master is because `avm install` uses github tags (most recent one was v0.25.0 on July 5th w/o fixes). 

@armaniferrante any way to cut a new release, or at the very least create a v0.25.1 tag so `avm` can install the latest?

**Comment by RuvenSalamon** [comment]
> Looks like this is fixed upstream (tested when building from source).
> 
> The reason `cargo install --git https://github.com/project-serum/anchor avm --locked` and `avm install latest` doesn't pick up latest master is because `avm install` uses git tags (most recent one was v0.25.0 on July 5th w/o fixes).
> 
> @armaniferrante any way to cut a new release, or at the very least create a v0.2X.X tag so `avm` can install the latest?
> 
> EDIT: You can use the latest upstream cli built from source in your CI/CD for now:
> 
> ```shell
> # Optional --rev <SHA> to freeze source
> cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force
> ```

Great to hear 👍! I'll look for the fix because I'm curious to see what the problem was. Do we know the commit/pr? Because it should link to this issue for people to see.

**Comment by RuvenSalamon** [comment]
It seems like this is still an issue in 0.26.0 🤔

**Comment by Henry-E** [comment]
Looks fine to me? Maybe this is a mac thing. Either way, open to checking out any PRs that purport to solve the issue.
```
root:~/tests/some-name# anchor build
Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
cargo-build-bpf child: /root/.local/share/solana/install/active_release/bin/cargo-build-sbf --arch bpf
error: expected one of `!` or `::`, found `<eof>`
  --> programs/some-name/src/lib.rs:16:1
   |
16 | mistake
   | ^^^^^^^ expected one of `!` or `::`

error: could not compile `some-name` due to previous error

root:~/tests/some-name# echo $?
1
```

**Comment by RuvenSalamon** [comment]
![image](https://user-images.githubusercontent.com/14349484/214328100-5b127f35-f4f8-4a53-aa0e-23f5353d8f9e.png)
Hmm maybe it is a mac thing indeed. Will try to find time if I can (or someone else of course) to look at it.

**Comment by RuvenSalamon** [comment]
![image](https://user-images.githubusercontent.com/14349484/214328526-825af311-dd48-472a-99ec-a6e1497d46a9.png)
Maybe it's a mac thing indeed. Will try to find time if I can (or someone else can dive in of course)

**Comment by RuvenSalamon** [comment]
I have some further information:

If I check out the commit of the 0.26.0 tag and build the cli, I'm able to use the executable in target to build the broken anchor program and have it return the correct status.

If I run anchor 0.26.0 installed through avm I have the wrong exit status.

I reinstalled 0.26.0 through avm and noticed:
`Compiling anchor-cli v0.26.0 (/Users/ruvensalamon/.cargo/git/checkouts/anchor-bf03d42499b9267c/347c225/cli)`
which seems to be correct so not sure where the difference lies right now.

**Comment by RuvenSalamon** [comment]
submitted a PR https://github.com/coral-xyz/anchor/pull/2370

**Comment by RuvenSalamon** [comment]
> Looks fine to me? Maybe this is a mac thing. Either way, open to checking out any PRs that purport to solve the issue.
> 
> ```
> root:~/tests/some-name# anchor build
> Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
> cargo-build-bpf child: /root/.local/share/solana/install/active_release/bin/cargo-build-sbf --arch bpf
> error: expected one of `!` or `::`, found `<eof>`
>   --> programs/some-name/src/lib.rs:16:1
>    |
> 16 | mistake
>    | ^^^^^^^ expected one of `!` or `::`
> 
> error: could not compile `some-name` due to previous error
> 
> root:~/tests/some-name# echo $?
> 1
> ```

PR opened!
