### ISSUE TITLE
Consumed 20000 compute units Error

### ISSUE THREAD

**Issue by dev-tom-0108** [coral-xyz/anchor#2157]
I have built the program with lots of calculations but the program failed with compute unit exceed error.

The error msg : Program returned error: exceeded maximum number of instructions allowed (200000) at instruction #55823

And here is the solscan url: https://solscan.io/tx/2FVZvQLxVaJ5NmdUSscPtnvvc2sVYzvD8AbpZKxPdgjWhr5wNkyYWB99QqxWa4Kc5EbCCUeLnaUFkeoCBpx1AAAv?cluster=devnet

Plz teach me the reason.

**Comment by chinepun** [comment]
There is a maximum number of compute units a transaction can use. When this number is exceeded, the program can no longer continue as it is using too much computational resources. You can read more [here](https://docs.solana.com/developing/on-chain-programs/debugging#monitoring-compute-budget-consumption). The usual recommendation when this happens is to reduce the unnecessary logging your program does.

**Comment by Henry-E** [comment]
Recommend asking on https://solana.stackexchange.com/ . As this is not an issue with anchor itself but the solana runtime.

**Comment by acheroncrypto** [comment]
In addition to the previous comments: https://solanacookbook.com/references/basic-transactions.html#how-to-change-compute-budget-fee-priority-for-a-transaction
