### ISSUE TITLE
AddEventListener does not work for multiple events of the same name

### ISSUE THREAD

**Issue by filipzeta** [coral-xyz/anchor#2161]
If subscribing to an event using `addEventListener` in `event.ts`, `this._eventListeners` does not correctly concatenate if listening to multiple events with the same name. Therefore only the final listener will fire.

This is an issue if subscribing to the same event name multiple times in one script. We can see this by adding extra logging:

```
...
Add event listener, eventName= TradeEvent
...
Add event listener, eventName= OrderCompleteEvent
...
Add event listener, eventName= TradeEvent
this._eventListeners before: Map(2) { 'TradeEvent' => [ 0 ], 'OrderCompleteEvent' => [ 1 ] }
this._eventCallbacks before: Map(2) {
  0 => [ 'TradeEvent', [Function (anonymous)] ],
  1 => [ 'OrderCompleteEvent', [Function (anonymous)] ]
}
this._eventListeners after: Map(2) { 'TradeEvent' => [ 2 ], 'OrderCompleteEvent' => [ 1 ] }
this._eventCallbacks after: Map(3) {
  0 => [ 'TradeEvent', [Function (anonymous)] ],
  1 => [ 'OrderCompleteEvent', [Function (anonymous)] ],
  2 => [ 'TradeEvent', [Function (anonymous)] ]
}
...
```

`this._eventListeners` after adding should contain `'TradeEvent' => [ 0, 2 ]`, but instead is only `'TradeEvent' => [ 2 ]`

I'm fixing this bug, but also wanted to open an issue to document it 😊

**Comment by Henry-E** [comment]
Looks like this got merged, congrats!
