### ISSUE TITLE
Failing anchor build

### ISSUE THREAD

**Issue by jveer634** [coral-xyz/anchor#2163]
I am trying to build a simple counter program using `WSL2 Ubuntu`. I have successfully installed rust solana-cli and anchor. But when trying to run any command mainly `anchor build` on the build I am getting the following error

![image](https://user-images.githubusercontent.com/47923507/188144362-6e2f5647-6c52-412c-bc45-7df7078ab93b.png)

**Anchor:** anchor-cli 0.24.2
**Solana cli**: solana-cli 1.11.10 (src:843e018c; feat:4253057308)
**Rust**: rustc 1.63.0 (4b91a6ea7 2022-08-08)
**Cargo**: cargo 1.63.0 (fd9c4297c 2022-07-01)

**Comment by Henry-E** [comment]
Looks like a rust issue / solana cli issue maybe?

**Comment by jveer634** [comment]
Well there are other projects that are working using the same environment, cli and rust. And that's why I'm q bit confused

**Comment by Henry-E** [comment]
Did you fix this? It looks like you might need to try reinstalling the CLI since it's not found on the path. There might be another issue at play here but I don't think the github issues for anchor is the right place for that. Maybe the [solana stackexchange](https://solana.stackexchange.com/)
