### ISSUE TITLE
Ledger WALLET Approve Issue!

### ISSUE THREAD

**Issue by dev-tom-0108** [coral-xyz/anchor#2166]
Hi, everyone
I am building dapp with ledger wallet.
I am using the `promise.all` in FE code.
Let's imagine as sending 3 ixs in 1 transaction.
For phantom case, users should click one approve in phantom pop-up then it works well.
For ledger case, users should click 1 time approve in FE pop-up and click 3 times on the ledger to approve for manual. so you should 4  times manual operations.
How can I fix this issue? One time approve is the main problem. 
plz help me.

**Comment by Henry-E** [comment]
A haiku written by chatgpt:
```
Bright blue sky above
This doesn't seem like an anchor
Related problem, no.
```
