### ISSUE TITLE
'anchor deploy' deploys non-verifiable build by default

### ISSUE THREAD

**Issue by serejke** [coral-xyz/anchor#2167]
**Problem**
I would like to deploy the verifiable build.

`anchor build` builds non-verifiable program and saves the result to `target/deploy/<program>.so`

`anchor build --verifiable` builds the program in a Docker container and saves the result to `target/verifiable/<program>.so`

but then
`anchor deploy` takes the non-verifiable build from `target/deploy` but not from `target/verifiable`.
I have to manually copy&replace the `<program>.so` from the `target/verifiable` to `target/deploy` before running the `anchor deploy`

**Suggestion**
Add a `--verifiable` CLI option to the `anchor deploy` to change the program path.

**Comment by esemeniuc** [comment]
Would love to see this also!

**Comment by Henry-E** [comment]
yeh, this sounds cool. I could see this being easy enough to add for anyone interested in doing a PR.

**Comment by aroraprince** [comment]
Came across this issue:
I might be able to fix it.
Seems the changes need to be made somewhere around here [fn deploy](https://github.com/coral-xyz/anchor/blob/master/cli/src/lib.rs#L2834).
