### ISSUE TITLE
TS: `fetchNullable` should be robust towards accounts only holding SOL

### ISSUE THREAD

**Issue by rado0x54** [coral-xyz/anchor#2172]
Hey, I'm running into a problem with the `fetch` or `fetchNullable` methods. This code can easily cause an exception if someone just transfers some lamports to a PDA address before the program initializes an account there. Then is causes the following exception.

```
Error: Invalid account discriminator
    at BorshAccountsCoder.decode (/[...]/@project-serum/anchor/src/coder/borsh/accounts.ts:61:13)
    at AccountClient.fetchNullable (/[...]/@project-serum/anchor/src/program/namespace/account.ts:140:33)
```
That's what the account looks like when transferring SOL into it:
```
{
  "pubkey": "9qZkiciPFPdhJNNdPgmkDRjDJuPTthTJjvUSoewHNrLT",
  "account": {
    "lamports": 1000000000,
    "data": [
      "",
      "base64"
    ],
    "owner": "11111111111111111111111111111111",
    "executable": false,
    "rentEpoch": 0
  }
}
`
```

In my mind `fetchNullable` should NOT fail in this case (e.g. when the account has NO data) and just return `null`.

If the community agrees I'd PR a fix.

Note, is not a problem for the program later to init an account at that PDA later (and change the owner from the System Program to the Program itself)

**Comment by Henry-E** [comment]
Think we fixed this when merging your PR
