### ISSUE TITLE
anchor.BN.toBuffer("le", 8) not working on the browser

### ISSUE THREAD

**Issue by netpoe** [coral-xyz/anchor#2177]
In my typescript tests, this works fine: 

```typescript
async function getGamePDA(setupArgs: { amount: anchor.BN; feePercentage: number; houseWallet: anchor.web3.PublicKey }) {
    const [pdaPubKey, _] = await PublicKey.findProgramAddress(
      [
        anchor.utils.bytes.utf8.encode("game"),
        setupArgs.amount.toBuffer("le", 8), <== HERE
        Float64Array.of(setupArgs.feePercentage).buffer,
        setupArgs.houseWallet.toBuffer(),
      ],
      program.programId,
    );

    return pdaPubKey;
  }
```

but when running it on the browser, I get this error: 

```
TypeError: setupArgs.amount.toBuffer is not a function
```

What's the right browser alternative? I've tried `new Uint8Array(setupArgs.amount.toNumber())`, but get this error instead: `TypeError: Max seed length exceeded` — The Rust anchor program is expecting this: `data.amount.to_le_bytes().as_ref(),`

**Comment by callensm** [comment]
`Buffer` may not be available in your code bundle depending on the version of node you are building from. Importing a polyfill should solve it.

**Comment by devDesu** [comment]
Try to use `BN.toArrayLike`
