### ISSUE TITLE
IDLs in target/idl/*.json does not match with target/types/*.ts

### ISSUE THREAD

**Issue by rado0x54** [coral-xyz/anchor#2187]
Hello,

there is an inconsistency with the IDL generation in `target/idl/*.json` and `target/types/*.ts` which breaks implementations that rely on the IDL from the `ts` version.

We have the following account in our program:
```
#[account]
pub struct DidAccount {
```

In `target/idl/*.json` it generates to
```
...
  "accounts": [
    {
      "name": "DidAccount",
      "type": {
        "kind": "struct",
...
```

In `target/types/*.ts` it generates to

```
...
export const IDL: SolDid = {
...
  "accounts": [
    {
      "name": "didAccount",
      "type": {
        "kind": "struct",
...
```

In my opinion, the correct fix would to have the Account Name also capitalized in IDL **and** type in ``target/types/*.ts`. This would additionally require an update to the `Program` interface, where currently camelCase is expected:
Current:
```
program.account.didAccount
```
New:
```
program.account.DidAccount
```

I consider this quite the major inconsistency and projects relying directly on the generated `*.ts` are likely to run into problems when not using the JSON IDL directly.

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/2824.
