### ISSUE TITLE
Upgrading from 0.24.2 to 0.25.0

### ISSUE THREAD

**Issue by plasmare** [coral-xyz/anchor#2197]
Just updated my program anchor_lang and anchor_spl dependencies from 0.24.2 to 0.25.0, then upgraded the program, and now some of my endpoints don't work. I'm getting: 

"failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0"

If I go and change the dependencies back to 0.24.2 and upgrade the program, everything is fine again. I'm not really sure what could be going on here, as this is literally the only change.

**Comment by Henry-E** [comment]
Hope you found the help you needed, even if it wasn't here
