### ISSUE TITLE
Tutorials Link is broken

### ISSUE THREAD

**Issue by kunalchhabra37** [coral-xyz/anchor#2199]
Tutorial link on the [anchor_lang rust docs](https://docs.rs/anchor-lang/latest/anchor_lang/#:~:text=Anchor%20%E2%9A%93%20is%20a%20framework,management%20for%20developing%20complete%20applications) is broken.

![Screenshot (33)](https://user-images.githubusercontent.com/76837213/192291045-148e8926-0850-47ed-8908-9f1ecb02087b.png)

**Comment by SkyYap** [comment]
I click your link and I was redirect to [](https://docs.rs/anchor-lang/latest/anchor_lang/) and view it without any issue.

**Comment by kunalchhabra37** [comment]
In doc.rs checkout the tutorial link, it's broken. Not the docs rs link.

**Comment by SkyYap** [comment]
> In doc.rs checkout the tutorial link, it's broken. Not the docs rs link.

Ohh I didnt view it clearly. I think you can refer to their latest tutorial through the [Github](https://github.com/coral-xyz/anchor) Getting Started part. 

There are 2 tutorials. The older documentation is [this](https://www.anchor-lang.com/) while the latest one is [this](https://book.anchor-lang.com/) Think they phase out the older tutorial link which is hosted on GitHub and didn't replace the link with the new one.

**Comment by Henry-E** [comment]
This sounds like issue solved 🤷
