### ISSUE TITLE
Accounts + Program IDL/Schema traits

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#22]
## Motivation

Suppose I had a field `foo` of type `crate_a::MyAccountsA` that is embedded into `crate_b::MyAccountsB` as follows.

```rust
// crate_a/src/lib.rs

#[derive(Accounts)]
pub struct MyAccountsA {
 ...
}
```

```rust
// crate_b/src/lib.rs

#[derive(Accounts)]
pub struct MyAccountsB {
  foo: crate_a::MyAccountsA,
}
```

I would want the IDL emitted for `crate_b` to have all the type i+ account nformation for `foo`. 

Currently this information is only available to `crate_a`, and so `crate_b` would either have to re-define `crate_a::MyAccountsA` in its own `src/lib.rs` or use all the accounts in flattened form, instead of composing `crate_a::MyAccountsA` directly.

## Solution

To achieve this, we can have the various macros generate trait implementations providing IDL/type information. Additionally, we probably need to add some type of `build.rs` file that calls these generated traits to output the IDL, instead of just parsing the program's file directly, as we do now. 

The build steps might be organized into

1. Walk entire crate to find IDL types.
2. Generate idl.rs file, invoking the traits on the IDL types.
3. Emit IDL by running the build.rs file

**Comment by paul-schaaf** [comment]
related: #454
