### ISSUE TITLE
Add cli support to generate crate from an IDL

### ISSUE THREAD

**Issue by chinepun** [coral-xyz/anchor#2204]
[anchor-gen](https://github.com/saber-hq/anchor-gen/) generates a crate from an IDL but it is difficult to set up, would it be okay to send a PR that utilizes anchor-gen to generate the crate from an IDL directly from anchor CLI. @armaniferrante

**Comment by Henry-E** [comment]
The usage of the anchor-gen library seems to be that you have an IDL but nothing else and it generates a crate for you to import and do CPI stuff with. While I get that adding this to the CLI would sort of make sense, it's different from the typical use case of anchor, which is that you have a program etc. 

Plus I'm not sure about taking on additional responsibility for maintaining this extra feature. Maybe you could instead add CLI support for anchor-gen?

Certainly willing to think about it for the future though. It is an important thing to note that people might only have an IDL and still want to interact with programs on that basis. So maybe there would be some way to make it easier to have two-way IDL/package generation. Not sure when/if this would ever happen though.
