### ISSUE TITLE
proc-macro2-diagnostics update

### ISSUE THREAD

**Issue by cholcombe973** [coral-xyz/anchor#2210]
https://github.com/coral-xyz/anchor/blob/862575a6496e2d92e9e95d226bc44d7cae1594e1/lang/syn/src/codegen/accounts/constraints.rs#L2

Is it possible to remove this dependency? The underlying library hasn't been updated in years and it's causing a dependency conflict with actix-web because it uses a pinned version of `version-check`. I submitted an issue to the library author in the hopes that it'll get updated but I'm trying this avenue as well.

**Comment by Henry-E** [comment]
Ok, I found the root usage of this library and it's linked to notifying users about deprecated constraints. https://github.com/coral-xyz/anchor/pull/429/files

It's definitely possible we could get rid of this crate if it was possible to replace the existing code with something else. That said it doesn't seem like a super high priority, though happy to look at PRs.
