### ISSUE TITLE
Feature Request: Union Account Loaders

### ISSUE THREAD

**Issue by mgild** [coral-xyz/anchor#2211]
If I am versioning an account type in an action, it would be great to support something like

```
#[derive(Accounts)]
pub struct ExampleAction<'info> {
    pub union: UnionAccountLoader<'info, AccountDataV1, AccountDataV2>,
}
```

This could be extended to support optional accounts as well

```
#[derive(Accounts)]
pub struct ExampleAction<'info> {
    pub optional: UnionAccountLoader<'info, OptionalAccount, None>,
}
```

Perhaps `None` could be a special case since it is not a type, but then `load` and `load_mut` could also take the type you are trying to load as well.

**Comment by Henry-E** [comment]
I'm not sure how feasible it is for us to support a list of possible generic types for accounts. However, there is an optional account feature coming to anchor that has syntax more like `Option<UnionAccountLoader<'info, OptionalAccount>>`. Check out https://github.com/coral-xyz/anchor/pull/2101
