### ISSUE TITLE
Update Docs on How to Import a program for CPI

### ISSUE THREAD

**Issue by jim4067** [coral-xyz/anchor#2217]
I believe this section of the docs can be improved by using cargo-add since it is natively incorporated into Rust by writing `cargo add --path "../puppet/programs/puppet" --features=cpi`

https://github.com/coral-xyz/anchor/blob/fd467df93245ceca0ea2a2ce865a0da7967982b7/docs/src/pages/docs/cross-program-invocations.md?plain=1#L101-L105

I also got an error when I used `path = ../puppet` but I fixed it using `path = ../puppet/programs/puppet`

**Comment by Henry-E** [comment]
Regarding the first part, I think that sure, we could make it easier for people by adding the `cargo add` command, although I think that is less clear for people to understand what they need to do in future cases. It also helps them to see what's going on.

Secondly I don't think `../puppet/programs/puppet` is correct? Maybe you're adding it to a different cargo.toml or perhaps cargo.toml is being called from a different directory. You could totally be right but I would expect the tests to fail if this were the case surely?
