### ISSUE TITLE
Arc<dyn Signer> vs Rc<dyn Signer>

### ISSUE THREAD

**Issue by cavemanloverboy** [coral-xyz/anchor#2218]
When writing a library with `Rc<T>`, sometimes the author must choose whether they will 

1) limit use cases for the sake of `Rc` performance vs `Arc` performance
2) allow for more use cases (e.g. multithread programs) by replacing `Rc` with `Arc`.

The `anchor_client` is one such library. I have some multi-threaded system that uses a struct with an `anchor_client` `Client` as a field, which internally contains an `Rc<Keypair>`. This makes the type `!Send` and `!Sync` and thus unusable for my multithreaded system. 

I suspect that the minor performance cost incurred from going from `Rc<Keypair>` to `Arc<Keypair>` is worth allowing using a client in a multi-threaded program. So, I propose we do that. I have my local fork where this is done for my own use case, but would like to see this done upstream.

**Comment by cavemanloverboy** [comment]
It could even be behind a feature flag to give users of the library the option between `Rc<T>` and `Arc<T>`

**Comment by cavemanloverboy** [comment]
With this, should come other things like expanding the type signature to `Arc<dyn Signer + 'static + Send + Sync>`

**Comment by Henry-E** [comment]
So it sounds like you would like the anchor client to start using `Arc` instead of `Rc` to enable multithreading, which seems like a pretty reasonable request from a rust client. I haven't looked much into anchor's rust client, so i don't know where or for what it's currently using `rc` but I'd definitely be open to discussing this in a PR if you have any specific suggestions or changes.

**Comment by cavemanloverboy** [comment]
I don't want to introduce anything that requires nightly, but I'll see if I can get something going in stable Rust this weekend.

**Comment by Henry-E** [comment]
Just checking that you know Solana compiles with its own custom version of rust. It's only 1.59 for the 1.13 cli but might be up to 1.64 whenever 1.14 becomes the stable version

**Comment by cavemanloverboy** [comment]
Cool, check out https://github.com/coral-xyz/anchor/pull/2321

**Comment by cavemanloverboy** [comment]
> Just checking that you know Solana compiles with its own custom version of rust. It's only 1.59 for the 1.13 cli but might be up to 1.64 whenever 1.14 becomes the stable version

This is not relevant for the client, btw. The clients aren't compiled to bpf.

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2321
