### ISSUE TITLE
Async vs Sync RpcClient

### ISSUE THREAD

**Issue by cavemanloverboy** [coral-xyz/anchor#2219]
By default, the `.rpc()` method of the `anchor_client` `Program` returns a blocking RpcClient. It would be great if we could have the option to request the async `RpcClient` via `.async_rpc()` perhaps. The async `RpcClient` is under a different module of the solana_client, which `anchor_client` already re-exports.

I have done this on my local fork but would like to see this upstream.

**Comment by Henry-E** [comment]
Happy to look at a PR

**Comment by cavemanloverboy** [comment]
I'll get you a PR this weekend

**Comment by cavemanloverboy** [comment]
PR is at https://github.com/coral-xyz/anchor/pull/2322

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2322.
