### ISSUE TITLE
error[E0635]: unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by ctindogarus4f** [coral-xyz/anchor#2226]
This happens when initialising a project with anchor.

Steps to reproduce it:
1. anchor init counterapp
2. cd counterapp
3. anchor build

```bash
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /Users/constantindogaru/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.46/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

The versions that I'm using are the following:
```bash
$ solana --version
solana-cli 1.9.4 (src:8ce65878; feat:3258470607)
$ rustc --version
rustc 1.66.0-nightly (c0983a9aa 2022-10-12) (the error happens with the 1.64 stable version as well)
$ anchor --version
anchor-cli 0.25.0
```

OS: macOS Monterey, Apple M1 Pro chipset

**Comment by smexxxx** [comment]
Having the same issue

**Comment by ctindogarus4f** [comment]
any solution with this? currently blocking me from building anything on solana...

**Comment by gmaijoe** [comment]
You can fix this by going into cargo.lock and manually replacing the existing `proc-macro2` package with

```
[[package]]
name = "proc-macro2"
version = "1.0.40"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "dd96a1e8ed2596c337f8eae5f24924ec83f5ad5ab21ea8e455d3566c69fbcaf7"
dependencies = [
 "unicode-ident",
]
```

**Comment by fuzzyyeti** [comment]
I'm having the same issue as well. I tried the solution above, but proc-macro2 1.0.40 didn't meet the dependency for syn. I'm not sure how to generate a checksum to downgrade syn in the rust.lock file.

**Comment by fuzzyyeti** [comment]
This solution from the Anchor Discord worked for me. Here's how to fix the dependencies using cargo instead of directly editing the cargo.lock file.
`cargo update -p syn --precise 1.0.99; cargo update -p proc-macro2 --precise 1.0.43`

**Comment by ctindogarus4f** [comment]
> This solution from the Anchor Discord worked for me. Here's how to fix the dependencies using cargo instead of directly editing the cargo.lock file. `cargo update -p syn --precise 1.0.99; cargo update -p proc-macro2 --precise 1.0.43`

this worked like a charm, but anchor still needs to fix the original issue. We shouldn't patch it manually or ask in discord for solutions

**Comment by ctindogarus4f** [comment]
I don't remember what solved the issue. I think it was the `solana-cli` tool that needed an upgrade + some `solana` commands to get rid of the errors.

**Comment by acheroncrypto** [comment]
Closing as this doesn't seem to be an issue anymore.
