### ISSUE TITLE
Install anchor with cargo failed

### ISSUE THREAD

**Issue by f5i23q999d** [coral-xyz/anchor#2229]
Here's the error information,

 = note: /usr/bin/ld: /tmp/cargo-installMARu1k/release/deps/libopenssl-e941b450aebef610.rlib(openssl-e941b450aebef610.openssl.e1663c67-cgu.3.rcgu.o): in function `openssl::error::Error::get':
          openssl.e1663c67-cgu.3:(.text._ZN7openssl5error5Error3get17h139db04d2a1924cbE+0x5d): undefined reference to `ERR_get_error_all'
          collect2: error: ld returned 1 exit status

 and i had run the following command:
`sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y pkg-config build-essential libudev-dev
`

**Comment by SkyYap** [comment]
Think you are using Window and installing using cargo. It doesn't work on Window. I have made a video on how to install anchor without using avm and you are required to install WSL2 to run anchor in future. Here's the video: https://www.youtube.com/watch?v=AL5dTscNlmA&feature=youtu.be

**Comment by Henry-E** [comment]
Ok, so this is a windows thing.
