### ISSUE TITLE
IDL generation fails on arrays where the size is an associated constant

### ISSUE THREAD

**Issue by EquilateralDelta** [coral-xyz/anchor#2286]
Checked with `anchor-cli 0.24.2`
```
const B: usize = 4;

#[account]
pub struct A {
    pub works: [(); 4],
    pub also_works: [(); B],
    pub does_not_work: [(); A::C],
}

impl A {
    const C: usize = 4;
}
```
In the case of the code below, `anchor build` successfully builds a contract, but on the IDL generation step build fails with
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', lang/syn/src/idl/mod.rs:204:76
```
If the field of `does_not_work` is commented out, everything works.

**Comment by Henry-E** [comment]
I feel like this is a known issue. Maybe the IDL generation needs to do a better job at correctly accessing constants but not entirely sure what the solution looks like tbh.

**Comment by EquilateralDelta** [comment]
I think it's not a critical problem to rewrite a code to use a regular constant instead of an associated one, but it can be very confusing for someone to find the culprit of this error. As a suggestion, maybe giving more meta information about a struct and field that causes IDL generation to fail would help locate a problem much more easily.

**Comment by Henry-E** [comment]
While fixing and improving IDL related generation stuff is a probably the number 3 anchor priority for me, I don't quite know when I'll be able to get to this. In the meantime PRs are welcome or maybe someone else more familiar with the IDL code could look into it.

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/2824.
