### ISSUE TITLE
Manually create CPI client for Serum DEX

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#23]
Create a `dex` module analogous to https://github.com/project-serum/anchor/blob/master/spl/src/token.rs in the `anchor_spl` crate.

**Comment by Henry-E** [comment]
Bumping this. Would be great to have 
```
- InitializeMarket
- NewOrder(V?)
- ConsumeEvents
- CancelOrder(V?)
- SettleFunds
```

**Comment by armaniferrante** [comment]
Currently have `new_order` and `settle_funds` from #224.. The rest are straightforward to add as needed.

**Comment by Henry-E** [comment]
Think we mostly sorted this over time.
