### ISSUE TITLE
Anchor build doesn't understand nested structs

### ISSUE THREAD

**Issue by fedorerd** [coral-xyz/anchor#2300]
I believe, there is more stuff linked with nested structs, but as for now I faced these 2 issue:s

**Build doesn't check required by (init) and similar marks accounts passed in nested structs**
I have context initializing account:
```
#[derive(Account)]
pub struct Context<'info> {
    #[account(init, space = 20)]
    pub a: Account<'info, A>,
    pub b: B<'info>
}
```
And B here is a nested reusable struct (meant to be such)
```
#[derive(Account)]
pub struct B<'info> {
    pub system_program: Program<'info, System>
}
```

So I am passing system program into nested B struct. Despite that, build will fail with such error:
`error: the init constraint requires the system_program field to exist in the account validation struct. Use the Program type to add the system_program field to your validation struct.`

**(close =) mark on account does not allow to pass accounts from nested structs.**
```
#[derive(Account)]
pub struct Context<'info> {
    #[account(mut, close = b.signer]
    pub a: Account<'info, A>,
    pub b: B<'info>
}

#[derive(Account)]
pub struct B<'info> {
    #[account(mut)]
    pub signer: Signer<'info>
}
```

Build will panic with `error: expected ,` error (instead saw `.` in `b.signer`).

Some deeper checks of nested stuff might be cool

**Comment by Henry-E** [comment]
Nested structs aren't particularly well supported at the moment. It's kind of a messy macro at the moment and is more likely to be removed or replaced with some different functionality than to get added functionality.
