### ISSUE TITLE
lang: Unit structs not allowed in IDL 

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#232]
Unit and tuple structs are explicitly disallowed in the program interface definition, currently.

**Comment by mschneider** [comment]
"not allowed" should be enforced when updating IDL. it actually happened already twice that one of our apps broke because of the tuple enum exception.

**Comment by darkmode-ff** [comment]
would love to see this become active again 👀

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2824.
