### ISSUE TITLE
Support using references to account info in account struct

### ISSUE THREAD

**Issue by Henry-E** [coral-xyz/anchor#2324]
As people start using more and more accounts in their programs thanks to the lookup table functionality, they might start having issues with stack memory from having so many accounts in the account struct. One possible solution to this would be to allow references to AccountInfo in the account struct instead of cloning, which we currently do. Supporting syntax like this possibly:

```
#[derive(Accounts)]
pub struct MyStruct<'a, 'info> {
   pub my_account: &'a AccountInfo<'info>,
}
```

**Comment by cavemanloverboy** [comment]
should probably close this

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2656
