### ISSUE TITLE
avm install doesn't work

### ISSUE THREAD

**Issue by HZfive** [coral-xyz/anchor#2328]
`avm install 0.26.0`
![image](https://user-images.githubusercontent.com/97534416/208798557-b8d5f5ed-ed9f-4dcc-a2f4-df75a47d69ea.png)
`cargo install --git https://github.com/project-serum/anchor avm --locked --force`
![image](https://user-images.githubusercontent.com/97534416/208798812-46e96749-5db9-4892-86ff-bdd64fabe213.png)

**Comment by sohrab-** [comment]
It looks like you're on an older version of Rust. clap 4.0.0+ needs Rust 1.60 and above. You can check the version by running `rustc --version`.

If it is old, you can do a `rustup update` (and something like `rustup default stable`) to get on the latest version.

**Comment by Henry-E** [comment]
Ah sorry for this but it does look like the solution is to just update your rust to at least 1.60. Avm should work ok then
