### ISSUE TITLE
Error codes numbers are inaccurate

### ISSUE THREAD

**Issue by fedorerd** [coral-xyz/anchor#2341]
When you are declaring multiple enums unders #[error_code] attribute, error codes numbers are quire inaccurate.

For example, I have these errors in my program:
```rust
#[error_code]
pub enum FirstCaseErrors {
    #[msg("First")]
    First
}

#[error_code]
pub enum SecondCaseErrors {
    #[msg("Second")]
    Second
}
```

In IDL only errors from `FirstCaseErrors` will be generated. IDL will ignore SecondCaseErrors (however, it will still be presented in the list of types, just "msg" is missing).

Moreover, if we will receive these errors, their codes will be the same. So if transaction panics with `FirstCaseErrors::First`, anchor error object will display error code number 6000. If it panics with `SecondCaseErrors::Second`, error code number will be also 6000. Which is a bit annoying, especially if we are wishing to parse errors by this numeric code.

**Comment by Henry-E** [comment]
The attribute `#[error_code]` only supports a single usage of the attribute. 

Just going to close this because i'm not clear that it's actually an error unless someone wants to add support for multiple uses of it. Which might require quite extensive changes.
