### ISSUE TITLE
Add token_2022 program id support

### ISSUE THREAD

**Issue by lempiy** [coral-xyz/anchor#2354]
`spl_token_2022` has released feature to revoke token transfer approval not only by owner but also by delegate. 
https://github.com/solana-labs/solana-program-library/pull/2872
I got issues trying to import and use `spl_token_2022::revoke` instruction in anchor program using standard `solana_program::invoke`.

```rust
fn revoke_approve<'info>(
    owner_ata: &Account<'info, TokenAccount>,
    delegate: &Signer<'info>,
) -> Result<()> {
    let cpi_program = &spl_token_2022::id();
    let revoke_instruction = revoke(cpi_program, &owner_ata.key(), &delegate.key, &[])?;
    invoke(&revoke_instruction, &[owner_ata.to_account_info(), delegate.to_account_info()])?;
    Ok(())
}
```
Getting error message during execution.
`Unknown program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb`
Is it possible to make `spl_token_2022::revoke` working ?

**Comment by Henry-E** [comment]
Anchor doesn't support spl token_2022, which uses a different program address. So there would have to be a whole other version of this file https://github.com/coral-xyz/anchor/blob/master/spl/src/token.rs which uses the correct token_2022 program id.

**Comment by lempiy** [comment]
Thanks.
Is it possible to create crate, smth like:
`anchor-spl-2022 = "0.26.0"`
compatible with `anchor-lang` ?

**Comment by Henry-E** [comment]
What you're describing is only how the crate would be imported?

Usually this is specified in the dependences, usually in a format more like
```
[dependencies]
anchor-spl = { version = "0.26.0", features = ["token-2022"] }
```
but this is only the import statement, someone still needs to add the `token-2022` stuff!

**Comment by lempiy** [comment]
As far as I get, token accounts created by old program could not be mutated by program 2022. So in order use self-revoke, token and token account should be created with token 2022 program ?

**Comment by Henry-E** [comment]
yes
