### ISSUE TITLE
spl-token metadata is missing wrappers for unverify_collection and unverify_sized_collection_item

### ISSUE THREAD

**Issue by web3omega** [coral-xyz/anchor#2368]
spl-token metadata `spl/src/metadata.rs` is missing wrappers for `unverify_collection` and `unverify_sized_collection_item`

**Comment by web3omega** [comment]
I created them in my own repo, I can create a PR
https://github.com/coral-xyz/anchor/compare/master...web3omega:anchor:master

**Comment by Henry-E** [comment]
Sure, PRs welcome but please add a small test for each if possible

**Comment by web3omega** [comment]
It seems there are no tests for SPL or spl-token-metadata - yet. Only some `token-proxy` tests.
https://github.com/coral-xyz/anchor/tree/master/tests/spl

I can derive some tests from my own project repo to here as I'm already using these new functionality locally. Will do it later this week.
