### ISSUE TITLE
ts: idl enum vields with snake_case have wrong type

### ISSUE THREAD

**Issue by devDesu** [coral-xyz/anchor#2374]
Names of enum variants fields are being converted to *camelCase* during idl parse while typescript types use name as-is.
So when we do `program.account.fetch` of account with enum struct typescript don't allow us to use correct `someField` property and forces to use `some_field` (which will be undefined during runtime)

```type: {
        kind: "enum",
        variants: [
          {
            name: "X",
            fields: [
              {
                name: "some_field",
                type: "publicKey",
              },
            ],
          },
        ]
}
```

Possible solution is to use some typescript camelCase converter in `DecodeEnumField` type
![image](https://user-images.githubusercontent.com/11212162/215045546-bedb5168-ef17-4867-97fa-1ec5ceeeabac.png)

**Comment by devDesu** [comment]
Another solution is to not convert enum variants fields names to camelCase

**Comment by Henry-E** [comment]
Is this problem only with enum types or does it also happen with structs?

**Comment by devDesu** [comment]
> Is this problem only with enum types or does it also happen with structs?

Haven't tested yet, I'll check it

**Comment by devDesu** [comment]
Looks like `Structs` are unaffected
