### ISSUE TITLE
Issues while trying to run Anchor project

### ISSUE THREAD

**Issue by crazydevlegend** [coral-xyz/anchor#2389]
Hi, I just created an Anchor project using `anchor init` terminal.
When I run `anchor build`, it succeeds, but it gives me errors when I run `anchor test`.
I didn't make any modifications to the project that was created automatically by `anchor init`.

I've been asking to senior Rust developers on Discord for several days, but none of them could tell the trick.
I'm not sure this is something related to version-management, or ...
I beg team's review on this issue.

and here's the link to my repo I created for you to check.
https://github.com/crazydevlegend/anchor-workspace

I'll be adding screenshots for versions on my end as attachment.
![image](https://user-images.githubusercontent.com/94694049/217059145-31505224-8456-49e9-a442-5cda24e171f3.png)
![image](https://user-images.githubusercontent.com/94694049/217059466-fc364c84-e2bf-4518-8998-ba1299b9276b.png)

**Comment by Henry-E** [comment]
Don't use solana cli version 1.15

**Comment by crazydevlegend** [comment]
Then which version would you recommend, @Henry-E ?

**Comment by Henry-E** [comment]
anything stable / 1.14. I don't remember what anchor is using at the moment in github ci but you could check and use that. Also this is definitely discord territory. There's plenty of stuff already there highlighting the issue with using 1.15

**Comment by crazydevlegend** [comment]
@Henry-E I installed v1.14 (the stable version you mentioned), but not able to resolve it yet...

**Comment by crazydevlegend** [comment]
Here's the error I get after installing v1.14
![image](https://user-images.githubusercontent.com/94694049/217698891-41b7a67c-8e9a-4683-a4f2-a378f9690b33.png)

**Comment by Aursen** [comment]
`sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y pkg-config build-essential libudev-dev libssl-dev`
