### ISSUE TITLE
Discord invite links in anchor repo

### ISSUE THREAD

**Issue by Henry-E** [coral-xyz/anchor#2405]
There are about 8 different discord invite links in the anchor repo. They should probably all be replaced with a single canonical link. Is it generally safe to post a discord invite link that doesn't expire?

**Comment by mafux777** [comment]
I think it would be. You seem to have a robust verification mechanism (at least anti-bot)

**Comment by Henry-E** [comment]
Great ok, well got to find time to make a PR that adds this as the canonical link

https://discord.gg/NHHGSXAnXk
