### ISSUE TITLE
"init" subcommand has the `--ts` option, is it okay to have `--rust`, I prefer having just one language

### ISSUE THREAD

**Issue by guanqun** [coral-xyz/anchor#241]
Instead of relying on two language (rust for the on-chain program, and js/ts for the deployment/client).

**Comment by armaniferrante** [comment]
Good point. I'm for it.

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2805:

```
anchor init <NAME> --test-template rust
```

https://www.anchor-lang.com/release-notes/0.30.0#rust-test-template
