### ISSUE TITLE
anchor doesn't support Solana CLI Version 1.15.2(latest)

### ISSUE THREAD

**Issue by Grim-R3ap3r** [coral-xyz/anchor#2422]
**error**:function _zn14solana_program4vote5state9votestate11deserialize17he5005e2fd6c7f858e stack offset of 6344 exceeded max offset of 4096 by 2248 bytes, please minimize large stack variables

works fine for previous builds of Solana.

**Comment by Henry-E** [comment]
There's nothing we can really do about this until the 1.15 solana-program crate (not the CLI) becomes stable and we release a version supporting that. The 1.15 solana cli / solana-program bumps the rust version used by their custom compiler from 1.60 to probably the latest rust version, 1.67 or something.
