### ISSUE TITLE
instructions suffixed with `_#` produces `0x65`

### ISSUE THREAD

**Issue by callensm** [coral-xyz/anchor#2433]
When an instruction name is suffixed by an underscore and a number (e.g. `my_ix_5`), the program will build and generate the IDL properly, but when invoking the instruction it will fail for an anchor `0x65` error:

```
/// 101 - Fallback functions are not supported
#[msg("Fallback functions are not supported")]
InstructionFallbackNotFound,
```

> NOTE: This does not occur if the instruction name suffix does not include the underscore (i.e. `my_ix5` works properly)

**Comment by armaniferrante** [comment]
dup of https://github.com/coral-xyz/anchor/issues/279 ?
