### ISSUE TITLE
Missing Token-2022 program supports on `associated_token` constraint

### ISSUE THREAD

**Issue by grhbit** [coral-xyz/anchor#2434]
Hello, I'm glad to hear that Anchor supports Token-2022 Program now!
Anchor v0.27.0 supports Token-2022 Program and many cases work well.

But I found two error cases for `associated_token` constraint.

**Case 1**

Use `associated_token` with `init_if_need`

```rust
#[derive(Accounts)]
pub struct Case1<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    #[account(
        init_if_needed,
        payer = authority,
        associated_token::mint = mint,
        associated_token::authority = authority,
    )]
    pub token_account: InterfaceAccount<'info, TokenAccount>,
    #[account(
        mint::decimals = 9,
        mint::authority = authority,
    )]
    pub mint: InterfaceAccount<'info, Mint>,
    pub token_program: Interface<'info, TokenInterface>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
}
```

Error Messages:
`Error: AnchorError caused by account: token_account. Error Code: ConstraintAssociated. Error Number: 2009. Error Message: An associated constraint was violated.`

https://github.com/coral-xyz/anchor/blob/3b45144787a0493caa8fc07de35e8cfd5fe98543/lang/syn/src/codegen/accounts/constraints.rs#L901

**Case 2**

Use `associated_token` constraint

```rust
#[derive(Accounts)]
pub struct Case2<'info> {
    pub authority: SystemAccount<'info>,
    #[account(
        associated_token::mint = mint,
        associated_token::authority = authority,
    )]
    pub token_account: InterfaceAccount<'info, TokenAccount>,
    pub mint: InterfaceAccount<'info, Mint>,
}
```
`Error: AnchorError caused by account: token_account. Error Code: AccountNotAssociatedTokenAccount. Error Number: 3014. Error Message: The given account is not the associated token account.`
https://github.com/coral-xyz/anchor/blob/3b45144787a0493caa8fc07de35e8cfd5fe98543/lang/syn/src/codegen/accounts/constraints.rs#L625

Both cases did not use `token_program` to make ATA.

**Comment by valentinmadrid** [comment]
@grhbit Please let me know if this works for you.

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2603
