### ISSUE TITLE
package `anchor-derive-accounts v0.27.0` cannot be built because it requires rustc 1.60 or newer, while the currently active rustc version is 1.59.0-dev

### ISSUE THREAD

**Issue by mondalraj** [coral-xyz/anchor#2445]
Hello there.
I am new to the ecosystem of anchor and rust.
I want to build a smart contract with solana, for that I have init an anchor project.
But while running anchor build / test I am getting the following error - 

Can anyone please guide me how to resolve this issue

![](https://cdn.discordapp.com/attachments/889702325231427584/1089497204017868890/Screenshot_2023-03-26_at_4.01.22_PM.png)

`rustup --version `: rustup 1.25.2 (17db695f1 2023-02-01)
`rustc --version` rustc 1.68.1 (8460ca823 2023-03-20)
`anchor --version` anchor-cli 0.27.0

**Comment by sukanyaparashar** [comment]
I am also experiencing the same issue :(

**Comment by mondalraj** [comment]
@sukanyaparashar I think we have multiple rust versions installed in our system, that is why  we are facing this issue.

**Comment by sukanyaparashar** [comment]
> @sukanyaparashar I think we have multiple rust versions installed in our system, that is why we are facing this issue.

@mondalraj , I just solved the issue by deleting the solana folder completely and also removing the `PATH` variable from the `.zshrc` file and then reinstalling solana again.
 This solved my issue. Hope it works for you as well.

**Comment by mondalraj** [comment]
@sukanyaparashar Thanks for your solution.

I also tried it at first, but the issue still persists for my case.
I followed this [https://solana.stackexchange.com/a/4170](https://solana.stackexchange.com/a/4170)

**Comment by stevepryde** [comment]
I'm still experiencing the same issue too. I deleted and reinstalled the latest stable solana toolchain and still it's the same.

I ran the official solana install script and it installed to `.local/share/solana/install/releases/` (Linux).
It put its own Rust compiler in 
`.local/share/solana/install/releases/stable-616d8d67978c325087cc5a9f33307f54eee48b6e/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/bin/`

And if I do `rustc --version` I get `rustc 1.59.0-dev`.

Do we need to use a beta version of solana?

**Comment by ShaunSHamilton** [comment]
As far as I understand it, there is some version of rustc shipped with the `solana` cli (or tools used by it), and the stable version of `solana` (1.13.8) has `rustc 1.59`.

What worked for me (either):
a) Change `anchor-lang` dep to `0.25.0` in `Cargo.toml`
b) Install version `1.15` of `solana`

**Comment by mondalraj** [comment]
Thanks @ShaunSHamilton @sukanyaparashar 

My issue is now resolved.
Previously Solana Stable Version 1.13 was installed on my system.

But anchor version was 0.27.0
So I uninstalled current solana-cli from my system, removed the $PATH

And reinstalled solana 1.15 version.

Now It is working fine.
