### ISSUE TITLE
Provide Boxed account type for AccountInfo

### ISSUE THREAD

**Issue by SushantChandla** [coral-xyz/anchor#2449]
Using `AccountInfo` or `UncheckedAccount` in the contexts the size of a context increase exponential which causes Stack violation. An AccountInfo takes about 48 bytes which is very high. 

Proposed Solution: Introduce Boxed for AccountInfo

**Comment by acheroncrypto** [comment]
Not exactly sure if there is a reason why `Box` is only supported with `Account` and `InterfaceAccount` but adding support for other types seems plausible.

**Comment by Aursen** [comment]
This is a problem with the macro proc in the Anchor library, I'll take care of it once my PR is accepted

**Comment by acheroncrypto** [comment]
I think this would be mostly useless now after https://github.com/coral-xyz/anchor/pull/2656, since using `UncheckedAccount` only uses 8 bytes (compared to 48 bytes for `AccountInfo`).
