### ISSUE TITLE
Redundant Copy-Paste of Program IDs

### ISSUE THREAD

**Issue by buffalojoec** [coral-xyz/anchor#2454]
How can we possibly make this process smoother or go away completely?

There's two spots that can drive a dev crazy whenever a fresh build is done, or if you're developing locally and do a `cargo clean`:
* `Anchor.toml`
* `lib.rs` : `declare_id`

Is there any way we can eliminate some of the redundancy of the process of updating your program's ID?

For context, I know the process most devs typically fall into is as follows:
* `cargo clean` or `anchor build` for the first time
* `anchor deploy`
  * Now, here the CLI will spit out the new Program ID, so you can either end up with this error below or go straight to step 3:
  * Try to hit your program and get the `Incorrect program ID` error
* Update the program ID in `declare_id` and `Anchor.toml`
* `anchor build` again

**Comment by acheroncrypto** [comment]
I agree Anchor should handle this internally. In the meantime, people can use [watchso](https://github.com/acheroncrypto/watchso), a hot-reloading tool, that also updates the program id in the case of mismatch between the declared one and the created public key in `target/deploy` folder.

**Comment by ilovehackathons** [comment]
> I agree Anchor should handle this internally. In the meantime, people can use [watchso](https://github.com/acheroncrypto/watchso), a hot-reloading tool, that also updates the program id in the case of mismatch between the declared one and the created public key in `target/deploy` folder.

My tool, [create-solana-starter](https://github.com/ilovehackathons/create-solana-starter), also handles this, but only covers Anchor so far. I'll take a look at yours and see if it makes sense to integrate it.

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2509.

Programs start with the correct program id and there is a new command `anchor keys sync` that has been added in https://github.com/coral-xyz/anchor/pull/2505 to sync on demand.
