### ISSUE TITLE
Ability to deploy IDL to local validator

### ISSUE THREAD

**Issue by realbuffalojoe** [coral-xyz/anchor#2456]
Devs want to be able to deploy an IDL to a local validator, so they can do IDL-based testing - especially for client-side and web-based code - from their local development suite

**Comment by realbuffalojoe** [comment]
Ooooof how lol

**Comment by acheroncrypto** [comment]
There seems to be a bug with the `anchor-cli` because I'm able to use IDLs in localnet using playground.

![image](https://user-images.githubusercontent.com/98934430/231372962-9ed83403-5ab2-4e90-b01b-729fc32f62ff.png)

**Comment by realbuffalojoe** [comment]
But you are also using the CLI, no?

**Comment by acheroncrypto** [comment]
They are not the same because playground CLIs are rewrites of the original CLIs and I test all of the commands while implementing them so a bug in the original CLI does not necessarily translate into the playground version.

**Comment by callensm** [comment]
this is possible already with the `anchor-cli`.

```sh
// deploy the program
$ anchor deploy --provider.cluster l

// initialize the idl account
$ anchor idl init --provider.cluster l -f ./target/idl/<program>.json <program_id>

// fetch the on-chain idl
$ anchor idl fetch --provider.cluster l -o idl.json <program_id>
```

**Comment by acheroncrypto** [comment]
I've just tried it and it seems to work fine. There is also no cluster specific IDL code so there is no reason why it wouldn't work specifically in localnet.

> My experience was the IDL publish command just hung there, and other devs I spoke with (like 2) said that you couldn't deploy IDLs to localnet

Could you give steps on how to reproduce this problem?

**Comment by realbuffalojoe** [comment]
I'm not able to reproduce it anymore. Strange. I ran into the issue a few times and someone mentioned you can't deploy IDLs to localnet.
I've got Anchor 0.27 CLI and it appears to work as expected. 
Closing
