### ISSUE TITLE
Ability to create Anchor account state structs for your own SDK

### ISSUE THREAD

**Issue by buffalojoec** [coral-xyz/anchor#2458]
Everyone loves Anchor's account state structs - like `Mint` and `TokenAccount` - when building the context for their instruction.

With the introduction of `Metadata` for tokens, this trend continues.

It's not practical for the maintainers of Anchor to continue to increase the collection of state structs that represent state from other protocols - be it SPL, Metaplex, Pyth, etc.

Instead, what if we created a seamless mechanism for creating Anchor account state structs, and allowed developers from any protocol to:
* Import the required traits from Anchor for account state
* Implement these traits within their crate
* Publish their crate to be included alongside `anchor-lang` within any program that wants to use these structs?

Another nice addition is the onus shifts from the Anchor maintainer crew to that of the state struct imported for a developer's particular program.

Here's a simple example:
`Cargo.toml`:
```toml
[dependencies]
anchor-lang = "0.27.0"
pyth-anchor-state = "0.0.1"
```

`lib.rs`:
```rust
use anchor_lang::prelude::*;
use pyth_anchor_state::PythAccount;

#[derive(Accounts)]
pub struct Example<'info> {
   pyth_account: Account<'info, PythAccount>,
}

...
```

**Comment by callensm** [comment]
what is stopping developers from doing this currently in their sdks? the `AccountSerialize` and `AccountDeserialize` traits required for this are exports from the `anchor_lang` crate and available for external implementation already.

**Comment by Aursen** [comment]
@callensm is right, I already do it in my contracts. And everything is relatively simple. I think there are already examples in the Anchor tests. If not, I can add some more

**Comment by realbuffalojoe** [comment]
You mean you create a lib with Anchor-compatible structs and just import them into your contracts?

I guess it's as simple as just adding `#[account]` or `AnchorDeserialize`, `AnchorSerialize` ?

If that's the case we should just encourage people to publish type/trait crates compatible with Anchor. Might be really cool to see protocols do this.

**Comment by Aursen** [comment]
You need to implement both trait manually but yeah you can create a lib normally. If not I will try to find the issue in the proc macro dérive Account (maybe we can have an issue here)

**Comment by callensm** [comment]
> You mean you create a lib with Anchor-compatible structs and just import them into your contracts?
> 
> I guess it's as simple as just adding `#[account]` or `AnchorDeserialize`, `AnchorSerialize` ?
> 
> If that's the case we should just encourage people to publish type/trait crates compatible with Anchor. Might be really cool to see protocols do this.

yeah pretty much. as long as the structs implement `AccountSerialize + AccountDeserialize + Clone` over the `'info` lifetime (if necessary), whether thats manual implementations or via the `account` proc-macro, they can be imported and used from any crate.

if this wasn't the case, if you would super difficult to use sibling program crates within a single anchor workspace that rely on each other.

this [lockup test suite](https://github.com/coral-xyz/anchor/tree/master/tests/lockup/) is a good example of the topic being discussed.
