### ISSUE TITLE
anchor build fails

### ISSUE THREAD

**Issue by effeaucarre** [coral-xyz/anchor#2465]
I can't manage to build my program, here is the error :

```
ubuntu@ip-172-31-44-11:~/cct-staking$ anchor build
BPF SDK: /home/ubuntu/.local/share/solana/install/releases/1.9.29/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
   Compiling atty v0.2.14
error[E0425]: cannot find function `is` in this scope
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/atty-0.2.14/src/lib.rs:98:6
   |
98 |     !is(stream)
   |      ^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `atty` due to previous error
```

Here is my cargo.toml : 

```
[lib]
crate-type = ["cdylib", "lib"]
name = "..."

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "^0.26.0"
anchor-spl = {version = "0.26.0"}
spl-token = {version = "3.1.1", features = ["no-entrypoint"]}
mpl-token-metadata = { version="1.9.0", features = [ "no-entrypoint" ] }
mpl-token-auth-rules = { version = "1.2.0", features = ["no-entrypoint"] }
```

Anyone knows how to fix this ?

**Comment by effeaucarre** [comment]
what is really weird is that if i run anchor build many times in a row, i have a different error: 

`ubuntu@ip-172-31-44-11:~/cct-staking$ anchor build
BPF SDK: /home/ubuntu/.local/share/solana/install/releases/1.9.29/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
   Compiling termcolor v1.1.3
error[E0107]: this struct takes 0 lifetime arguments but 1 lifetime argument was supplied
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/termcolor-1.1.3/src/lib.rs:375:20
    |
375 |     StdoutLock(io::StdoutLock<'a>),
    |                    ^^^^^^^^^^---- help: remove these generics
    |                    |
    |                    expected 0 lifetime arguments

error[E0107]: this struct takes 0 lifetime arguments but 1 lifetime argument was supplied
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/termcolor-1.1.3/src/lib.rs:376:20
    |
376 |     StderrLock(io::StderrLock<'a>),
    |                    ^^^^^^^^^^---- help: remove these generics
    |                    |
    |                    expected 0 lifetime arguments

For more information about this error, try `rustc --explain E0107`.
error: could not compile `termcolor` due to 2 previous errors
`

Sometimes it s atty, sometime it's termcolor...

**Comment by acheroncrypto** [comment]
From logs, I see that you're using Solana `1.9.29` which is very old. You should install a newer version from either https://docs.solana.com/cli/install-solana-cli-tools or by running `solana-install update`. Note that the latest version of Anchor(`0.27.0`) is using Solana `1.14.16`.

You can ask development related questions in [Solana Stackexchange](https://solana.stackexchange.com/) or [Anchor Discord](https://discord.gg/NHHGSXAnXk).

**Comment by effeaucarre** [comment]
thank you that solved my problem !
