### ISSUE TITLE
No such command: `+bpf` Error

### ISSUE THREAD

**Issue by Doughp** [coral-xyz/anchor#2472]
When running `anchor build` from a workspace created with `anchor init` I am getting this error in return:
```
 C:\path\to\directory>anchor build
 
info: uninstalling toolchain 'bpf'
info: toolchain 'bpf' uninstalled
error: no such command: `+bpf`

        Cargo does not handle `+toolchain` directives.
        Did you mean to invoke `cargo` through `rustup` instead?
```

AVM & Anchor version:
```
0.27.0
```
Cargo version:
```
cargo 1.69.0
```
Solana version:
```
solana-cli 1.15.2
```
Rustup version:
```
rustup 1.26.0
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.69.0 =`
```
Rustc version:
```
  rustc 1.69.0
```

I am on Windows 11, installed everything through Windows, not WSL. The program code can compile with `cargo build`, just getting this error with `anchor build`

**Comment by Aursen** [comment]
Currently Anchor does not support Windows

**Comment by Doughp** [comment]
> Currently Anchor does not support Windows

Then why would they allow it to be installed via windows? I understand you may not work for Anchor I am not questioning your help haha I am genuinely curious, all my other anchor commands work fine, just not build?
