### ISSUE TITLE
cant overide anchor version

### ISSUE THREAD

**Issue by x3meuriel** [coral-xyz/anchor#2475]
I tried to install the anchor to my computer but it keeps outputting this error

 Ignored package `anchor-cli v0.27.0 (https://github.com/coral-xyz/anchor?tag=v0.27.0#3b451447)` is already installed, use --force to override
Error: The system cannot find the file specified. (os error 2)

**Comment by Aursen** [comment]
Can you specify the OS pls ?

**Comment by x3meuriel** [comment]
this is the full error report

C:\Users\steve>avm install 0.27.0
    Updating git repository `https://github.com/coral-xyz/anchor`
warning: skipping duplicate package `swap` found at `C:\Users\steve\.cargo\git\checkouts\anchor-50c4b9c8b5e0501f\3b45144\tests\swap\programs\swap`
warning: skipping duplicate package `shared` found at `C:\Users\steve\.cargo\git\checkouts\anchor-50c4b9c8b5e0501f\3b45144\tests\typescript\programs\shared`
warning: skipping duplicate package `shared` found at `C:\Users\steve\.cargo\git\checkouts\anchor-50c4b9c8b5e0501f\3b45144\tests\zero-copy\programs\shared`
     Ignored package `anchor-cli v0.27.0 (https://github.com/coral-xyz/anchor?tag=v0.27.0#3b451447)` is already installed, use --force to override
Error: The system cannot find the file specified. (os error 2)
