### ISSUE TITLE
 Stack offset of 6344 exceeded max offset 

### ISSUE THREAD

**Issue by x3meuriel** [coral-xyz/anchor#2476]
I'm currently trying run anchor build on my local machine but i keep getting the error Stack offset and cant find file in the directory /home/xordwhite/.local/share/solana/install/releases/1.15.2/solana-release/bin/sdk/sbf/dependencies/bpf-tools/llvm/bin/llvm-readelf

I'm using the latest solana cli 1.15, latest anchor too and running on WSL

the error output is below

Error: Function _ZN14solana_program4vote5state9VoteState11deserialize17h0175041311a1ccfcE Stack offset of 6344 exceeded max offset of 4096 by 2248 bytes, please minimize large stack variables
Error: Function _ZN229_$LT$solana_program..vote..state..vote_state_0_23_5.._..$LT$impl$u20$serde..de..Deserialize$u20$for$u20$solana_program..vote..state..vote_state_0_23_5..VoteState0_23_5$GT$..deserialize..__Visitor$u20$as$u20$serde..de..Visitor$GT$9visit_seq17h6c63f4a352d9ddaeE Stack offset of 5752 exceeded max offset of 4096 by 1656 bytes, please minimize large stack variables
    Finished release [optimized] target(s) in 0.19s
[2023-04-28T02:37:30.778233521Z ERROR cargo_build_sbf] Failed to execute /home/xordwhite/.local/share/solana/install/releases/1.15.2/solana-release/bin/sdk/sbf/dependencies/bpf-tools/llvm/bin/llvm-readelf: No such file or directory (os error 2)

**Comment by sultandilaram** [comment]
This is an error from solana_program (Vote) itself, you can ignore this since it won't affect your program.

**Comment by acheroncrypto** [comment]
For the stack offset see https://github.com/solana-labs/solana/issues/30188.

> [2023-04-28T02:37:30.778233521Z ERROR cargo_build_sbf] Failed to execute /home/xordwhite/.local/share/solana/install/releases/1.15.2/solana-release/bin/sdk/sbf/dependencies/bpf-tools/llvm/bin/llvm-readelf: No such file or directory (os error 2)

This is not related to the stack error, and is usually solved by removing the cache with
```sh
rm -rf ~/.cache/solana
```

and building again.
