### ISSUE TITLE
anchor-spl 0.27.0 crate depends on spl-token-2022 0.5.0

### ISSUE THREAD

**Issue by aperire** [coral-xyz/anchor#2502]
anchor-spl v0.27.0 has been updated to use spl-token-2022 v0.6.1 as dependency. However, the crate still depends on spl-token v0.5.0. A simple trick of using 
`anchor-spl = { git = "https://github.com/coral-xyz/anchor" }` in `Cargo.toml` fixes the issue for now, but this should be fixed.

**Comment by 0xksure** [comment]
@aperire This only works when doing `cargo build-bpf` however the error persists when doing `cargo build` for crates using `anchor-spl`. Are there any quick fixes for this?

**Comment by 0xksure** [comment]
> @aperire This only works when doing `cargo build-bpf` however the error persists when doing `cargo build` for crates using `anchor-spl`. Are there any quick fixes for this?

Scratch that. It works now 👍

**Comment by acheroncrypto** [comment]
This is fixed in [`0.28.0`](https://github.com/coral-xyz/anchor/pull/2527).
