### ISSUE TITLE
could not update anchor cli version 0.27.0 due to compiling enum-iterator-1.4.0 error

### ISSUE THREAD

**Issue by KKQanT** [coral-xyz/anchor#2507]
Compiling tracing v0.1.37
error[E0658]: use of unstable library feature 'array_from_fn'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.4.0/src/lib.rs:586:18
    |
586 |             Some(core::array::from_fn(|_| unreachable!()))
    |                  ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0658]: use of unstable library feature 'array_from_fn'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.4.0/src/lib.rs:589:18
    |
589 |             Some(core::array::from_fn(|_| x.clone()))
    |                  ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0658]: use of unstable library feature 'array_from_fn'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.4.0/src/lib.rs:595:18
    |
595 |             Some(core::array::from_fn(|_| unreachable!()))
    |                  ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0658]: use of unstable library feature 'array_from_fn'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.4.0/src/lib.rs:598:18
    |
598 |             Some(core::array::from_fn(|_| x.clone()))
    |                  ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0658]: use of unstable library feature 'bool_to_option'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.4.0/src/lib.rs:454:18
    |
454 |         (!*self).then_some(true)
    |                  ^^^^^^^^^
    |
    = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

error[E0658]: use of unstable library feature 'bool_to_option'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.4.0/src/lib.rs:458:17
    |
458 |         (*self).then_some(false)
    |                 ^^^^^^^^^
    |
    = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `enum-iterator` due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `anchor-cli v0.27.0 (https://github.com/coral-xyz/anchor?tag=v0.27.0#3b451447)`, intermediate artifacts can be found at `/tmp/cargo-installtj6n1W`

Caused by:
  build failed
Error: Failed to install 0.27.0, is it a valid version?

![image](https://github.com/coral-xyz/anchor/assets/71139706/2b1b9ce0-65d8-49c8-9266-4a767c7c327e)

**Comment by acheroncrypto** [comment]
This is fixed in [`0.28.0`](https://github.com/coral-xyz/anchor/pull/2527).
