### ISSUE TITLE
Clippy linter complains about Error size.

### ISSUE THREAD

**Issue by D0bhareach** [coral-xyz/anchor#2515]
My functions in  Anchor code had squiggly yellow lines under returned Result. Clippy warns about  Error size.
[Couse of the problem](https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err)  
[dtolnay about errors (rust-lang/depricated)](https://github.com/rust-lang-deprecated/failure/issues/9)   
[Rust forum about large error](https://users.rust-lang.org/t/error-types-as-enums-or-as-structs/9797/3)  
[Rust Forum discussion about wrapping Error in the Box](https://users.rust-lang.org/t/clippy-complains-my-error-type-is-too-big-what-is-the-best-solution/93410)

**Comment by acheroncrypto** [comment]
Thank you, fixed in https://github.com/coral-xyz/anchor/pull/2600.
