### ISSUE TITLE
Init PDA => inner instruction too large

### ISSUE THREAD

**Issue by effeaucarre** [coral-xyz/anchor#2520]
Hello,
i'm stucked at something i've done many many times, and i don't get the problem.
I want to init a PDA, i use the following code :

`#[account(
    init,
    payer = owner,
    seeds = [METADATA_ACCOUNT_PREFIX.as_bytes(), mint.key().as_ref()],
    token::mint = mint,
    token::authority = owner,
    bump,
    )]
  pub real_metadata_account: Box<Account<'info, TokenAccount>>,`

if i comment it, everything works as expected, but as soon as i uncomment it i get the following error: 

Program failed to complete: Instruction passed to inner instruction is too large (12884933556 > 1280)

Like if the program fails to init the account in the inner instruction, but i don't get why there would be that much data.

I used many times init with similar seeds, and never had any problem.
for information, i tried with different mint addresses. 

metadata_account_prefix is just a string of letters.

any idea ?

**Comment by acheroncrypto** [comment]
Could you share a reproducable example in https://github.com/solana-labs/solana/issues/31960 ?

This seems to be an issue with Solana `1.16.0` and if you are looking for a quick solution, downgrading to `1.14.18` solves it.

**Comment by effeaucarre** [comment]
downgraded to 1.14.18 and it works now, thanks

**Comment by saicharanpogul** [comment]
downgraded to 1.14.18 and now i'm getting

```
error: package `winnow v0.4.7` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.62.0-dev
```

**Comment by saicharanpogul** [comment]
> downgraded to 1.14.18 and it works now, thanks

downgraded to 1.14.18 and now i'm getting

```
error: package `winnow v0.4.7` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.62.0-dev
```

**Comment by acheroncrypto** [comment]
> > downgraded to 1.14.18 and it works now, thanks
> 
> downgraded to 1.14.18 and now i'm getting
> 
> ```
> error: package `winnow v0.4.7` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.62.0-dev
> ```

`solana-cli v1.14` uses an older version of rustc, you'd have to use an earlier version of the problematic crates. See https://github.com/coral-xyz/anchor/issues/2511#issuecomment-1575433342.

If you have an easy reproducable example for this error, please share it in https://github.com/solana-labs/solana/issues/31960.

**Comment by acheroncrypto** [comment]
https://github.com/solana-labs/solana/issues/31960#issuecomment-1668682153 explains why this problem happens. 

This should not happen on `0.29.0` because `^1.16` is required for Solana crates.
