### ISSUE TITLE
Anchor init error

### ISSUE THREAD

**Issue by Killpit** [coral-xyz/anchor#2525]
Whenever I try to create anchor program, I get this error and when I try to run yarn, I get error and I can neither build nor test the application.

anchor init metaplex_nft_testing
ERROR: install is not COMMAND nor fully qualified CLASSNAME.
Usage: yarn [OPTIONS] SUBCOMMAND [SUBCOMMAND OPTIONS]
 or    yarn [OPTIONS] CLASSNAME [CLASSNAME OPTIONS]
  where CLASSNAME is a user-provided Java class

  OPTIONS is none or any of:

--buildpaths                       attempt to add class files from build tree
--config dir                       Hadoop config directory
--daemon (start|status|stop)       operate on a daemon
--debug                            turn on shell script debug mode
--help                             usage information
--hostnames list[,of,host,names]   hosts to use in worker mode
--hosts filename                   list of hosts to use in worker mode
--loglevel level                   set the log4j level for this command
--workers                          turn on worker mode

  SUBCOMMAND is one of:

    Admin Commands:

daemonlog            get/set the log level for each daemon
node                 prints node report(s)
rmadmin              admin tools
scmadmin             SharedCacheManager admin tools

    Client Commands:

applicationattempt   prints applicationattempt(s) report
app|application      prints application(s) report/kill application/manage
                     long running application
classpath            prints the class path needed to get the hadoop jar and
                     the required libraries
cluster              prints cluster information
container            prints container(s) report
envvars              display computed Hadoop environment variables
fs2cs                converts Fair Scheduler configuration to Capacity
                     Scheduler (EXPERIMENTAL)
jar <jar>            run a jar file
logs                 dump container logs
nodeattributes       node attributes cli client
queue                prints queue information
schedulerconf        Updates scheduler configuration
timelinereader       run the timeline reader server
top                  view cluster information
version              print the version

    Daemon Commands:

nodemanager          run a nodemanager on each worker
proxyserver          run the web app proxy server
registrydns          run the registry DNS server
resourcemanager      run the ResourceManager
router               run the Router daemon
sharedcachemanager   run the SharedCacheManager daemon
timelineserver       run the timeline server

SUBCOMMAND may print help when invoked w/o parameters or with -h.
Failed yarn install will attempt to npm install

added 174 packages, and audited 175 packages in 18s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 9.4.0 -> 9.7.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.1
npm notice Run npm install -g npm@9.7.1 to update!
npm notice 
Initialized empty Git repository in /Users/atatekeli/metaplex_nft_testing/.git/
metaplex_nft_testing initialized

I'm looking on how I can create an anchor program without having any issues.

**Comment by Killpit** [comment]
solana-cli: 1.15.0

yarn: yarn version
Hadoop 3.3.4
Source code repository https://github.com/apache/hadoop.git -r a585a73c3e02ac62350c136643a5e7f6095a3dbb
Compiled by stevel on 2022-07-29T12:32Z
Compiled with protoc 3.7.1
From source with checksum fb9dd8918a7b8a5b430d61af858f6ec
This command was run using /opt/homebrew/Cellar/hadoop/3.3.4/libexec/share/hadoop/common/hadoop-common-3.3.4.jar

anchor-cli 0.27.0

**Comment by acheroncrypto** [comment]
> yarn: yarn version Hadoop 3.3.4 Source code repository https://github.com/apache/hadoop.git -r a585a73c3e02ac62350c136643a5e7f6095a3dbb Compiled by stevel on 2022-07-29T12:32Z Compiled with protoc 3.7.1 From source with checksum fb9dd8918a7b8a5b430d61af858f6ec This command was run using /opt/homebrew/Cellar/hadoop/3.3.4/libexec/share/hadoop/common/hadoop-common-3.3.4.jar

What does this have to do with `yarn`? It doesn't seem like you have it installed. You can install it with `npm install -g yarn`.

**Comment by Killpit** [comment]
I don't know, I tried installing Hadoop and while trying to configure, it gor messed up, now trying to download yarn, will let you know the result

**Comment by Killpit** [comment]
I did but I had the same issue

**Comment by Killpit** [comment]
npm install --global yarn

changed 1 package in 477ms
npm notice 
npm notice New minor version of npm available! 9.4.0 -> 9.7.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.1
npm notice Run npm install -g npm@9.7.1 to update!
npm notice 
atatekeli:~ atatekeli$ yarn version
-bash: /opt/homebrew/bin/yarn: No such file or directory

**Comment by Killpit** [comment]
That's what I got when I write yarn version, I used brew install yarn

 yarn version

yarn version v1.22.19
warning package.json: No license field
warning package.json: No license field

And this is what when I write yarn

 yarn
yarn install v1.22.19
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/web3-js/scrypt-shim.git
Directory: /Users/atatekeli
Output:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by Killpit** [comment]
yarn --version 1.22.19

**Comment by Killpit** [comment]
I think there's not much to do about it

atatekeli$ anchor init anchor_retest
yarn install v1.22.19
warning package.json: No license field
warning ../package.json: No license field
info No lockfile found.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 19.21s.
Initialized empty Git repository in /Users/atatekeli/anchor_retest/.git/
anchor_retest initialized
