### ISSUE TITLE
CLI should check sol balance before deploying

### ISSUE THREAD

**Issue by CanardMandarin** [coral-xyz/anchor#2532]
When deploying a program (using `anchor deploy`) with an insufficient sol balance you will have the following error.

```
Error: Deploying program failed: Error processing Instruction 1: custom program error: 0x1
There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.
```
It could be nice to have a better error message.

We could also estimate the necessary balance and prevent users from deploying if their balance are too low.
This could come with a flag `--skip-balance-check`.

**Comment by CanardMandarin** [comment]
Might be relevant as this error message appears a lot on discord.
![image](https://github.com/coral-xyz/anchor/assets/10544393/9c2f82db-b84d-4378-9a34-3b60cbba8241)

**Comment by 0xdeepmehta** [comment]
Yes, it would be great to have this feature. @CanardMandarin, do you want to PR?

**Comment by CanardMandarin** [comment]
> Yes, it would be great to have this feature. @CanardMandarin, do you want to PR?

Absolutely! You can assign me this issue.

**Comment by CanardMandarin** [comment]
Fixed with: https://github.com/solana-labs/solana/pull/32129
