### ISSUE TITLE
Anchor test failing on Debian servers

### ISSUE THREAD

**Issue by tanmaymunjal** [coral-xyz/anchor#2547]
Hey, I am a developer from DefiOS, a web3 org building on-chain incentives for open-source work on Solana!

Update: It seems that the initial build was done on an ubuntu server, while the later build process was shifted to Debian server. It seems to be the case that anchor tests do not work on debian distro.

**Comment by acheroncrypto** [comment]
It's very likely that you are missing some of the build dependencies and there isn't much I can say other than that when you haven't shared any logs.

```
sudo apt update && sudo apt upgrade && sudo apt install -y pkg-config build-essential libudev-dev
```

**Comment by tanmaymunjal** [comment]
Yeah, I did try that but didn't work. Tbh the reason no logs were shared was as there was nothing much to sure

Like the anchor build was working fine, the anchor test did run but showed transaction simulation failed: the program failed to complete every test, something not observed on the same tests in the current Ubuntu build using the same steps.

No logs were generated in the .anchor/program-logs, even disabling preflight led to zero logs and just showed transaction failed on the CLI level, I still have the old build, will try to experiment and see if I can find anything

@acheroncrypto

**Comment by tanmaymunjal** [comment]
Despite further inspection, it is quite not clear to me at the moment what is the issue we are running into. The test systems have now been ported to Ubuntu and are no longer creating issues but tests still seem to fail on the Debian dev server. One weird thing I have noted is that in Debian test runs the program logs directory is empty. While in Ubuntu test runs, even if no tests are run for that program(we utilize different program-level test folders to isolate testing), the program logs directory has a file per program deployed with at least one default streaming logs comment when running anchor test. Could you please check @acheroncrypto if you can find anything

Debian
![Screenshot from 2023-07-01 11-07-01](https://github.com/coral-xyz/anchor/assets/72982935/bcb7a4d6-f765-4549-9851-e2ffc918c208)
Ubuntu
![Screenshot from 2023-07-01 11-08-26](https://github.com/coral-xyz/anchor/assets/72982935/f52751b4-ebbb-41ac-9420-678b9175651f)

**Comment by tanmaymunjal** [comment]
Ok.looking at logs using the Solana logs cli command, it seems that the error that we are receiving is "Invoked by an instruction with data that is too large (12884933860 > 10240)". This seems to be related to a Solana-level issue https://github.com/solana-labs/solana/issues/30271 rather than an Anchor issue. Closing this here

**Comment by acheroncrypto** [comment]
Yes, that's an issue with Solana `1.16` release https://github.com/solana-labs/solana/issues/31960 and downgrading to `1.14.18` should solve the problem.
