### ISSUE TITLE
Anchor tests run successfully but shows error at end 

### ISSUE THREAD

**Issue by tanmaymunjal** [coral-xyz/anchor#2562]
Anchor tests run successfully but show an error at the end, Error: No such file or directory (os error 2).

Not 100% sure but might be related to this https://solana.stackexchange.com/questions/1648/error-no-such-file-or-directory-os-error-2-error-from-anchor-test, I am building the contracts in separate VMs using the -p command and running them in separate test suite using anchor test --run  and --skip-build flag.  This might be causing the idl to not be generated for the other programs in that VM and might be the cause of the error.

Again this is a guess, will need to see the code.

**Comment by acheroncrypto** [comment]
> Not 100% sure but might be related to this https://solana.stackexchange.com/questions/1648/error-no-such-file-or-directory-os-error-2-error-from-anchor-test

Yes, if you use `--skip-build` flag but the workspace has not been built before, then you'll get this error.

**Comment by acheroncrypto** [comment]
Most of the compiling time is taken by the initial compilation of the crates, and most of those crates will be shared between programs so any subsequent compilation will only take a fraction of the time it took after the first one. You can see the workflow of [Anchor tests](https://github.com/coral-xyz/anchor/tree/master/tests) where each test folder is a separate Anchor workspace and [CI tests](https://github.com/coral-xyz/anchor/blob/6ef6b79a6ca5d88b0a1e1d85bd6fbd546191695a/.github/workflows/reusable-tests.yaml#L372) are per workspace, not per program.

> does it make sense to remove this error if the un-built contract is not even being mentioned

Reading all tests to decide whether a specific program is being used or not is not very practical. It would be much easier to solve this problem by either catching this error in your CI tests, or creating a filler IDL file for each program that's not built.

**Comment by tanmaymunjal** [comment]
Yeah makes sense, tried it out today and the speed difference does not really seem to matter, cloding this here
