### ISSUE TITLE
Add easy functions for token transfers

### ISSUE THREAD

**Issue by metaproph3t** [coral-xyz/anchor#2586]
When you want to do a token transfer today within Anchor, it looks something like this (sorry for leading spaces):

```rust
		token::transfer(
			CpiContext::new(
				accs.token_program.to_account_info(),
				Transfer {
					from: accs.user_underlying_token_account.to_account_info(),
					to: accs.vault_underlying_token_account.to_account_info(),
					authority: accs.authority.to_account_info(),
				},
			),
			amount,
		)?;
```

This is pretty verbose and requires 3 levels of nesting. Not ideal, especially when you compare it with Solidity's `ERC20.transferFrom(from, to, amount)`

It would be nice to replace the function with something like this:

```rust
		token::transfer(
			&accs.token_program,
			&accs.user_underlying_token_account,
			&accs.vault_underlying_token_account,
			amount,
			&accs.authority,
		)?;
```

**Comment by devansh-m12** [comment]
i think creating a funtion might work you can try following code:

`
pub fn transfer(
    token_program: &AccountInfo,
    user_underlying_token_account: &AccountInfo,
    vault_underlying_token_account: &AccountInfo,
    amount: u64,
    authority: &AccountInfo,
) -> ProgramResult {
    let cpi_ctx = CpiContext::new(
        token_program.clone(),
        Transfer {
            from: user_underlying_token_account.clone(),
            to: vault_underlying_token_account.clone(),
            authority: authority.clone(),
        },
    );
    token::transfer(cpi_ctx, amount)
}
`

**Comment by devansh-m12** [comment]
I think creating a function might work you can try following code :

```
pub fn transfer(
    token_program: &AccountInfo,
    user_underlying_token_account: &AccountInfo,
    vault_underlying_token_account: &AccountInfo,
    amount: u64,
    authority: &AccountInfo,
) -> ProgramResult {
    let cpi_ctx = CpiContext::new(
        token_program.clone(),
        Transfer {
            from: user_underlying_token_account.clone(),
            to: vault_underlying_token_account.clone(),
            authority: authority.clone(),
        },
    );
    token::transfer(cpi_ctx, amount)
}
```

**Comment by metaproph3t** [comment]
Yeah, this is what I've been doing: [example](https://github.com/openbook-dex/openbook-v2/blob/master/programs/openbook-v2/src/token_utils.rs). It would just be nice if we could include this in anchor-spl so I don't need to copypasta into each new repo

**Comment by devansh-m12** [comment]
If you haven't already, you can make a new pull request for that, and I'm sure they'll integrate it eventually.

**Comment by acheroncrypto** [comment]
Closing for now: https://github.com/coral-xyz/anchor/pull/2596#issuecomment-1674538118
