### ISSUE TITLE
`anchor-cli` isn't released on crates.io as a binary for version 0.28.0

### ISSUE THREAD

**Issue by cereum** [coral-xyz/anchor#2593]
It's important for those who consume anchor via CI to be able to download the binaries to quickly run validation/unit tests. By neglecting the latest version/not having a release pipeline it forces developers to write disgusting caching logic (ask me how I know 🙃 ) to keep anchor up to date with the latest features. 

Publishes shouldn't be on the maintainers. They should be quasi-automated through GHA

**Comment by acheroncrypto** [comment]
[`anchor-cli 0.29.0`](https://crates.io/crates/anchor-cli/0.29.0) is published on crates.io but it's not the recommended installation method for binaries as mentioned in the previous comment.
