### ISSUE TITLE
vue + vite = broken sha256 for anchor discriminator ?

### ISSUE THREAD

**Issue by effeaucarre** [coral-xyz/anchor#2619]
I have a weird use case : 
when i call my program instruction in a vue + vite app, i get the error 101, wrong discriminator (fallback function error).

So i tried a very simple code : 

`console.log(sha256.digest('global:bid'));  `

And this does not give me the same result in my app and in a node app (the one in the node app seems to be the right one because transaction are OK with this one).

So it seems something is breaking sha256 (so, anchor too).

i have a 
`var global = global || window; `
might be linked ?

**Comment by acheroncrypto** [comment]
Yes, there is an issue with newer versions of Chrome and `js-sha256` package(https://github.com/emn178/js-sha256/issues/40) which cause `Error: Invalid account discriminator`. We've updated to a new package in https://github.com/coral-xyz/anchor/pull/2580 which shouldn't have this problem.

Upgrade to latest version https://www.npmjs.com/package/@coral-xyz/anchor/v/0.28.1-beta.2 to fix this problem. I'm closing this but feel free to reopen if the issue persists after upgrading.

**Comment by effeaucarre** [comment]
it seems to work, thanks

btw, what is the difference between coral-xyz/anchor and project-serum/anchor ?

**Comment by acheroncrypto** [comment]
> btw, what is the difference between coral-xyz/anchor and project-serum/anchor ?

Latter is deprecated, [@coral-xyz/anchor](https://www.npmjs.com/package/@coral-xyz/anchor) is the package that is up to date.

**Comment by baindlapranayraj** [comment]
Hey I am trying to write some test case for my simple tweet account creation everything is fine creating PDA, but my test case throws an error Error: AnchorError occurred. Error Code: InstructionFallbackNotFound. Error Number: 101. Error Message: Fallback functions are not supported.  A small help could be apriciated
