### ISSUE TITLE
Anchor v0.28.0 image missing from Docker hub

### ISSUE THREAD

**Issue by tomjohn1028** [coral-xyz/anchor#2639]
[Latest tag is v0.27.0](https://hub.docker.com/r/projectserum/build/tags), so `anchor build --verifiable` fails when using CLI 0.28.0

**Comment by acheroncrypto** [comment]
There is a new image at https://hub.docker.com/r/backpackapp/build.

You can also install the latest CLI with:

```
cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
```

Closing because it's duplicate of https://github.com/coral-xyz/anchor/issues/2560 and will be fixed on the next version.
