### ISSUE TITLE
Method does not support views

### ISSUE THREAD

**Issue by ahpb21** [coral-xyz/anchor#2648]
const returnData = await program.methods
  .calculate(someVariable)
  .accounts({
    acc: somePubkey,
    anotherAcc: someOtherPubkey,
  })
  .view()  // Method does not support views

**Comment by acheroncrypto** [comment]
`view` method is only supported if `calculate` instruction returns a value.

**Comment by acheroncrypto** [comment]
Closing because there isn't enough information to reproduce and good chance this error is by design.
