### ISSUE TITLE
Anchor.toml is unable to parse `*` while mentioning workspace members

### ISSUE THREAD

**Issue by dhruvja** [coral-xyz/anchor#2658]
I was trying to add workspace members to anchor.toml file since the smart contracts were in a different directory than the default `programs` directory. And i observed that when i mentioned the folder path in the workspace members with a `*`, the `anchor.toml ` similar to what we have in cargo.toml, it was not able to understand it.

For eg:
```
[workspace]
members = [
  "solana/my-programs/*"
]
```
The above didnt work. 
But it works fine when the exact directory is mentioned like below.

```
[workspace]
members = [
  "solana/my-programs/example-program"
]
```
Is there a particular reason why we dont allow all the `*` to include all the directories in a particular folder ?

If there isnt, I am happy to open a PR for the above fix.

**Comment by acheroncrypto** [comment]
> Is there a particular reason why we dont allow all the `*` to include all the directories in a particular folder ?

Nothing particular other than globs not being supported by default.

> If there isnt, I am happy to open a PR for the above fix

Sounds great!

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2785
