### ISSUE TITLE
Make `anchor init` and `anchor new` aliases of each other

### ISSUE THREAD

**Issue by jim4067** [coral-xyz/anchor#2668]
The intention of both of the commands is to initialize a new anchor workspace. I think we should make them aliases of each other as `init` has more options compared to `new` yet they should be doing the same thing.

**Comment by acheroncrypto** [comment]
> The intention of both of the commands is to initialize a new anchor workspace

That's not correct, they are different commands and don't do the same thing.

`anchor init` initializes a new workspace meanwhile `anchor new` adds a new program to the existing workspace. `anchor new` won't work outside of an Anchor workspace.
