### ISSUE TITLE
ProgramData upgrade_authority_address not being set

### ISSUE THREAD

**Issue by joefitter** [coral-xyz/anchor#2675]
Using anchor 0.29.0

When validating the `upgrade_authority_address` from ProgramData, the PublicKey is `Some(11111111111111111111111111111111)`

```rust
#[derive(Accounts)]
pub struct InitTxFeeConfig<'info> {
    #[account(
        init,
        space = TxFeeConfig::LEN,
        payer = authority,
        seeds = [b"tx-fee-config"],
        bump
    )]
    pub tx_fee_config: Account<'info, TxFeeConfig>,

    #[account(
        constraint = program.programdata_address()? == Some(program_data.key())
    )]
    pub program: Program<'info, StakooorProgram>,

    #[account(
        constraint = program_data.upgrade_authority_address == Some(authority.key()) // <---- upgrade_authority_address not set here
    )]
    pub program_data: Account<'info, ProgramData>,

    #[account(mut)]
    pub authority: Signer<'info>,

    pub system_program: Program<'info, System>,
}
```

I notice in the release notes the section regarding upgradeable tests - however the upgrade auth is missing with or without this flag being added to anchor.toml

This issue can be reproduced by cloning https://github.com/Unboxed-Software/solana-admin-instructions/ and updating anchor to 0.29.0

**Comment by acheroncrypto** [comment]
> Using anchor 0.29.0
> ...
> This issue can be reproduced by cloning https://github.com/Unboxed-Software/solana-admin-instructions/ and updating anchor to 0.29.0

This feature is not dependent on program crate versions used and only works if on `anchor-cli 0.29.0`. Can you confirm you are on `anchor-cli 0.29.0`?

**Comment by joefitter** [comment]
I am now, and it works perfectly. Thank you :)
