### ISSUE TITLE
error when, running `cargo install --git https://github.com/coral-xyz/anchor --tag v0.29.0 anchor-cli --locked`

### ISSUE THREAD

**Issue by atnrkl** [coral-xyz/anchor#2714]
error: failed to select a version for the requirement `clap = "^4.2.4"`
candidate versions found which didn't match: 3.2.25, 3.2.24, 3.2.23, ...
location searched: crates.io index
required by package `avm v0.29.0

system: Ubuntu 22.04 LTS x86_64

**Comment by acheroncrypto** [comment]
This could happen when `cargo` is unable to update the registry for whatever reason, try removing `~/.cargo/cache` and `~/.cargo/registry` to force update.

**Comment by atnrkl** [comment]
Thanks, it worked

**Comment by atnrkl** [comment]
Thanks, it worked
