### ISSUE TITLE
Compiling anchor-spl v0.29.0 error

### ISSUE THREAD

**Issue by tpkeeper** [coral-xyz/anchor#2715]
anchor build failed

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.20"

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = { version = "0.29.0", default-features = false, features = [
    "stake",
    "mint",
    "spl-token",
    "token",
] }

```
Compiling anchor-spl v0.29.0
error[E0599]: no variant or associated item named `deserialize` found for enum `StakeState` in the current scope
   --> src/stake.rs:139:21
    |
139 |         StakeState::deserialize(buf).map(Self).map_err(Into::into)
    |                     ^^^^^^^^^^^ variant or associated item not found in `StakeState`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following traits are implemented but not in scope; perhaps add a `use` for one of them:
    |
1   | use anchor_lang::AnchorDeserialize;
    |
1   | use bincode::config::Options;
    |
1   | use borsh::BorshDeserialize;
    |
1   | use serde::de::Deserialize;
    |
      and 2 other candidates
```

**Comment by acheroncrypto** [comment]
I'm not able to reproduce the issue with same versions, did you run `cargo update`?

**Comment by tpkeeper** [comment]
For (anchor cli /anchor-lang/anchor-spl), I used 0.29 at the beginning. I kept getting this error and could not compile it no matter what. When I switched to 0.28, the compilation was normal. When I switched back to 0.29, the compilation was normal again. Yeah. This is really weird
