### ISSUE TITLE
Show installation progress when `solana_version` is not installed in CLI

### ISSUE THREAD

**Issue by acheroncrypto** [coral-xyz/anchor#2724]
### Problem

During `solana_version` toolchain override, we set the standard I/O stream to [`Stdio::null`](https://doc.rust-lang.org/std/process/struct.Stdio.html#method.null) in order to avoid displaying the switching process via `solana-install init` command. The process can take a while if the given Solana version is not installed but there is no indication of a new installation.

### Solution

Anchor should only set the standard I/O stream to `Stdio:null` if the given `solana_version` is already installed. That way, users will be able to see the installation process when necessary.

**Comment by simplysabir** [comment]
Hey @acheroncrypto , can i work on this issue? i kind of understood the problem and have implementation in mind and have written that too.

**Comment by simplysabir** [comment]
@acheroncrypto hey raised the PR, kindly have a look!!

https://github.com/coral-xyz/anchor/pull/2757

**Comment by simplysabir** [comment]
#2757

**Comment by acheroncrypto** [comment]
Resolved in https://github.com/coral-xyz/anchor/pull/2757
