### ISSUE TITLE
Anchor deploy not working on mainnet

### ISSUE THREAD

**Issue by jasmeenPedalsup** [coral-xyz/anchor#2735]
while running `anchor deploy` on mainnet I am getting below error

```
Deploying cluster: https://api.mainnet-beta.solana.com/
Upgrade authority: /Users/myuser/.config/solana/id.json
Deploying program "santacoin_claim"...
Program path: /Users/myuser/work/santacoin/code/contract-claim/target/deploy/contract_claim.so...
thread 'main' panicked at cli/src/program.rs:2188:26:
Should return a valid tpu client: RpcError(Error { request: Some(GetClusterNodes), kind: Reqwest(reqwest::Error { kind: Body, source: TimedOut }) })
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
There was a problem deploying: Output { status: ExitStatus(unix_wait_status(25856)), stdout: "", stderr: "" }.
```

rent and gas fee both are deduct from account but contact not deployed. if I tried to re-deploy then it again ask for rent fee.

**Comment by acheroncrypto** [comment]
What's your Solana CLI version?

**Comment by acheroncrypto** [comment]
> rent and gas fee both are deduct from account but contact not deployed. if I tried to re-deploy then it again ask for rent fee.

You can claim the lamports by closing the unused buffer accounts with `solana program close --buffers`.

This should be fixed if you use the same Solana CLI version as the cluster you're trying to deploy to.
