### ISSUE TITLE
Anchor Deploy ELF Error: Invalid String 

### ISSUE THREAD

**Issue by solanacryptodev** [coral-xyz/anchor#2736]
So I'm working on a new program and got it to build. I want to deploy to devnet, so I set my Solana config to api.devnet.solana.com. I generated a vanity keypair for the program and passed that private key array to the keypair.json file that generates when you run anchor build. But then I run **anchor deploy --provider.cluster devnet** I get this error...

**ELF error: ELF error: Failed to parse ELF file: invalid string**

I'm not sure what string it's referring to that's invalid. Someone suggested it might be related to my Cargo.toml file.

```[package]
name = "word"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sayword"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = "0.29.0"
random_word = { version = "0.4.1", features = ["en"] }
solana-program = "1.17.9"
```

This is also the beginning of my lib.rs file...

```
use anchor_lang::prelude::*;
use crate::state::state::Increment;

pub mod instructions;
pub mod state;
mod errors;

pub use instructions::*;
pub use state::*;

declare_id!("3iQ3v19x7zQUgqV3amCMmuci8UjGejQp1fpEXBaP8pAB");

#[program]
pub mod word {
    use super::*;

    /// Creates the Game Account
    pub fn initialize_create_game(
        ctx: Context<CreateGame>, name: String, min_deposit: u8) -> Result<()> {
        handle_create_game(ctx, name, min_deposit)?;
        Ok(())
    }
```

I ran into this issue when trying to run anchor test too, but I was somehow able to resolve it, but I kept running into testing errors that I can't pin down the origin of. Not sure if it's the program, the way the test is written, or something else. So I was just going to deploy it and test it on devnet via the IDL.

**Comment by acheroncrypto** [comment]
This is because you're using `random_word` crate which depends on `rand` crate. Programs execution must be deterministic so crates like `rand` is not allowed to be used inside Solana programs(not Anchor specific).

Please see [on-chain program restrictions](https://docs.solana.com/developing/on-chain-programs/developing-rust#restrictions).
