### ISSUE TITLE
Use of cargo make

### ISSUE THREAD

**Issue by Aursen** [coral-xyz/anchor#2737]
Switch to [cargo make](https://github.com/sagiegurari/cargo-make) to handle different cases:

- Release
- Setup test
- Version bump
- Run all tests
- And others

Benefits:

- Cross shell scripting
- One type of command for each repo management need
- Simplified flow

**Comment by acheroncrypto** [comment]
Similar to https://github.com/coral-xyz/anchor/pull/2594#issuecomment-1674302737, there shouldn't be a need to install a seperate tool just to execute a few commands. People already have `bash`, `node` or `make` so I see everything else as a suboptimal choice.

**Comment by Aursen** [comment]
Bash is not Windows compatible.
Node is installed but seems a bit too much for what needs to be done.
And I didn't have make, I didn't need it.

It's just annoying to have multiple CLI tool to handle different cases (not cross shell). But I understand and I will close the issue
