### ISSUE TITLE
idl-build = ["anchor-lang/idl-build"] - cause compilation error

### ISSUE THREAD

**Issue by ohaddahan** [coral-xyz/anchor#2745]
If I'm using `idl-build = ["anchor-lang/idl-build"]` I'm getting compilation errors.
Once removed, compiles fine.

```
error[E0599]: no associated item named `__anchor_private_gen_idl_type` found for struct `anchor_spl::token::TokenAccount` in the current scope
  --> programs/<>/src/instructions/car/<>.rs:15:10
   |
15 | #[derive(Accounts)]
   |          ^^^^^^^^ associated item not found in `TokenAccount`
   |
   = note: this error originates in the derive macro `Accounts` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you are looking for the module in `std`, not the primitive type
   |
15 | #[derive(std::Accounts)]
   |          +++++
```

```toml
[package]
name = "<>"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "matchbox"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.29.0", features = ["spl-associated-token-account", "spl-token", "metadata"] }
arrayref = "0.3.7"
```

```toml
[package]
name = "<>"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "matchbox"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.29.0", features = ["spl-associated-token-account", "spl-token", "metadata"] }
arrayref = "0.3.7"
```

**Comment by acheroncrypto** [comment]
This is happening because all crates that you use types from need to be specified in the `idl-build` feature list:

```
[features]
idl-build = [
    "anchor-lang/idl-build",
    "anchor-spl/idl-build",
]
```

More details in [release notes](https://github.com/coral-xyz/anchor/blob/f6a15254d18609ee09258f781c42b1263994b86c/docs/src/pages/docs/release-notes.md#notes-1).

**Comment by ohaddahan** [comment]
> release notes

Oh, missed that.
The error message was cryptic :)

**Comment by acheroncrypto** [comment]
Yeah, definitely cryptic — we should improve it.

**Comment by bunnyBites** [comment]
> This is happening because all crates that you use types from need to be specified in the `idl-build` feature list:
> 
> ```
> [features]
> idl-build = [
>     "anchor-lang/idl-build",
>     "anchor-spl/idl-build",
> ]
> ```
> 
> More details in [release notes](https://github.com/coral-xyz/anchor/blob/f6a15254d18609ee09258f781c42b1263994b86c/docs/src/pages/docs/release-notes.md#notes-1).

I don't believe I spent a week trying different anchor versions and solana versions to fix this.

**Comment by solguru310** [comment]
Thanks @acheroncrypto .
I solved my error by your comment.
fully recommend you.

**Comment by 0xl3on** [comment]
> This is happening because all crates that you use types from need to be specified in the `idl-build` feature list:
> 
> ```
> [features]
> idl-build = [
>     "anchor-lang/idl-build",
>     "anchor-spl/idl-build",
> ]
> ```
> 
> More details in [release notes](https://github.com/coral-xyz/anchor/blob/f6a15254d18609ee09258f781c42b1263994b86c/docs/src/pages/docs/release-notes.md#notes-1).

thank you!!
