### ISSUE TITLE
ts: IDL PDA seeds are typed as `any`

### ISSUE THREAD

**Issue by acheroncrypto** [coral-xyz/anchor#2750]
### Problem

IDL PDA seeds are typed as `any` in TS package:

https://github.com/coral-xyz/anchor/blob/de9901b5fd739d80d5d881c8892b71083b24c987/ts/packages/anchor/src/idl.ts#L65-L70

### Solution

Add the actual types instead of using `any`.

**Comment by Nishchay1571999** [comment]
Can i take this up?

**Comment by Nishchay1571999** [comment]
hi @acheroncrypto I went through the type.rs file in ./lang/syn/src/idl/type.rs file and came up with this particular. Type

**Comment by Nishchay1571999** [comment]
hi @acheroncrypto I went through the type.rs file in ./lang/syn/src/idl/type.rs file and came up with this particular. Type
export type IdlSeed = {
  ty: IdlType,
  value: any,
  account?:string,
  path?:string
}; 
It sounds kind of right Is there anything I might be missing?

**Comment by acheroncrypto** [comment]
Hey, thanks for your interest in contributing but https://github.com/coral-xyz/anchor/pull/2752 has been created before your initial comment.

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2752
