### ISSUE TITLE
Can not create zero_copy state with u64 and u8?

### ISSUE THREAD

**Issue by huybuidac** [coral-xyz/anchor#2759]
```rust
#[account(zero_copy)]
pub struct TestOk {
    pub key: Pubkey,
    pub supply: u64,
}

#[account(zero_copy)]
pub struct TestFail1 {
    pub key: Pubkey,
    pub supply: u64,
    pub u8_var: u8,
}
```

Got this error when build
```rust
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
    |
939 | pub struct TestFail1 {
    |            ^^^^^^^^^
    |
    = note: source type: `TestFail1` (384 bits)
    = note: target type: `_::{closure#0}::TypeWithoutPadding` (328 bits)
```

And this error on IDE
<img width="679" alt="image" src="https://github.com/coral-xyz/anchor/assets/7322305/edbe5d7f-3fe2-4fe9-ba4e-9f429b6a1043">

**Comment by huybuidac** [comment]
same with u16, u32, bool. Is it feature?

**Comment by acheroncrypto** [comment]
Zero copy accounts need to implement [`bytemuck::Pod`] trait and [safety](https://docs.rs/bytemuck/1.14.0/bytemuck/trait.Pod.html#safety) section specifically mentions:

> The type must not contain any uninit (or padding) bytes, either in the middle or on the end (eg: no `#[repr(C)] struct Foo(u8, u16)`, which has padding in the middle, and also no `#[repr(C)] struct Foo(u16, u8)`, which has padding on the end).

```rs
#[account(zero_copy)]
pub struct TestFail1 {
    pub key: Pubkey,
    pub supply: u64,
    pub u8_var: u8,
}
```

This struct has 56 bits of padding at the end which the error message also states(384-328). There are many ways to solve this, for example:

- Remove `u8_var`
- Change `u8_var` to `u64`
- Add padding at the end `_padding: [u8; 7]`
