### ISSUE TITLE
Error while setting AVM version, even when it is successfully installed 

### ISSUE THREAD

**Issue by shravanandoria** [coral-xyz/anchor#2769]
![image](https://github.com/coral-xyz/anchor/assets/36509067/57ea792d-8978-46a1-9fce-99591688eaf7)

**Comment by shravanandoria** [comment]
@paul-schaaf @armaniferrante @acheroncrypto

**Comment by acheroncrypto** [comment]
Did you run `avm install 0.29.0` like the error suggested?

`avm --version` returns the `avm` version but the error is about `anchor-cli` not being installed.

Also, please don't ping people.
