### ISSUE TITLE
target/idl/tic_tac_toe.json doesn't exist

### ISSUE THREAD

**Issue by qiluge** [coral-xyz/anchor#2775]
⚠️ Don't use issues for support questions ("How does x feature work in Anchor? How to do x in Anchor?"). Use the discord instead https://discord.gg/NHHGSXAnXk (but don't ping maintainers). ⚠️

Cannot run `anchor test`.
<img width="1309" alt="image" src="https://github.com/coral-xyz/anchor/assets/19525062/ab13ecdb-5419-40f2-ae53-e4ec3e7dd890">

**Comment by acheroncrypto** [comment]
Your program is named `tic_toc_toe` instead of `tic_tac_toe`. Change the program module name:

```diff
- mod tic_toc_toe
+ mod tic_tac_toe
```
