### ISSUE TITLE
Anchor build issue

### ISSUE THREAD

**Issue by hammad-ali18** [coral-xyz/anchor#2787]
When I am using anchor build  for my program , it is showing me this error. I have entered the solana binaries to my path variable insidre environment correct. 

error: not a directory: '/home/muhammad/.local/share/solana/install/releases/1.17.17/solana-release/bin/sdk/sbf/dependencies/platform-tools/rust/bin'

**Comment by acheroncrypto** [comment]
Looks like something went wrong during your Solana installation. I'd try removing the current version and re-install with

```
solana-install init 1.17.0
```

**Comment by hammad-ali18** [comment]
yes it worked when I installed the previous version and and updated the PATH on ~/.bashrc

like this
export PATH="$PATH:/home/muhammad/.local/share/solana/install/releases/1.17.0/solana-release/bin/sdk/sbf/dependencies/platform-tools/rust/bin"
