### ISSUE TITLE
How to update the rustc version of anchor project 

### ISSUE THREAD

**Issue by lucaslee129** [coral-xyz/anchor#2809]
Hi, Everyone. I have one issue while using anchor project. 
I am a fresher of Solana project and now I am using the documentations.

Recently, I create the new anchor project using `anchor init nftminting `and run the `anchor build` command.

But this error is occured:
`error: package `solana-program v1.18.1` cannot be built because it requires rustc 1.72.0 or newer, while the currently active rustc version is 1.68.0-dev
Either upgrade to rustc 1.72.0 or newer, or use
cargo update -p solana-program@1.18.1 --precise ver
where `ver` is the latest version of `solana-program` supporting rustc 1.68.0-dev`

So I checked the my rustc version.
When I run the command `rustc --version`, the result is `rustc 1.75.0 (82e1608df 2023-12-21)`.
Now I am using `anchor-cli 0.29.0`.

So this means now I am using rustc 1.75.0. 
What is the reason and How to fix it? Hope your kind answers. Thanks for your kind time

**Comment by acheroncrypto** [comment]
Please see https://github.com/solana-labs/solana/issues/31428 to understand why the error occurs.

You can update it by running:

```
solana-install init 1.18.0
```

Also, please use [Solana StackExchange](https://solana.stackexchange.com/) for questions.

**Comment by lucaslee129** [comment]
Hi, Thanks for your kind effort. I have a similar issue now, I dont know how to fix that. I cannot get answer from google.
Here is the error message.

`error: package `toml_edit v0.21.1` cannot be built because it requires rustc 1.69 or newer, while the currently active rustc version is 1.68.0-dev
Either upgrade to rustc 1.69 or newer, or use
cargo update -p toml_edit@0.21.1 --precise ver
where `ver` is the latest version of `toml_edit` supporting rustc 1.68.0-dev
`

In the last case, I fixed the issue by `solana-install init 1.18.1`. But in this case, I cannot fix it.
What is the reason and how to fix it? Hope your kind answers.

**Comment by 19-xiaogao** [comment]
I had a similar problem.
