### ISSUE TITLE
[FR] Convert Pubkey to Address

### ISSUE THREAD

**Issue by Morgandri1** [coral-xyz/anchor#2817]
As said in the title; there should be a relatively easy way to derive an Address object from a solana.js Pubkey.

**Comment by acheroncrypto** [comment]
`Address` is not an object, it's a type alias:

https://github.com/coral-xyz/anchor/blob/5d5cadebdd81edb2700ad72e33349c8ffe106569/ts/packages/anchor/src/program/common.ts#L65

Conversion is not necessary since you can use `PublicKey` in any place where Anchor expects `Address`.
