### ISSUE TITLE
Pass remaining accounts in `RequestBuilder` in rust client

### ISSUE THREAD

**Issue by dhruvja** [coral-xyz/anchor#2818]
To pass remaining accounts, we need to define our own struct and implement the traits so that we can pass it to the `RequestBuilder` but having a method to just pass a vector of `AccountMeta` in `RequestBuilder` would be a good idea. Ideally having something similar to what we have in typescript would be the best.

I was thinking maybe we could have a struct smtg like below.
```rs
Accounts<T>(T, Vec<AccountMeta>);
```

with the trait implemented as follows
```rs
impl<T: anchor_lang::ToAccountMetas> anchor_lang::ToAccountMetas
    for Accounts<T>
{
    fn to_account_metas(&self, is_signer: Option<bool>) -> Vec<AccountMeta> {
        let accounts = self.0.to_account_metas(is_signer);
        [accounts, self.1.clone()].concat()
    }
}
```
The above is inspired from what we have here: 

https://github.com/ComposableFi/emulated-light-client/blob/a369bd73a32b77b4021c571836b29a947f81dd9e/solana/solana-ibc/programs/solana-ibc/src/ix_data_account.rs#L75-L100

**Comment by dhruvja** [comment]
> I was going to add a trait implementation for `ToAccountMetas` in order to support this but noticed it was already added in #406.
> 
> You can pass `vec![AccountMeta { ... }` to the `accounts` method.
> 
> It's not easy to discover, I'll add documentation for this.

But i feel, with using just the vector, we cannot use the existing accounts struct with it right? I can live with that for now but having something like above would be a good addition. What do you think?

**Comment by mina86** [comment]
One thing that’s a bit broken about ToAccountsMetas is that there’s no
way not to create temporary vectors.  Consider than you have Accounts
type `Foo` and you want to pass accounts from that and a couple
additional accounts (which end up in remaining_accounts on the smart
contract side).  You’d do something like:

```rust
let req = program
    .request()
    .accounts(Foo { /* ... */ })
    .accounts(vec![bar, baz]);
```

First, `.accounts(Foo { /* ... */})` results in a call to
Foo::to_account_metas which creates a vector.

Second, we have the `vec![bar, baz]` vector passed in call to
accounts.

Third, fourth and fifth, the implementation of Vec::to_accounts_metas
is this:

```rust
        self.iter()
            .flat_map(|item| (*item).to_account_metas(is_signer))
            .collect()
```

which means that for every element of the vector, it calls
T::to_account_infos.  Each of those calls returns a new vector so in
our example we end up with two new one-element vectors one holding
`bar` and the other holding `baz`.  This is then collected into yet
another vector.

Sixth, the `.accounts(vec![bar, baz])` call appends the vector to the
list of accounts it already has which likely results in a new vector
allocation.

That’s quite ridiculous.  A bit of serving grace here is that this is
code run on the client so memory and performance isn’t as critical as
on the chain when doing CPI calls.

(One thing that would improve situation would be `ToAccountMetas`
implementation for `[T]` so at least one of the temporary vectors
could be avoided).

Perhaps the following would be viable to improve things:

```rust
pub trait ToAccountMetas {
    fn to_account_metas(&self, is_signer: Option<bool>) -> Vec<AccountMeta>;
    fn into_account_metas(self, is_signer: Option<bool>, metas: &mut Vec<AccountMeta>) {
        metas.append(&mut self.to_account_metas(is_signer));
    }
```

**Comment by acheroncrypto** [comment]
> That’s quite ridiculous. A bit of serving grace here is that this is code run on the client so memory and performance isn’t as critical as on the chain when doing CPI calls.

Yeah, that's a quite a few allocations there but as you said it's client code and these few allocations of quite small vecs wouldn't make any noticible difference anyway. You'll be limited by the network before you're limited by the vec allocations so I don't think it's very useful to try to optimize it.
