### ISSUE TITLE
Invalid serialization of type aliased values unless argument name matches type alias name

### ISSUE THREAD

**Issue by halfbakedsneed** [coral-xyz/anchor#2820]
Strange one. Take this simple program, and accompanying invocation:

```rust
// 0.29.0

use anchor_lang::prelude::*;

pub type MyType = [u8; 3];

#[program]
pub mod test {
    use super::*;

    pub fn initialize(ctx: Context<Initialize>, kek: MyType) -> Result<()> {
        msg!("{:?}", kek);

        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
```

```ts
await program.methods.initialize([1, 2, 3]).rpc();
```

## Expected Behaviour

I should see `[1, 2, 3]` in the program logs.

## Current Behaviour

I see `[0, 0, 0]` in the program logs.

If I rename the argument `kek` to `my_type`, then everything works as expected! (hence why the example in the [release notes](https://www.anchor-lang.com/docs/release-notes#type-aliases) works).

## Possible Fix

I believe the culprit lies within the client code parsing the IDL into a layout [here](https://github.com/coral-xyz/anchor/blob/master/ts/packages/anchor/src/coder/borsh/idl.ts#L168).

Unless I'm misunderstanding something, I believe this case should actually be written as follows, no?

```diff
case "alias": {
  return IdlCoder.fieldLayout(
-   { type: typeDef.type.value, name: typeDef.name },
+   { type: typeDef.type.value, name },
    types
  );
}
```

This patch resolves the quirk, but I'm not sure of what other effects it may have.

**Comment by acheroncrypto** [comment]
Yes, that's definitely a bug and your fix is correct — it should use `name` variable similar to the other defined types in `typeDefLayout` method.

I'm currently working on a rather large PR with regards to the IDL and it doesn't have this problem. However, if you'd like to make a PR with this fix, we can merge it.
