### ISSUE TITLE
Error: Invalid arguments: wallet not provided

### ISSUE THREAD

**Issue by alex-borichevsky** [coral-xyz/anchor#2825]
got error with anchor:
Error occurred: Error: Invalid arguments: wallet not provided.
 but i have logged wallet - all is good, here is my configuration:
const keypair = getWallet(".private/secretKey.json");
const meidl = readJsonFile("src/magic-eden/m2idl.json");
const wallet: Wallet = new Wallet(keypair);
const connection = new Web3.Connection(
Web3.clusterApiUrl("mainnet-beta"),
"confirmed",
);

const provider = new AnchorProvider(connection, wallet, {});
const magicEdenProgram = new Program(
  meidl as Idl,
  new PublicKey(MAGIC_EDEN_V2_PROGRAM_ID),
  provider,
);

**Comment by acheroncrypto** [comment]
I don't see the problem in your code but you can let Anchor load the wallet and programs for you by adding this script in `Anchor.toml`. See documentation https://www.anchor-lang.com/docs/manifest.

Please ask questions in [Solana StackExchange](https://solana.stackexchange.com/) instead.
