### ISSUE TITLE
ctx.bumps.get -- no longer compiles

### ISSUE THREAD

**Issue by GildedHonour** [coral-xyz/anchor#2833]
v0.29.0

This used to compile 

    let a = ctx.bumps.get("program_authority").unwrap().to_le_bytes();

It no longer does due to

    this is an associated function, not a method

But this won't compile either:

      let a = MyStruct123::get("program_authority").unwrap().to_le_bytes();

    ^^^ function or associated item not found in `MyStruct123`

How to make it work?

**Comment by acheroncrypto** [comment]
It changed in `0.29.0`, please see https://github.com/coral-xyz/anchor/issues/2678#issuecomment-1777283646.
