### ISSUE TITLE
Unable to deploy, max retries...

### ISSUE THREAD

**Issue by effeaucarre** [coral-xyz/anchor#2836]
I have to deploy a program for mainnet, i have tried 2 different RPC (helius & quicknode)

There are around 600 tx to be sent. It takes several minutes to send the 6xx transactions, and i have the error blockhash expired, does this 5 times, then fails.

What could cause this, since it was working like a charm before ?

i'm using "@project-serum/anchor": "^0.24.2" + solana cli 1.15.2

**Comment by acheroncrypto** [comment]
This problem happens because it's getting more and more difficult to land transactions that don't have priority fees in mainnet. Anchor's current deploy logic is a wrapper around `solana-cli`'s deploy, and because `solana-cli` doesn't yet support setting priority fees, you may get this error.

**Comment by effeaucarre** [comment]
so is there a better way to deploy the program ? because i'm stuck for many days trying to deploy...
or may be priority fees support will be added in solana cli?

**Comment by mikemaccana** [comment]
@effeaucarre yes there's a PR to add priority fees to the Solana CLI. Hold on a sec I'll find it...

**Comment by effeaucarre** [comment]
thanks ! i guess i just ghave to wait then...

**Comment by acheroncrypto** [comment]
Deployment experience is improved in the latest versions of the Solana CLI (after `1.18.12`). You usually need to supply different arguments/options to make it work properly though.
