### ISSUE TITLE
TSdoc generated site needs an upgrade from 0.27 to 0.29

### ISSUE THREAD

**Issue by mikemaccana** [coral-xyz/anchor#2842]
I was looking for docs about `getProvider()` using search on https://www.anchor-lang.com/ earlier - I couldn't find anything (and ended up just reading the source), but https://coral-xyz.github.io/anchor/ts/index.html had appeared via Google. 

I noticed https://coral-xyz.github.io/anchor/ts/index.html is for 0.27 though.

**Comment by acheroncrypto** [comment]
Updated!
