### ISSUE TITLE
Anchor Discord link leads to a server filled with porn invites

### ISSUE THREAD

**Issue by zilayo** [coral-xyz/anchor#2851]
⚠️ Don't use issues for support questions ("How does x feature work in Anchor? How to do x in Anchor?"). Use the discord instead https://discord.gg/NHHGSXAnXk (but don't ping maintainers). ⚠️

As per the title.

The link on the github and in the github issue template (https://discord.gg/NHHGSXAnXk ) leads to a #verify platform filled withy spam porn invites and no apparent way to verify.

Are the github link on these repos outdated?

**Comment by acheroncrypto** [comment]
Hey, those bots are quite common these days unfortunately.

The link is not outdated, I'm not able to see the #verify channel but you just react to an emoji to verify yourself if I remember correctly.

**Comment by zilayo** [comment]
> Hey, those bots are quite common these days unfortunately.
> 
> The link is not outdated, I'm not able to see the #verify channel but you just react to an emoji to verify yourself if I remember correctly.

Perhaps a good idea to review the verification process?

Found that captcha bot let slid into my DMs which let me verify.

Current the process for someone new to the anchor ecocsystem is

1) Find discord link on github.
2) Join server. Immediately met by a channel advertising borderline illegal porn.
3) Once you check your DMs, find a message from captcha.bot to verify
4) Forced to disable VPN to verify with captcha bot.

Lots of other solutions that 1) don't require having an unmoderated channel that users/bots can spam porn invites in + 2) lets you verify without disabling VPNs.
