### ISSUE TITLE
anchor build error

### ISSUE THREAD

**Issue by 19-xiaogao** [coral-xyz/anchor#2853]
anchor build error failed to select a version for the requirement `bs58 = "=0.5.0"`

BPF SDK: /Users/～/saftware/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
    Updating `ustc` index
error: failed to select a version for the requirement `bs58 = "=0.5.0"`
candidate versions found which didn't match: 0.4.0, 0.3.1, 0.3.0, ...
location searched: `ustc` index (which is replacing registry `crates-io`)
required by package `anchor-attribute-account v0.29.0`
    ... which satisfies dependency `anchor-attribute-account = "=0.29.0"` of package `anchor-lang v0.29.0`
    ... which satisfies dependency `anchor-lang = "=0.29.0"` of package `my_anchor_project v0.1.0 (~/my_anchor_project)`
perhaps a crate was updated and forgotten to be re-vendored?

**Comment by acheroncrypto** [comment]
Hey, it looks like your cache is outdated. You can run `cargo update` to re-fetch the crates.io index and update.

**Comment by 19-xiaogao** [comment]
My  anchor version anchor-cli 0.29.0 
rustup 1.27.0 (bbb9276d2 2024-03-08)
solana-cli 1.9.4 (src:8ce65878; feat:3258470607)

**Comment by 19-xiaogao** [comment]
I fixed the bug, brew download solana-cli version is too high. Just use v1.17.27.
