### ISSUE TITLE
node: 1: This: not found

### ISSUE THREAD

**Issue by emaborsa** [coral-xyz/anchor#2854]
As mentioned on [stackoverflow](https://solana.stackexchange.com/questions/11976/node-1-this-not-found), I am trying to [set up the development environment for Solana](https://solana.com/developers/guides/getstarted/setup-local-development) in the Windows WSL.

Everything installed without errors:
- Node v20.11.1
- anchor-cl: 0.29.0
- solana-cli 1.18.6 (src:2afde1b0; feat:3352961542, client:SolanaLabs)
- rustc 1.76.0 (07dca489a 2024-02-04)
- cargo 1.76.0 (c84b36747 2024-01-18)

I wanted to try [this](https://openquest.xyz/quest/solana-my-money) example, but when I run `anchor test` I get the following error:

> /mnt/c/Users/faceb/AppData/Roaming/npm/node_modules/node/bin/node: 1: This: not found

Trying to figure out the problem, I tried to run `anchor init a_random_name` and I get the same error as well. In fact, anchor takes the node folder installed on windows instead the one in the WSL.

Any help?

**Comment by acheroncrypto** [comment]
Do you have `yarn` installed? `anchor test` uses the `test` script in `Anchor.toml`.

**Comment by emaborsa** [comment]
Hi, after trying to renistall everything and not solving the problem, I digged on google and found a comment that as you mentioned, yarn is required and it was not installed.
Installing it solved the problem.
