### ISSUE TITLE
 anchor test --skip-local-validator err

### ISSUE THREAD

**Issue by 19-xiaogao** [coral-xyz/anchor#2861]
I run  ` anchor test --skip-local-validator ` err : 
yarn run v1.22.22
warning package.json: No license field
$ /Users/longjiuwei/html,css,js/rust/anchor-project/node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'

✖ ERROR: Error: Cannot find module '/Users/~/html'

He would then run this command, and I guess it was this command that reported the error
`yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts `

**Comment by acheroncrypto** [comment]
It's likely that this is caused by the directory name `html,css,js`, don't use `,` in your filepaths.

**Comment by 19-xiaogao** [comment]
Thanks.
