### ISSUE TITLE
IDL doesn't exist

### ISSUE THREAD

**Issue by jerac-breederdao** [coral-xyz/anchor#2877]
I tried running `anchor test` and i got the error `Error: IDL doesn't exist` I already ran `cargo clean` then `cargo build` but the error still exist.

**Comment by acheroncrypto** [comment]
You need to run `anchor build` instead of `cargo build` to generate the IDL. Also, `anchor test` builds the programs by default too, so if you still get this error, it might be because of a mismatch between your program name in various places e.g. `Anchor.toml` and `Cargo.toml`.

**Comment by acheroncrypto** [comment]
To add to the previous post, the latest version ([v0.30.0](https://github.com/coral-xyz/anchor/pull/2909)) includes various fixes to the IDL generation workflow, making it very likely that the problem you're having is fixed.
