### ISSUE TITLE
feature: event bytes to enum of events (rust)

### ISSUE THREAD

**Issue by ckamm** [coral-xyz/anchor#2885]
It would be helpful if anchor generated a function like:
```
fn event_from_bytes(bytes: &[u8]) -> Result<Event>;

enum Event {
    Event1(Event1),
    // one for each struct tagged #[event]
}
```
That finds the matching discriminator and then parses the event.

**Comment by acheroncrypto** [comment]
It's a bit difficult to get all events in the current codegen, but this can easily be implemented with the new [`declare-program!`](https://github.com/coral-xyz/anchor/pull/2857) macro. Would that be sufficient, or do you need the function to be generated with the program codegen?

**Comment by Lou-Kamades** [comment]
the new macro is probably sufficient imo
