### ISSUE TITLE
Anchor event listener not recording few transactions

### ISSUE THREAD

**Issue by sunidhii19** [coral-xyz/anchor#2889]
Hi,
I am listening to an event emitted from my program using @coral-xyz/anchor library but it is not recording all the transactions on mainnet. I am using quicknode pro RPC URL for establishing the websocket connection to listen to these events on my program. What could be the reason here? 

![solana-anchor-issue](https://github.com/coral-xyz/anchor/assets/141013843/2ac0ca51-07da-4edb-90da-45c20797716e)

**Comment by acheroncrypto** [comment]
See https://github.com/coral-xyz/anchor/issues/1613 for more info on why this happens.

[`event-cpi`](https://github.com/coral-xyz/anchor/pull/2438) feature fixes this issue but it's not as ergonomic to use e.g. not as easy to subscribe. See usage example [here](https://github.com/coral-xyz/anchor/tree/4de70aabee9081110d282434a235d3388b3b15b1/tests/events).
