### ISSUE TITLE
Account Constraints affect stack size usage

### ISSUE THREAD

**Issue by nabeel99** [coral-xyz/anchor#2915]
I wasnt sure if this is a bug or an intended feature.

Problem:
Faced with large stack variables i tried boxing it but still to no avail, i randomly removed constraints and saw a good % reduction in stack offset size , which made me experiment by adding and removing constraints and seeing there effect, i dont understand why does adding constraints affect stack size ? since even if i comment out the handler function stack size does not get affected so why is it specifically constraints affect stack size ?

**Comment by nabeel99** [comment]
@acheroncrypto  hoping you would have some insight, since it puzzles me as to when i add `    let test: [i32; 1024] = [0; 1024];
` inside the handler function it dsnt cause the stack offset size to increase but constraints do ?

**Comment by acheroncrypto** [comment]
Constraints are essentially macros that expand to more Rust code. Some constraints result in a lot of code (e.g. `init`), which means you can easily go over the limit of the current stack frame if you use many constraints.

> @acheroncrypto hoping you would have some insight, since it puzzles me as to when i add ` let test: [i32; 1024] = [0; 1024];` inside the handler function it dsnt cause the stack offset size to increase but constraints do ?

That's because the Rust compiler strips out any code that's not being used in the resulting binary. Also, sometimes you don't event get stack offset warnings on builds, but you get memory access errors in runtime instead.

**Comment by nabeel99** [comment]
Btw i dont think there is but on the offchance am wrong, does there exist a way to log stack usage to enable easier experimentation, since the solution to my solutions seems manually handrolling some of the stuff anchor codegen is doing in anchor derive accounts.

**Comment by nabeel99** [comment]
@acheroncrypto  i dont remeber where i read this, but i remember armani recommending composite structs i.e seperate it into multiple derive accounts and embed into a final derive accounts , it was quite back not sure if the internal codegen then uses seperate functions to circumvent this issue.

**Comment by nabeel99** [comment]
Closing this in favour  of #2920 , anyone who comes across this issue, if you want to use anchor, one possible  solution is to use composite structs.
