### ISSUE TITLE
Bug: provider.sendAndConfirm() maxSupportedTransactionVersion

### ISSUE THREAD

**Issue by czkz** [coral-xyz/anchor#2921]
Got the following error after calling `provider.sendAndConfirm(VersionedTransaction)`:

> SolanaJSONRPCError: failed to get transaction: Transaction version (0) is not supported by the requesting client. Please try the request again with the following configuration parameter: "maxSupportedTransactionVersion": 0

`sendAndConfirm()` doesn't set `maxSupportedTransactionVersion` in `getTransaction()`:
https://github.com/coral-xyz/anchor/blob/fefa69519fb9b875cac72469b8d5021f8c2d90a5/ts/packages/anchor/src/provider.ts#L177-L179

It should probably be like this:
```typescript
const failedTx = await this.connection.getTransaction(txSig, {
  commitment: "confirmed",
  maxSupportedTransactionVersion: isVersionedTransaction(tx) ? 0 : undefined
});
```

**Comment by acheroncrypto** [comment]
> It should probably be like this:
> 
> ```ts
> const failedTx = await this.connection.getTransaction(txSig, {
>   commitment: "confirmed",
>   maxSupportedTransactionVersion: isVersionedTransaction(tx) ? 0 : undefined
> });
> ```

Yeah, this looks better. Feel free to PR this fix.
