### ISSUE TITLE
Error: failed to get recent blockhash: TypeError: fetch failed

### ISSUE THREAD

**Issue by jim4067** [coral-xyz/anchor#2938]
Getting the error below when running tests. Fails on devnet and localnet and testnet clusters

```bash
Error: failed to get recent blockhash: TypeError: fetch failed
    at Connection.getLatestBlockhash (/home/jimii/Documents/crew/stream-nft/node_modules/@coral-xyz/anchor/node_modules/@solana/web3.js/src/connection.ts:4593:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AnchorProvider.sendAndConfirm (/home/jimii/Documents/crew/stream-nft/node_modules/@coral-xyz/anchor/src/provider.ts:147:9)
    at MethodsBuilder.rpc [as _rpcFn] (/home/jimii/Documents/crew/stream-nft/node_modules/@coral-xyz/anchor/src/program/namespace/rpc.ts:29:16)
      ✔ Admin initializes the protocol sate (969ms)
```

Env setup
```bash
solana-cli 1.17.28 (src:a67767a0; feat:3746964731, client:SolanaLabs)
anchor-cli 0.29.0
```
Upgrading did not help

**Comment by acheroncrypto** [comment]
> Fails on devnet and local testnet clusters

Does it work on localnet? If so, this looks to be an RPC issue and not much we can do about that.

**Comment by jim4067** [comment]
Fails on all clusters, even localnet

**Comment by acheroncrypto** [comment]
How do you reproduce it?

**Comment by jim4067** [comment]
Not sure how to do so. 

I generated a new project and it worked fine.

**Comment by acheroncrypto** [comment]
Closing since it's impossible to debug if it's not reproducable, and it seems to work now.

Feel free to reopen if you can reproduce it.

**Comment by kalloc** [comment]
The same on my side.
```
ANCHOR_PROVIDER_URL=https://api.devnet.solana.com strace -s 10000 -ff -e connect anchor migrate --provider.cluster devnet 2>&1 | grep connect
[pid 2660159] connect(18, {sa_family=AF_INET, sin_port=htons(8899), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 
```
but rpcEndpoint: 'https://api.devnet.solana.com',

**Comment by defigods** [comment]
It doesn't work in one codebase, while works in two others.
I created a new project, copied code to working codebase, but didn't solve all.
It works for localnet and doesn't work for devnet only.
How to solve?
