### ISSUE TITLE
Latest anchor version is incompatible with solana 1.16.x

### ISSUE THREAD

**Issue by ellttBen** [coral-xyz/anchor#2949]
In the latest version, `anchor_lang` is incompatible with `solana-program 1.16.x` due to https://github.com/coral-xyz/anchor/blob/970cd236b60ca5b814abdfae8fa0227ada4d15bf/lang/src/lib.rs#L204. The `ArithmeticOverflow` variant was added in 1.17.x. The dependency should therefore be bumped to `1.17` to avoid these kinds of issues.

**Comment by acheroncrypto** [comment]
Yes, unfortunately I realized this after making the release, but it shouldn't be a big deal since most projects are going to need the `1.18` version anyway due to other dependency compatibility issues.

Thanks for bringing this up, I'll bump it before the next version.
