### ISSUE TITLE
Discord invites don't work

### ISSUE THREAD

**Issue by 0xDAEF0F** [coral-xyz/anchor#2960]
⚠️ Don't use issues for support questions ("How does x feature work in Anchor? How to do x in Anchor?"). Use the discord instead https://discord.gg/NHHGSXAnXk (but don't ping maintainers). ⚠️

1. When I join the discord there is only one channel called `verify` and there is no further actions required so I cant verify.

2. Captcha.bot sends me a direct message with a grayed out button saying: `ONLY verify on https://captcha.bot`

**Comment by acheroncrypto** [comment]
You should receive a message from the captcha bot, but you won't receive it if you disabled receiving messages. You can also type `/verify` in the verification channel.

If you still have problems, share your discord ID and I can verify you.

**Comment by 0xDAEF0F** [comment]
My DM's are not disabled. I get the message from the bot, but the button is greyed out. anyways here is my discord username: `0xdaef0f`
