### ISSUE TITLE
ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by surajitghorai12** [coral-xyz/anchor#2969]
ReferenceError: structuredClone is not defined. Please look into this issue.
![image](https://github.com/coral-xyz/anchor/assets/133847733/01f3c3be-308e-417a-a963-0c9321937e1d)

**Comment by acheroncrypto** [comment]
Your Node version is outdated, minimum Node v17 is required for `structuredClone`.

See compatibility: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility
