### ISSUE TITLE
`declare_program!()` macro not supported for previous version IDLs

### ISSUE THREAD

**Issue by VY5FR2NWJ9** [coral-xyz/anchor#2972]
The macro attempts to parse the `Idl` [type](https://github.com/coral-xyz/anchor/blob/master/idl/src/types.rs#L64) using `serde_json`, but complains about mandatory `discriminator` field for IDLs generated before anchor 0.30

Example IDL that does not work with this macro: https://github.com/drift-labs/protocol-v2/blob/master/sdk/src/idl/drift.json

I wonder if it would be sensible to have the option to make backwards incompatible fields such as `discriminator` Option<>, or if there is a way of migrating old IDL JSON files to the new format (as a client, who does not have access to the project)

**Comment by acheroncrypto** [comment]
> I wonder if it would be sensible to have the option to make backwards incompatible fields such as discriminator Option<>, or if there is a way of migrating old IDL JSON files to the new format (as a client, who does not have access to the project)

Yes, I'll add a utility to convert an old IDL to a new one, and this will be supported by default with `declare_program!`.

**Comment by VY5FR2NWJ9** [comment]
awesome, that sounds great
