### ISSUE TITLE
failed to read package metadata on Windows if the project is on different drive location

### ISSUE THREAD

**Issue by Rizary** [coral-xyz/anchor#2973]
I have set my $HOME variable to be `C:\Users\rizary` and the project location is in `D:\` as you can see in the picture below. The error seems that it's incorrectly detect the location

![image](https://github.com/coral-xyz/anchor/assets/7221768/1e4a5191-b2af-4813-a781-6af02d4ab5cd)

**Comment by acheroncrypto** [comment]
As the logs suggest, this seems to be related to `cargo-build-sbf` (coming from Solana installation) that `anchor build` uses under the hood.

This is also very likely to be a Windows only issue as Windows uses different file path separator. There is not much we can do to fix this on our side, and even if this gets fixed, there are a lot more probles that people run into while using Windows.

The most common solution is to use WSL instead.

**Comment by acheroncrypto** [comment]
Also, I've just realized you use space in your file path `\school of solana\`, that might also be the reason for the error.

**Comment by Rizary** [comment]
Thanks for the answer.. the space is not an issue (i've changed it and the error persist). I'll try to open issue on `cargo-build-sbf`

**Comment by Lu-Derik** [comment]
I  have the same problem even within WSL. Is there any solution?
