### ISSUE TITLE
lang: Allow using `AccountInfo` references in `#[derive(Accounts)]` structs

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#299]
Currently, all structs are cloned fromt he accounts slice and given to the accounts struct.

**Comment by acheroncrypto** [comment]
We now use an internal reference to the underlying `AccountInfo` for all account types except `AccountInfo` type itself since that has to be owned with the current derive macro (https://github.com/coral-xyz/anchor/pull/2656).
