### ISSUE TITLE
`anchor idl init` deploys new idl data account and doesn't show `Anchor Program IDL` at the program address page at the explorers

### ISSUE THREAD

**Issue by ouoabcde** [coral-xyz/anchor#3015]
When I run `anchor idl init`, this deploys new idl data account. I'm new to the solana and anchor, so I have no idea that this is the right result, but anyway it does deploys the idl account.
At `devnet`, I used this command.
```
$ anchor idl init --filepath target/idl/<program_name>.json 5yYKAKV5r62ooXrKZNpxr9Bkk7CTtpyJ8sXD7k2WryUc --provider.cluster devnet
```
And this command generated this new account, `6MiEUjVXFR4dL12vLQXjft8pa4QBZmWiYmNWaKYA7B1N`.
You can find it at the [explorer](https://explorer.solana.com/tx/3nuFZ8Pkm7dLhNBeraNizZbX12fnrkHicKeaVyLv7gVmmBAx6YniyPDJDVQmYSkv3R9cYCT2N76nZuyrP8DDzpoY?cluster=devnet).

I understand that this command is for publishing the anchor idl file to the on-chain, but I can't find the `Anchor Program IDL` tab at any of those accounts (5yYKAKV5r62ooXrKZNpxr9Bkk7CTtpyJ8sXD7k2WryUc: program account, 6MiEUjVXFR4dL12vLQXjft8pa4QBZmWiYmNWaKYA7B1N: idl data account).

What should I do to show the Anchor IDL file at the explorer? Is this command is not for this?

### My version
- anchor-cli 0.30.0
- solana-cli 1.18.14 (src:d8e08244; feat:4215500110, client:SolanaLabs)

**Comment by acheroncrypto** [comment]
Your IDL has been successfully deployed on-chain, but the Solana explorer doesn't yet support the latest IDL spec.

You can verify this by running:

```sh
anchor idl fetch 5yYKAKV5r62ooXrKZNpxr9Bkk7CTtpyJ8sXD7k2WryUc --provider.cluster devnet
```

It might be worth it to create an issue in the [Solana Explorer](https://github.com/solana-labs/explorer) repo to update Anchor as it's using an ancient version of Anchor (`0.23.0`):

https://github.com/solana-labs/explorer/blob/06b186421c6d8eb8383e21d72f55f859a3fd7e0c/package.json#L20

Or comment on https://github.com/solana-labs/explorer/issues/316.

**Comment by ngundotra** [comment]
Btw @acheroncrypto this is now fixed
