### ISSUE TITLE
Add support for mock RPC Client in anchor_client

### ISSUE THREAD

**Issue by cryptopapi997** [coral-xyz/anchor#3050]
Solana client has a a feature that allows you to [generate and use a mock rpc client](https://docs.rs/solana-client/latest/solana_client/rpc_client/struct.RpcClient.html#method.new_mock), which is supremely useful when doing unit tests. Anchor client (as far as I can tell) doesn't support this when using RequestBuilder and instead always uses the passed cluster under the hood:

(https://github.com/coral-xyz/anchor/blob/master/client/src/lib.rs#L641)
(https://github.com/coral-xyz/anchor/blob/master/client/src/lib.rs#L650)
... and more

It would be cool if we could pass in an RPCClient instead of a cluster when creating a client to allow for mocking.

**Comment by acheroncrypto** [comment]
I agree, mocking is useful, and this would be a nice feature to have.
