### ISSUE TITLE
ts: add commitment param to `Program.addEventListener`

### ISSUE THREAD

**Issue by livthomas** [coral-xyz/anchor#3051]
Right now, if you call [Program.addEventListener](https://github.com/coral-xyz/anchor/blob/master/ts/packages/anchor/src/program/index.ts#L374-L383), you only get subscribed to Anchor events at the default commitment level set in the `Connection` instance. And if you want to receive events at multiple commitment levels, you need to create a separate connection for each.

It looks like [Connection.onLogs](https://github.com/solana-labs/solana-web3.js/blob/master/packages/library-legacy/src/connection.ts#L6443) method provides a third optional `commitment` parameter so it is actually possible to subscribe to the same event at multiple commitment levels using a single connection.

It would be nice if `Program.addEventListener` method also took an optional `commitment` parameter so we could use a single Solana connection across the whole app. Right now, we are basically forced to create multiple connection instances just because Anchor doesn't support this.

**Comment by acheroncrypto** [comment]
> It would be nice if `Program.addEventListener` method also took an optional `commitment` parameter so we could use a single Solana connection across the whole app.

Sounds great! Feel free to create a PR for this, or let me know if you'd like me to add it.

**Comment by livthomas** [comment]
I have implemented it in https://github.com/coral-xyz/anchor/pull/3052

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/3052

**Comment by livthomas** [comment]
@acheroncrypto Is there any chance a new version with this fix could get released anytime soon?

**Comment by acheroncrypto** [comment]
We have some breaking changes, so this will be included in v0.31 which is likely going to get released next month.
