### ISSUE TITLE
`anchor build` fails at `spl-token-2022` compilation

### ISSUE THREAD

**Issue by ouoabcde** [coral-xyz/anchor#3071]
`anchor build` fails at `spl-token-2022` compilation. Here's the error log.
```
error: could not compile `spl-token-2022` (lib) due to 41 previous errors
```

And here is the full error log.
[anchor_build_error.log](https://github.com/user-attachments/files/16108587/anchor_build_error.log)

I'm trying to use token extension at my project, so this build error needs to be fixed.

**My Versions**
- anchor-cli 0.30.1
- solana-cli 1.18.15 (src:767d24e5; feat:4215500110, client:SolanaLabs)

At my anchor project's Cargo.toml,
- anchor-lang = "0.30.1"
- anchor-spl = "0.30.1"

**Comment by acheroncrypto** [comment]
Please see https://github.com/coral-xyz/anchor/issues/3044 and the solution mentioned in https://github.com/coral-xyz/anchor/issues/3044#issuecomment-2184026104. This should be fixed if SPL just makes a patch release with the correct version requirement for Solana crates, but unfortunately, that's taking quite a long time.

**Comment by ouoabcde** [comment]
@acheroncrypto Sorry I'm new to solana and anchor development. I have a question about your comment. Like you've suggested the solution at 3044, to solve my case, what command should I use?
I've got the error at `spl-token-2022`, so I've tried the command like below, because I'm using `solana-cli 1.18.15` and at my case, the error occurred on `spl-token-2022@3.0.2`.
```
cargo update -p spl-token-2022@3.0.2 --precise 1.18.15
```
But it fails like this.
```
    Updating crates.io index
error: no matching package named `spl-token-2022` found
location searched: registry `crates-io`
required by package `anchor-spl v0.30.1`
    ... which satisfies dependency `anchor-spl = "^0.30.1"` (locked to 0.30.1) of package `<My Project>`
```
I think I'm lost. haha..

**Comment by acheroncrypto** [comment]
> ```
> cargo update -p spl-token-2022@3.0.2 --precise 1.18.15
> ```

The command mentioned in https://github.com/coral-xyz/anchor/issues/3044#issuecomment-2184026104 uses `solana-zk-token-sdk` because downgrading that crate also downgrades other Solana crates, which solves the problem. You're trying to downgrade `spl-token-2022`, and that won't work.

**Comment by ouoabcde** [comment]
@acheroncrypto I was using `solana-program-test = "2.0.1"` and `solana-sdk = "2.0.1"` at my project's Cargo.toml's dev-dependencies. So first of all, I downgraded these packages' version to "1.18.15". This work updated the Cargo.lock file's related dependencies to 1.18.17.
Then I ran the command you suggested at the 3044 comment, I ran this command.
```
$ cargo update solana-zk-token-sdk --precise 1.18.17
$ anchor build
```
But the result is same though. Could you help me what am I missing?

**Comment by ouoabcde** [comment]
Figured it out. The sequence was important.
1. install anchor-spl
2. cargo update solana-zk-token-sdk --precise 1.18.17
3. install other packages

If you try to update solana-zk-token-sdk at the last, then build will fail.
