### ISSUE TITLE
InitSpace does not support tuple structs

### ISSUE THREAD

**Issue by cryptopapi997** [coral-xyz/anchor#3082]
If we try to derive `InitSpace` on a tuple struct, it will fail with the error `Please use named fields in account structure`. This is annoying, but the fact that [the code](https://github.com/coral-xyz/anchor/blob/master/lang/derive/space/src/lib.rs#L59) seems to intentionally reject this case makes me wonder if there's a reason behind intentionally not supporting this?

Is there one or would you be open to a PR fixing this @acheroncrypto?

**Comment by acheroncrypto** [comment]
> This is annoying, but the fact that [the code](https://github.com/coral-xyz/anchor/blob/master/lang/derive/space/src/lib.rs#L59) seems to intentionally reject this case makes me wonder if there's a reason behind intentionally not supporting this?

It was intentional because Anchor did not support tuple structs during that time. It was added in v0.30 (https://github.com/coral-xyz/anchor/pull/2824).

> Is there one or would you be open to a PR fixing this @acheroncrypto?

I don't see any reason to not support this, go ahead.

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/3084
