### ISSUE TITLE
Feature Request: Make Resolvable Accounts accept Optional Accounts

### ISSUE THREAD

**Issue by jacobcreech** [coral-xyz/anchor#3110]
While using `accounts()` has updated to automatically derive PDA accounts and put them as the correct args, this has caused a decent amount of confusion amongst developers who are used to deriving PDAs and inputting them. 

`partialAccounts()` solves for this by allowing people to continue to self derive, but why not make this default in `accounts()` to avoid confusion?

**Comment by acheroncrypto** [comment]
Because it usually allows you to remove half the code compared to the old way, which makes both reading and using libraries much easier down the line.

I also have plans to completely get rid of `PublicKey.findProgramAddress` methods, which will complement this change. It is not only unnecessary, but it also looks very archaic.

**Comment by jacobcreech** [comment]
> Because it usually allows you to remove half the code compared to the old way, which makes both reading and using libraries much easier down the line.

I completely agree that it helps a ton with code removal, but it does make it harder to work with older codebases when upgrading anchor. This could possibly be not needed DX-wise if the accounts were obvious or gave a helpful error as mentioned in https://github.com/coral-xyz/anchor/issues/3111

**Comment by acheroncrypto** [comment]
Generally speaking, I do think new projects should be prioritized over older codebases when adding new features. `accountsPartial` was essentially added to make the migration of older codebases easier, as all they have to do is to replace all `.accounts(` with `.accountsPartial(`.

**Comment by jacobcreech** [comment]
>  I do think new projects should be prioritized over older codebases when adding new features.

Oh I completely agree. It just has been painful trying to figure out what accounts were needed and not providing too many accounts, which is why I suggested this change. If we can fix #3111, we likely can just ignore this problem.
