### ISSUE TITLE
TypeScript: provider.wallet.payer property doesn't exist on Anchor 0.30.1

### ISSUE THREAD

**Issue by mikemaccana** [coral-xyz/anchor#3122]
It seems that people are continuously working around `Property 'payer' does not exist on type 'Wallet'` with `// ts-ignore`, `// @ts-expect-error`, or type coersion with `as anchor.Wallet`. In Anchor 0.30.1 these are still needed.

Would it be possible to make `provider.wallet.payer` exist out of the box?

Code to reproduce:

```typescript
import * as anchor from "@coral-xyz/anchor";
import { assert } from "chai";

describe("some anchor app", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  
  // Working around this issue:
  // const user = (provider.wallet as anchor.Wallet).payer;
  const user = provider.wallet.payer;

  it(`has a working wallet`, async () => {
    const balance = await provider.connection.getBalance(user.publicKey);
    console.log("Balance: ", balance);
    assert.ok(balance > 0, "Balance should be greater than 0");
  });
});
```

**Comment by acheroncrypto** [comment]
> Would it be possible to make `provider.wallet.payer` exist out of the box?

It would be possible, but only as an optional field since it only exists in tests.
