### ISSUE TITLE
avm install latest #avm #cli

### ISSUE THREAD

**Issue by jonathanwork** [coral-xyz/anchor#3131]
time-0.3.29

error[E0282]: type annotations needed for `Box<_>`

   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `anchor-cli v0.30.0 (https://github.com/coral-xyz/anchor?tag=v0.30.0#852fcc77)`, intermediate artifacts can be found at `/tmp/cargo-installEa5d5m`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Error: Failed to install 0.30.0, is it a valid version?

**Comment by acheroncrypto** [comment]
Please see the answer in https://github.com/coral-xyz/anchor/issues/3126#issuecomment-2254245326

**Comment by krusher55** [comment]
@jonathanwork after racking my head i found a way to get it working


after running cargo install --git https://github.com/coral-xyz/anchor avm --locked --force,  
go to ../time-0.3.29/src/format_description/parse/mod.rs file (get the path from compilation error) 

and in line 83, update 

`let items = format_items`

to 

`let items: Box<[format_item::Item]> = format_items`


save the file and run

`avm install latest`

followed by

`avm use latest`


and check with

`anchor --version`


if it shows anchor version, we gucci

anchor-cli 0.30.1


hope this helps

**Comment by RasHQ-programmation** [comment]
IM GUCCI

**Comment by mcfriend99** [comment]
Can a PR be raised with this fix??

**Comment by Ex4m** [comment]
None of the fixes were working for me except this one. Thank you sir, very well done

**Comment by paudeldipesh** [comment]
It works. Thank you, buddy.

**Comment by rishabhjamwal** [comment]
It works! 
Thanks

**Comment by harpreettrader** [comment]
thanks it's working fine for me

**Comment by rolandeke** [comment]
> @jonathanwork after racking my head i found a way to get it working
> 
> after running cargo install --git https://github.com/coral-xyz/anchor avm --locked --force, go to ../time-0.3.29/src/format_description/parse/mod.rs file (get the path from compilation error)
> 
> and in line 83, update
> 
> `let items = format_items`
> 
> to
> 
> `let items: Box<[format_item::Item]> = format_items`
> 
> save the file and run
> 
> `avm install latest`
> 
> followed by
> 
> `avm use latest`
> 
> and check with
> 
> `anchor --version`
> 
> if it shows anchor version, we gucci
> 
> anchor-cli 0.30.1
> 
> hope this helps

I tried doing this but then got another error 
```
error: the `-Z unstable-options` flag must also be passed to enable the flag `check-cfg`

error: could not compile `dashmap` (lib)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `anchor-cli v0.30.1 (https://github.com/coral-xyz/anchor?tag=v0.30.1#e6d7dafe)`, intermediate artifacts can be found at `/tmp/cargo-installPlwick`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Error: Failed to install 0.30.1, is it a valid version?
```

any help with this?

**Comment by imsamad** [comment]
go to file with the path as given in terminal
this might look like
- ../time-0.3.29/src/format_description/parse/mod.rs file (get the path from compilation error)
-  /home/${USER}/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.29/src/format_description/parse/mod.rs:83:9

replace method **_parse_owned_** with following

```

pub fn parse_owned<const VERSION: usize>(
    s: &str,
) -> Result<crate::format_description::OwnedFormatItem, crate::error::InvalidFormatDescription> {
    validate_version!(VERSION);
    let mut lexed = lexer::lex::<VERSION>(s.as_bytes());
    let ast = ast::parse::<_, VERSION>(&mut lexed);
    let format_items = format_item::parse(ast);

    let items: Vec<crate::format_description::OwnedFormatItem> = format_items
        .map(|res| res.map(Into::into))
        .collect::<Result<_, _>>()?;

    // If there's only one item, return it directly
    if items.len() == 1 {
        Ok(items.into_iter().next().unwrap())
    } else {
        // If there are multiple items, create a compound item
        Ok(crate::format_description::OwnedFormatItem::Compound(items.into_boxed_slice()))
    }
}
```

**Comment by rishipatel9** [comment]
Thanks.

**Comment by Daniel235-web** [comment]
Boss level @jonathanwork , thank you
