### ISSUE TITLE
Spl-Associated-Token-Account: Create (Program Error: "IncorrectProgramId")

### ISSUE THREAD

**Issue by glowly29** [coral-xyz/anchor#3138]
I don't know why have this error:

![image](https://github.com/user-attachments/assets/e5562657-456e-4b27-8462-fb70b246fab4)

The transaction: https://solscan.io/tx/62x6buvyNm5br2DMZNAaseqhkAENogvh7jWvgUpiZfxMTyUHjWWTgeeZ9CgnGHYrp6b7Fz3E3VCRGEvRgVV31y4?cluster=devnet

Can someone explain this to me? Thanks!

**Comment by acheroncrypto** [comment]
It probably expects Token 2022 instead.

Use [Solana StackExchange](https://solana.stackexchange.com) for your questions.

**Comment by glowly29** [comment]
Thanks
