### ISSUE TITLE
Error: Method does not support views

### ISSUE THREAD

**Issue by htiennv** [coral-xyz/anchor#3142]
`Anchor`: `0.29.0`

I have a called with code:

```ts

it("Can get buy price!", async () => {
  let buyTokenAmount = 1_000_000;

  let price = await program.methods
    .getBuyPrice(new BN(buyTokenAmount))
    .view();

  console.log("price: ", price);
});

```

But it got error:

<img width="1092" alt="Screenshot 2024-08-02 at 17 12 03" src="https://github.com/user-attachments/assets/baa3b1e7-b7eb-46da-95eb-9d2d57a22a2e">

**Comment by htiennv** [comment]
@acheroncrypto please help! Thanks

**Comment by acheroncrypto** [comment]
`view` method requires the accounts to be immutable, but `crazyState` is marked mutable.

**Comment by htiennv** [comment]
Thanks @acheroncrypto
