### ISSUE TITLE
AccountsResolver cannot pull accounts with a specified confirmation level

### ISSUE THREAD

**Issue by JohnnnyWang** [coral-xyz/anchor#3146]
### What happened
We found that when calling method with a loop. If the seed generated by pda depends on a certain value, but this value will be changed in the previous loop. If the "root" ConfirmOptions level is used, it can be executed correctly. If it is the "confirmed" level, an error will occur (the value generated by pda is wrong, resulting in repeated init accounts)

Here is code, typescript client side
```ts
 for (let param of params) {
      await this.program.methods
        .initializeX(param)
        .accounts({
          ...,
        })
        .signers([])
        .rpc({
          skipPreflight: false,
          commitment: 'root',  // written like this, everything is ok
          preflightCommitment: 'root', // written like this, everything is ok
          maxRetries: 0,
          minContextSlot: undefined,
        });

    }
```

```ts
 for (let param of params) {
      await this.program.methods
        .initializeX(param)
        .accounts({
          ...,
        })
        .signers([])
        .rpc({
          skipPreflight: false,
          commitment: 'confirmed',  // but this, an error will occur
          preflightCommitment: 'confirmed', // but this, an error will occur
          maxRetries: 0,
          minContextSlot: undefined,
        });

    }
```

smart contract code
```rs
#[derive(Accounts)]
pub struct InitializeX<'info> {
    #[account(
        init,
        seeds = [b"x", state.x_seq.to_le_bytes().as_ref()], // During initialization, we will use state.x_seq as the seed
        space = X::SIZE,
        bump,
    )]
    pub x: AccountLoader<'info, X>,

    #[account(
        mut,
        seeds = [b"state".as_ref()],
        bump,
    )]
    pub state: Account<'info, State>,
    ...
}

pub fn handle_initialize_x(
    ctx: Context<InitializeX>,
) -> Result<()> {
    safe_increment!(state.x_seq, 1); // But after initialization, we will increment state.x_seq by 1
    Ok(())
}
```

I briefly read the relevant implementation of the anchor ts source code. I suspect that the public async fetchAccount<T = any> method in AccountsResolver does not carry the confirmation level when calling

```ts
// async fetchAccount<T = any>
const accountInfo = await this._provider.connection.getAccountInfo(
publicKey
);

```
Am I right? Is there any way to solve this problem?
Thanks

**Comment by acheroncrypto** [comment]
> I briefly read the relevant implementation of the anchor ts source code. I suspect that the public async fetchAccount<T = any> method in AccountsResolver does not carry the confirmation level when calling
> 
> ```ts
> // async fetchAccount<T = any>
> const accountInfo = await this._provider.connection.getAccountInfo(
> publicKey
> );
> ```

The `Connection` object you pass to the `AnchorProvider` has a configured commitment level which is used by the call you linked.

> Is there any way to solve this problem?

The best way to solve this problem is to confirm the transaction *before* the next iteration, since the next iteration depends on the previous iteration.

**Comment by JohnnnyWang** [comment]
Wow, thank you, I forgot that the connection can also (need to) set the confirmation level
