### ISSUE TITLE
Discriminator is not implemented for anchor_spl: :token_interface::Mint  and anchor_spl::token_interface::TokenAccount

### ISSUE THREAD

**Issue by cxp-13** [coral-xyz/anchor#3151]
I'm following a tutorial https://www.soldev.app/course/token-extensions-on-chain, github: https://github.com/Unboxed-Software/token22-staking

My dependency situation is 
```
[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "2.0.4"
spl-token = "6.0.0"
spl-token-2022 = "3.0.4"
```

When I try to use the token_interface module in anchor_spl, after executing `anchor build` I get the trait `Discriminator` is not implemented for `anchor_spl: :token_interface::Mint ` and `anchor_spl::token_interface::TokenAccount`.

Detailed code at https://github.com/Unboxed-Software/token22-staking/issues/2

**Comment by acheroncrypto** [comment]
Please see answer https://github.com/coral-xyz/anchor/issues/2745#issuecomment-1868379225.

There is also going to be a warning for this in the next version (https://github.com/coral-xyz/anchor/pull/3133).

**Comment by solguru310** [comment]
Thanks for your help.
@acheroncrypto
