### ISSUE TITLE
anchor build and anchor deploy Fail Despite Successful Installation of Anchor via Cargo

### ISSUE THREAD

**Issue by SandeepMahto17** [coral-xyz/anchor#3164]
Description:
I encountered issues when running anchor build and anchor deploy commands even after
successfully installing Anchor using Cargo with the following command:
```cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli --force```
I also tried to install Anchor using avm install latest, which failed with an error related to the
Box<> type from the times package.
A few months ago, I successfully installed Anchor using avm install latest on another laptop,
and everything worked properly without any issues.
Steps to Reproduce:
1. Install Anchor using Cargo:
```cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli --force```
2. Run ```anchor build ```and ```anchor deploy```.
3. Observe the errors.
Expected Behavior:
The anchor build and anchor deploy commands should execute successfully without any
errors after a successful installation of Anchor.
Environment:
• Anchor Version: 0.30.1

• Installation Method: Cargo, GitHub (via ```cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli --force```)

• Operating System: WSL Ubuntu 22.04.4

![Screenshot 2024-08-11 002243](https://github.com/user-attachments/assets/b38f6c57-462b-47bb-9765-8e54fd041989)

![Screenshot 2024-08-11 002303](https://github.com/user-attachments/assets/e1ad73be-e41e-43b5-88ef-1421f7f2a643)

**Comment by acheroncrypto** [comment]
> `anchor` 0.28.0 is not installed with `avm`. Installing...

This means you have set [`toolchain.anchor_version`](https://www.anchor-lang.com/docs/manifest#toolchain) to `0.28.0`, which overrides your `anchor deploy` command to use that version, and the installation fails due to  https://github.com/coral-xyz/anchor/issues/3126. See "Note" section of https://github.com/coral-xyz/anchor/pull/3143 for more info.

**Comment by SandeepMahto17** [comment]
Thanks, it worked.
