### ISSUE TITLE
`getParsedTransaction` doesn't work at localnet

### ISSUE THREAD

**Issue by ouoabcde** [coral-xyz/anchor#3174]
`getParsedTransaction` doesn't work at localnet. It returns `null`. It should return `confirmed` or `finalized` transaction result.

**My Versions**
- anchor-cli 0.30.1
- solana-cli 1.18.15 (src:767d24e5; feat:4215500110, client:SolanaLabs)

**Comment by acheroncrypto** [comment]
You need to confirm the transaction with at least `confirmed` commitment level before you can fetch it. Also, this is not an Anchor issue.
