### ISSUE TITLE
Can't use this command:  ``` cargo build-bpf ```

### ISSUE THREAD

**Issue by CryptoNinja0331** [coral-xyz/anchor#3180]
Hello, seniors.
I am a fresher for developing solana program.
I am trying to use this command "cargo build-bpf" to build my own solana program. but I met this error message. 
![image](https://github.com/user-attachments/assets/f5e20de7-fc5b-4c47-8c3f-39e667885bd9)
Please help me. Thanks.

**Comment by acheroncrypto** [comment]
That command is deprecated, use `cargo-build-sbf` instead. Not sure if it works properly on Windows though.

It's recommended you use `anchor build` when using Anchor. Also, please use [Solana StackExchange](https://solana.stackexchange.com/) or [the Anchor Discord](https://discord.gg/NHHGSXAnXk) for development questions instead.
