### ISSUE TITLE
Error creating Idl account

### ISSUE THREAD

**Issue by priynshuchouhn** [coral-xyz/anchor#3212]
![image](https://github.com/user-attachments/assets/0e532b9f-871b-4e4f-b4fe-16d70a35d022)

**Comment by acheroncrypto** [comment]
Make sure you're using the correct program id:

https://github.com/coral-xyz/anchor/blob/5c67b046251df69e58677a9842e1c7a6f1373944/lang/src/error.rs#L262-L263
