### ISSUE TITLE
broken link in intro-to-solana.md

### ISSUE THREAD

**Issue by 0xlws** [coral-xyz/anchor#3215]
In `intro-to-solana.md`, there is a clickable link labeled "SolDev" that points to https://soldev.app. However, when clicked, it redirects to https://www.ironforge.cloud instead of the expected destination.

reference:
https://github.com/coral-xyz/anchor/blob/1e3c15e7c955266f9bee9d8a4d9519fec838110d/docs/src/pages/docs/intro-to-solana.md?plain=1#L201

**Comment by acheroncrypto** [comment]
The creator is the same, so I guess SolDev is no longer available. Ironforge is great, but it doesn't belong in the resources section, so it's probably best to remove it.

**Comment by 0xlws** [comment]
hey btw, i just created a pull req to remove it, but maybe its better to put https://beta.solpg.io instead?
