### ISSUE TITLE
An error occurred when updating program id using anchor keys sync

### ISSUE THREAD

**Issue by caesear** [coral-xyz/anchor#3222]
First, I modify the configuration of the anchor.toml file and then run the run build command. This is normal.
![image](https://github.com/user-attachments/assets/5d8e29a4-1def-48ae-9b8c-96bc6cef1c5f)

Now I want to change a program id. I first deleted my program key file target/deploy/kinobi_test-keypair.json. Then run the anchor keys list command to generate a new program key. Then run the anchor keys sync command. The result is that the anchor.toml I modified before is overwritten, causing me to lose my original configuration information, and the anchor build will fail at this time.
![image](https://github.com/user-attachments/assets/20a6e215-3f1f-464d-a02f-5f7becab166a)

**Comment by caesear** [comment]
anchor version is 0.29.0.
rust version is 1.80.1 (3f5fd8dd4 2024-08-06). 
cargo version is 1.80.1 (376290515 2024-07-16)

**Comment by acheroncrypto** [comment]
It seems like serialization of the custom `provider.cluster` input isn't compatible with its deserialization. You can easily get around this by using one of the supported cluster strings (like `Localnet`).

**Comment by caesear** [comment]
![image](https://github.com/user-attachments/assets/c8c6fb99-dc73-42f3-bb3f-63df72b5b179)
Unlike what you said, I simply wrote a test above, but it's useless if you change it to effective development. Focus on removing my commented code. Join I want to switch the cluster to my own paid rpc and mainnet rpc. When I use one of these, the other annotations disappear. I have to add it again. There are two problems

**Comment by nishim3** [comment]
I am facing the same issue. Everytime I run ```anchor keys sync``` the wss url is added to the cluster and that causes an error in building...
