### ISSUE TITLE
Anchor Events not working

### ISSUE THREAD

**Issue by floscar12** [coral-xyz/anchor#3226]
Read some documentation and came across Anchor Events but that [CPI Events](https://book.anchor-lang.com/anchor_in_depth/events.html#cpi-events)

It requires one to opt into it, like so `anchor-lang = { version = "0.29.0", features = ["event-cpi"] }`

I am using Anchor version 0.30.1. My instruction has the required #[event_cpi] above it,  and it is supposed to emit the event "TestEvent"
`emit_cpi!(TestEvent { random: 32332522 });`

On my NodeJs server, I import the idl and set up the Program alongside AnchorProvider, so that I can subscribe to the event like so 

`  const subscriptionId3 = program.addEventListener("TestEvent", (event) => {
    console.log("event");
  });
`

My transactions go through successfully, but I never get the events. I look at the transaction details on Solana Explorer, and I do indeed see that the event_authority was passed as an account for the transaction, and an interaction occured. 

I am using a Helius RPC endpoint for devnet. What could be the issue? Is it because I am using devnet?

**Comment by acheroncrypto** [comment]
This is because `program.addEventListener` doesn't work with CPI events currently. You need to get the transaction and parse the event that way. There is an existing issue https://github.com/coral-xyz/anchor/issues/2609, let's track it there.

**Comment by floscar12** [comment]
> This is because `program.addEventListener` doesn't work with CPI events currently. You need to get the transaction and parse the event that way. There is an existing issue #2609, let's track it there.

Thank you so much!

If I could bother you with one quick question: I am fetching transaction data and iterating through its inner instructions to decode instruction data until I find my event. I am able to decode it using `const event = program.coder.events.decode(eventData);` but I am curious, is there anyway for a malicious actor to forge this by adding their own custom instructions to another account? How can I verify this came from the event authority?

**Comment by acheroncrypto** [comment]
A malicious actor cannot forge this because the event authority needs to sign the transaction for event CPI to work. We have a test for this:

https://github.com/coral-xyz/anchor/blob/51b21cebca7a8672550a9f0349485d920eac8602/tests/events/tests/events.ts#L69-L102
