### ISSUE TITLE
[feature request] `avm use` should auto install the version if not already installed

### ISSUE THREAD

**Issue by nickfrosty** [coral-xyz/anchor#3229]
when new developers are setting up anchor and avm on their machines, avm could help simplify this with the `use` command.

- if a user runs `avm use <version>`, avm could detect if they have the desired version already downloaded and installed locally
- if they do not, ask them if they want to download it now
- if they already have it, continue to function as before

cc @mikemaccana @acheroncrypto

**Comment by acheroncrypto** [comment]
Adding it in https://github.com/coral-xyz/anchor/pull/3230, thanks for the suggestion!
