### ISSUE TITLE
Constants Activated By Conditional Compilation Aren't Included In IDL When Feature Is Activated

### ISSUE THREAD

**Issue by bonedaddy** [coral-xyz/anchor#3231]
# Overview

If you have a constant variable declared like so

```rust
#[cfg(not(feature = "foo"))]
pub const BAR: Pubkey = ...;
#[cfg(feature = "foo")]
pub const BAR: Pubkey = ...;
````

And you build you idl or program activating the `foo` feature, the idl which gets generated does not include the variable `BAR` in it's output.

# Version

Anchor `0.30.1`

**Comment by acheroncrypto** [comment]
Constants need to be marked with [the `#[constant]` attribute](https://docs.rs/anchor-lang/0.30.1/anchor_lang/attr.constant.html) for them to be included in the IDL.

To make this work, you can enable the `foo` feature in `idl-build` feature list:

```toml
[features]
idl-build = ["foo", ...]
```

If you activate the feature using CLI args e.g. `anchor build -- --features foo`, it won't work in `0.30.1`, but it will work in the next release (https://github.com/coral-xyz/anchor/pull/3059).

**Comment by bonedaddy** [comment]
:facepalm: You are right, it seems that I forgot to mark one of the constants that is conditionally activated with the `#[constant]` attribute.

Thanks!
