### ISSUE TITLE
Error When installing Anchor using `avm install latest`

### ISSUE THREAD

**Issue by Prashidha0O1** [coral-xyz/anchor#3239]
error[E0282]: type annotations needed for `Box<_>`
  --> /home/ht0k/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.29/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`

   Compiling solana-security-txt v1.1.1
   Compiling unicode-segmentation v1.10.1
   Compiling heck v0.3.3
   Compiling console v0.15.8
   Compiling solana-vote-program v1.18.17
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `anchor-cli v0.30.1 (https://github.com/coral-xyz/anchor?tag=v0.30.1#e6d7dafe)`, intermediate artifacts can be found at `/tmp/cargo-installswRPCY`.

**Comment by Prashidha0O1** [comment]
@acheroncrypto please, help me out here

**Comment by Serdnad** [comment]
Take a look at https://github.com/coral-xyz/anchor/issues/3236
