### ISSUE TITLE
export 'workspace' (imported as 'anchor') was not found in '@project-serum/anchor' 

### ISSUE THREAD

**Issue by 1752146907** [coral-xyz/anchor#3240]
export 'workspace' (imported as 'anchor') was not found in '@project-serum/anchor' (possible exports: ACCOUNT_DISCRIMINATOR_SIZE, AccountClient, AnchorError, AnchorProvider, BN, BorshAccountsCoder, BorshCoder, BorshEventCoder, BorshInstructionCoder, BorshStateCoder, EventManager, EventParser, IdlError, LangErrorCode, LangErrorMessage, MethodsBuilderFactory, Native, Program, ProgramError, ProgramErrorStack, StateClient, SystemCoder, eventDiscriminator, getProvider, parseIdlErrors, setProvider, splitArgsAndCtx, stateDiscriminator, toInstruction, translateAddress, translateError, utils, validateAccounts, web3)

![image](https://github.com/user-attachments/assets/cae09b23-5f36-4e94-861b-93193040674b)

**Comment by acheroncrypto** [comment]
`workspace` feature is not available in browsers. Also, `@project-serum/anchor` is obsolete — switch to `@coral-xyz/anchor` instead.

**Comment by 1752146907** [comment]
> `workspace`功能在浏览器中不可用。另外，`@project-serum/anchor`已过时 — 请改用`@coral-xyz/anchor`。

The official example is also used in this way, why?
![image](https://github.com/user-attachments/assets/458c0be1-ce3b-424b-8293-bc8fb4085f4b)

**Comment by 1752146907** [comment]
@acheroncrypto
