### ISSUE TITLE
The program expected this account to be already initialized

### ISSUE THREAD

**Issue by htiennv** [coral-xyz/anchor#3253]
Hi teams,

I have a entrypoint called `buy`. And I want pass a token account of user called: `user_discount_token_account` - it's token account of user with a mint named `DISCOUNT`. 

    user_discount_token_account: Box<Account<'info, TokenAccount>>,

The contract will check balance of user then apply discount fees. 
The problem when user not holds token `DISCOUNT` so `user_discount_token_account` not initialized.

Logs:
```
AnchorError caused by account: user_discount_token_account. Error Code: AccountNotInitialized. Error Number: 3012. Error Message: The program expected this account to be already initialized.
```

How I can resolve it? I just want checking balance of token account and no need creating new token account for user

**Comment by acheroncrypto** [comment]
`Account<'info, TokenAccount>` will check whether the account is actually a token account. If the account does not exist (owned by the System Program and has 0 lamports), this check will fail.

You can make it an optional account (`Option<Account<'info, TokenAccount>>`) to achieve what you described.

Note that we don't use GitHub for dev support, please use [Solana StackExchange](https://solana.stackexchange.com/) or [Anchor Discord](https://discord.gg/NHHGSXAnXk) instead.

**Comment by htiennv** [comment]
Thanks
