### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by zale-lee** [coral-xyz/anchor#3254]
I executed `anchor init xxx` and got `Error: No such file or directory (os error 2)`.

**Comment by cxp-13** [comment]
> I executed `anchor init xxx` and got `Error: No such file or directory (os error 2)`.

I have encountered this problem, how did you solve it?

**Comment by zale-lee** [comment]
you can try  reinstall `anchor` and `yarn`
