### ISSUE TITLE
failed: Access violation in unknown section at address 0x0 of size 32

### ISSUE THREAD

**Issue by Lu-Derik** [coral-xyz/anchor#3255]
I have a struct as following:

#[account]
pub struct UserArecState {
    pub num_arec_nft_requested: u32,
    pub num_arec_nft_canceled: u32,
    pub num_arec_nft_issued: u32,
    pub num_arec_nft_redeemed: u32,
    pub num_arec_nft_liquidized: u32,
    pub amount_arec_nft_requested: u64,
    pub amount_arec_nft_cancelled: u64,
    pub amount_arec_nft_issued: u64,
    pub amount_arec_nft_redeemed: u64,
    pub amount_arec_nft_liquidized: u64,
    pub amount_art_offset: u64
}

impl Space for UserArecState {
    const INIT_SPACE: usize = ANCHOR_DISCRIMINATOR + 5 * U32_SIZE + 6 * U64_SIZE;
}

I always received the error in the handing instruction:
  ...
  "Program log: Instruction: MintTo",
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 5414 of 113644 compute units",
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success",
  "Program 7fEvnVYgDkZfT6JkffusC5f2vcRRMdd6dZqAAWURek61 consumed 92788 of 200000 compute units",
  "Program 7fEvnVYgDkZfT6JkffusC5f2vcRRMdd6dZqAAWURek61 failed: Access violation in unknown section at address 0x0 of size 32"
  
  7fEvnVYgDkZfT6JkffusC5f2vcRRMdd6dZqAAWURek61 is the account created to store this struct. This error happens even if I do not update anything to this account.
  
  But once if I remove one or two members from this struct, this error disappear, and everything works well now.

  This is very strange, Is there some limitation here? Or is it a Bug?

**Comment by Lu-Derik** [comment]
As a workaround, I add a reverse member like:
   pub reverse: bool,
It works now. For information, even if I declare "reverse" as u8, the error is still there.

**Comment by acheroncrypto** [comment]
This is very likely to be related to https://github.com/coral-xyz/anchor/issues/3196#issuecomment-2308730518, and it's already fixed in the `master` branch. You might want to try the `git` version to see if the problem still persists. In the meantime, I'm closing this but feel free to reopen if the issue persists in the next version.
