### ISSUE TITLE
I run `anchor --version` with `avm install latest` and got an error `zsh: command not found: anchor`

### ISSUE THREAD

**Issue by zale-lee** [coral-xyz/anchor#3256]
I run `avm install latest` and then `avm use latest` and then add `$HOME/.avm/bin` to PATH and then run `anchor --version` and  got an error `zsh: command not found: anchor`, but I can run `anchor-0.30.1`.

**Comment by acheroncrypto** [comment]
Do you also have `$HOME/.cargo/bin` in your `PATH`?

**Comment by zale-lee** [comment]
Yes, but there is no `anchor` in `$HOME/.cargo/bin`

**Comment by zale-lee** [comment]
`$HOME/.avm/bin` only has `anchor-0.30.1`.
`$HOME/.cargo/bin` has rust and cargo related programs and `avm`

**Comment by acheroncrypto** [comment]
How did you install `avm`? The default installation should come with both `avm` and `anchor` binary in `~/.cargo/bin`.

**Comment by zale-lee** [comment]
I ran `cargo install --git https://github.com/coral-xyz/anchor avm --locked --force` and then ran `avm install latest` to install `anchor`

**Comment by acheroncrypto** [comment]
Weird. That command should also install the `anchor` binary because `avm` has two binaries:

https://github.com/coral-xyz/anchor/blob/c679b2782e55a1c11675fca2aeb692bb0fe7a7ea/avm/Cargo.toml#L6-L12

I've just tried it and it created the `anchor` binary too, so I'd try running it again.

**Comment by zale-lee** [comment]
I reinstalled `avm` to see if this problem still exists
