### ISSUE TITLE
Git Sol - First community Solana token on GitHub.

### ISSUE THREAD

**Issue by GitHubSolana** [coral-xyz/anchor#3270]
The first ever token on launched on the Official Solana GitHub Repo (Coral). All communcation will be made within this thread.

No TG. I will pay dex and give all updates via the comments.

The first comment will contain the CA/PF link.

**Comment by GitHubSolana** [comment]
https://pump.fun/A8iKQ3MdM26pxe84Hc31nHrccbutZr9gcqguktKKpump we are live!

**Comment by gladys1111211** [comment]
CTO?
