### ISSUE TITLE
[cli] key sync does not update the generated IDL type

### ISSUE THREAD

**Issue by nickfrosty** [coral-xyz/anchor#3292]
the `anchor keys sync` command does does not update the generated typescript type file located in the `target/types/program-name.ts`

so in order to sync the key, users must run:
- `anchor keys sync` to update the declare_id value
- then rebuild the program via `anchor build` in order to regenerate the type

## proposed solution

since `anchor keys sync` is already performing a regex replacement for the previous program id, this command should also replace other instances of the program id (including the generated type file)

**Comment by acheroncrypto** [comment]
We can easily implement this, but I don't think it would solve the problem because the user has to rebuild the program to update the program binary regardless, otherwise interacting with the program will fail with the `DeclaredProgramIdMismatch` error.

**Comment by acheroncrypto** [comment]
[`keys sync` command's documentation](https://www.anchor-lang.com/docs/cli#keys-sync) mentions that it only changes the `declare_id!` pubkeys (can also be seen from the help message).

Making changes to the source code naturally requires everything that was generated from that source code to be re-generated, so I think informing the user to rebuild the program should be enough to resolve this issue.

FYI, program ids are synced automatically if `Anchor.toml` doesn't have `localnet` entries during the initial build (https://github.com/coral-xyz/anchor/pull/3023).

**Comment by nickfrosty** [comment]
>Making changes to the source code naturally requires everything that was generated from that source code to be re-generated, so I think informing the user to rebuild the program should be enough to resolve this issue.

Works for me :)
