### ISSUE TITLE
Anchor build fails with:  error: no such command: `+solana` 

### ISSUE THREAD

**Issue by ilmari-h** [coral-xyz/anchor#3296]
Running `anchor build` fails with:

``` error: no such command: `+solana` Cargo does not handle `+toolchain` directives. Did you mean to invoke `cargo` through `rustup` instead?```

Following the installation instructions here: https://solana.com/docs/intro/installation

Program versions:
- anchor-cli 0.30.1
- solana-cli 1.18.25
- rustup toolchain: 1.79.0-x86_64-unknown-linux-gnu (default)
- rustc 1.81.0

**Comment by acheroncrypto** [comment]
Does https://github.com/coral-xyz/anchor/issues/3096#issuecomment-2241129355 help? Closing as duplicate.
