### ISSUE TITLE
Documentation Update Suggestion for Anchor Installation Issues.

### ISSUE THREAD

**Issue by yhoungdev** [coral-xyz/anchor#3300]
###  Issue with --locked Flag in Cargo Install: Suggesting Documentation Update 

Dear Anchor Team,

I hope this message finds you well.

For the past three days, I have encountered a persistent issue while attempting to install and set up Anchor on my x86_64 Linux system using both avm and the pre-built binary options. Unfortunately, none of these methods resolved the problem.

Upon further investigation, I discovered that the issue arises from an API change introduced in Rust 1.80.0. As a result, I would like to suggest an update to the documentation to address this issue and provide guidance for users facing similar challenges.

#### WORK AROUND 

When attempting to install Anchor using the following commands:

``` cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli --locked ```  
 
 or this 
 
 ``` cargo install --git https://github.com/coral-xyz/anchor avm --locked --force ``` 

I encountered the following error:

👇👇👇

``` 



type annotations needed for Box<_>
  --> /home/whoami/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.29/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate time caused by an API change in Rust 1.80.0; update time to version >=0.3.35 by calling cargo update
   Compiling zstd-safe v5.0.2+zstd.1.5.2
   Compiling bitflags v1.3.2
   Compiling unicode-segmentation v1.10.1
For more information about this error, try rustc --explain E0282.
error: could not compile time (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

```

Due to the API change in Rust 1.80.0

To successfully install Anchor, I recommend executing the following command without the --locked flag:

``` cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli ``` 

#### REFERENCE 

For more details, please refer to the following link: [Anchor Issue #3126](https://github.com/coral-xyz/anchor/issues/3126#issuecomment-2301387968).

Thank you for considering this suggestion. I believe updating the documentation will greatly assist users in resolving similar installation issues.

**Comment by acheroncrypto** [comment]
Thanks for creating this issue, but this problem has already been fixed in https://github.com/coral-xyz/anchor/pull/3143. We just need a new release (https://github.com/coral-xyz/anchor/pull/3259), but that's currently blocked by external reasons.

We're also planning adding binaries to releases and defaulting `avm install` to install those prebuilt binaries.

**Comment by yhoungdev** [comment]
Awesome 👌

**Comment by yhoungdev** [comment]
Looking forward to that
