### ISSUE TITLE
`anchor idl fetch` fails for legacy IDLs

### ISSUE THREAD

**Issue by ngundotra** [coral-xyz/anchor#3302]
For example:
```bash
$ anchor idl fetch -o tmp.json --provider.cluster mainnet compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq
Error: unknown variant `publicKey`, expected one of `bool`, `u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `f32`, `u64`, `i64`, `f64`, `u128`, `i128`, `u256`, `i256`, `bytes`, `string`, `pubkey`, `option`, `vec`, `array`, `defined`, `generic` at line 1 column 1839
```

I think this is an issue with legacy IDLs. Maybe `anchor idl convert` to download legacy idls before converting?

**Comment by acheroncrypto** [comment]
It feels like modifying/converting the IDL might be confusing since it's not actually what's on-chain. Should we just output the IDL as a string without checking if it's a valid IDL?
