### ISSUE TITLE
`anchor idl convert` missing --program-id option

### ISSUE THREAD

**Issue by ngundotra** [coral-xyz/anchor#3303]
Trying to convert legacy IDLs that are missing `programId` is quite annoying.

For example, trying to convert the IDL of program `compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq` results in the following
```bash
$ anchor idl convert compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq_idl.json -o tmp.json    
Error: Program id missing in `idl.metadata.address` field
```

I wish there was way to manually set these overrides in the CLI

**Comment by acheroncrypto** [comment]
Great idea! We should be able to add this feature.
