### ISSUE TITLE
Can switch from yarn to pnpm?

### ISSUE THREAD

**Issue by lispking** [coral-xyz/anchor#3306]
Can you switch from yarn to pnpm? The installation speed of yarn is still relatively slow, which is not very user-friendly for the overall user experience.

**Comment by acheroncrypto** [comment]
Yes, you can switch to `pnpm`. Someone mentioned they made it work using `pnpm` and `bun` in https://github.com/coral-xyz/anchor/issues/3080#issuecomment-2329363893.

**Comment by lispking** [comment]
The meaning is that "anchor init xxx" should be replaced during the process, rather than waiting for the environment to be ready before making the change.

**Comment by lispking** [comment]
After a preliminary look at the code, it seems that there might be significant changes needed.

**Comment by acheroncrypto** [comment]
> The meaning is that "anchor init xxx" should be replaced during the process, rather than waiting for the environment to be ready before making the change.

You can pass in `--no-install` to skip installing the JS dependencies.

**Comment by arihantbansal** [comment]
I think this should be solved by #3328

**Comment by acheroncrypto** [comment]
Yeah, as the previous comment mentioned, you'll be able to run:

```
anchor init <NAME> --package-manager pnpm
```
