### ISSUE TITLE
compilation failed with symbol multiply defined! failed to load bitcode of module "program nane-xxx"

### ISSUE THREAD

**Issue by SpringChiu** [coral-xyz/anchor#3314]
when I import solana anchor program's instruction, compilation failed with error info:
those are my code:
```rust
use solana_vault::instruction as solana_vault_instruction;
```

those are error info:
```
warning: Linking globals named 'entrypoint': symbol multiply defined!

error: failed to load bitcode of module "solana_vault-91162013c3821f80.solana_vault.c7fe4af8e94c9c31-cgu.0.rcgu.o":
```

**Comment by acheroncrypto** [comment]
You can fix this by enabling either the `cpi` or the `no-entrypoint` feature of the external program crate you're using. For example:

```toml
[dependencies]
solana-vault = { version = "0.1.0", features = ["cpi"] }
```

You can also avoid adding programs for CPI as a dependency by using [`declare_program!`](https://github.com/coral-xyz/anchor/pull/2857).

**Comment by SpringChiu** [comment]
> You can fix this by enabling either the `cpi` or the `no-entrypoint` feature of the external program crate you're using. For example:
> 
> ```toml
> [dependencies]
> solana-vault = { version = "0.1.0", features = ["cpi"] }
> ```
> 
> You can also avoid adding programs for CPI as a dependency by using [`declare_program!`](https://github.com/coral-xyz/anchor/pull/2857).

Thanks! I add feature of `no-entrypoint` and it compiled success
