### ISSUE TITLE
[Suggestion]: Add anchor-gen and support it.

### ISSUE THREAD

**Issue by SushantChandla** [coral-xyz/anchor#3316]
One common issue I’ve noticed when building on Solana is the frequent version compatibility problems. For instance, if I have an AMM and want to integrate some of Raydium’s code into my program, I often need to downgrade to the Solana and Anchor versions that Raydium uses. This makes Cross-Program Invocation (CPI) very challenging.

I discovered that the [anchor-gen](https://github.com/saber-hq/anchor-gen) package by Saber HQ can help solve this issue. It allows users to generate a client for CPI that matches the specific Solana and Anchor versions they're using. I believe this feature would be a great addition to the official Anchor repository, and Anchor should manage it going forward.

In its current state, the anchor-gen project doesn’t fully support the latest Anchor versions, but I think integrating this functionality into Anchor would be a great move for the ecosystem.

**Comment by acheroncrypto** [comment]
Anchor supports this feature natively since v0.30, see:

- https://www.anchor-lang.com/release-notes/0.30.0#dependency-free-program-declaration
- https://docs.rs/anchor-lang/0.30.1/anchor_lang/macro.declare_program.html
- https://github.com/coral-xyz/anchor/pull/2857
