### ISSUE TITLE
 cargo install error. failed to update submodule `examples/cfo/deps/openbook-dex`

### ISSUE THREAD

**Issue by z-hanwen** [coral-xyz/anchor#3387]
when I called " cargo install --git https://github.com/coral-xyz/anchor avm --locked --force", 
I had tried to git cloen https://github.com/openbook-dex/program, but it indicated me it was a empty repository. I could access github normally. what can I do. It's killing me. The following is the error message.

cargo install --git https://github.com/coral-xyz/anchor avm latest  --locked --force
    Updating git repository `https://github.com/coral-xyz/anchor`
    Updating git submodule `https://github.com/openbook-dex/program`
error：The requested URL returned error: 500 (curl_result = 22, http_code = 500, sha1 = 7d1d41538417aa8721aabea9503bf9d99eab7cc4)
error：Unable to find 7d1d41538417aa8721aabea9503bf9d99eab7cc4 under https://gitclone.com/github.com/openbook-dex/program
Cannot obtain needed object 7d1d41538417aa8721aabea9503bf9d99eab7cc4

error: failed to update submodule `examples/cfo/deps/openbook-dex`

Caused by:
  failed to fetch submodule `examples/cfo/deps/openbook-dex` from https://github.com/openbook-dex/program

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/openbook-dex/program' '+7d1d41538417aa8721aabea9503bf9d99eab7cc4:refs/commit/7d1d41538417aa8721aabea9503bf9d99eab7cc4'` (exit status: 128)

**Comment by acheroncrypto** [comment]
Looks like a GitHub API issue, so it resolved itself?

**Comment by z-hanwen** [comment]
> Looks like a GitHub API issue, so it resolved itself?

sorry for replying to you so late, I didn't install anchor in the recommended way. Because I didn't know how to solve this issue even I chatgpt it. I install anchor by building the source code then.
