### ISSUE TITLE
lock file version 4 requires `-Znext-lockfile-bump`

### ISSUE THREAD

**Issue by 619** [coral-xyz/anchor#3393]
I get lock file version 4 requires `-Znext-lockfile-bump` when I try to run anchor build. I've tried everything chatGPT has suggested and it's still there.

**Comment by dhl** [comment]
It seems like the newer Rust nightlies have bumped Cargo lock file to version 4.

You can workaround this problem by downgrading the changing the lock file version from 4 to 3.

**Comment by acheroncrypto** [comment]
Thanks for creating the issue. Please see the answer in https://github.com/coral-xyz/anchor/issues/3392#issuecomment-2508412018.

**Comment by nicthatcher** [comment]
> It seems like the newer Rust nightlies have bumped Cargo lock file to version 4.
> 
> You can workaround this problem by downgrading the changing the lock file version from 4 to 3.

How do you change the lock file version on the command line?
