### ISSUE TITLE
Hide Instruction Name on Solscan

### ISSUE THREAD

**Issue by halogen857** [coral-xyz/anchor#3407]
Hi, I can't login to Discord so asking here.

Is there a way to hide Instruction names from appearing on Solscan when using Anchor?

For example, this is how it appears on Solscan. Notice `"Program log: Instruction: MyInstructionName",`. I would like to hide this. I could obscure it with a fake name, but I notice some programs hide it completely. So wondering if possible with Anchor. 
```
[
  "Program ZZZOOOOOOOOOO invoke [1]",
  "Program log: Instruction: MyInstructionName",
  "Program ZZZOOOOOOOOOO consumed 3654 of 200000 compute units",
  "Program ZZZOOOOOOOOOO success"
]
```

**Comment by acheroncrypto** [comment]
You can build your program with `no-log-ix-name` feature enabled, e.g.

```
anchor build -- --features no-log-ix-name
```
