### ISSUE TITLE
bug: anchor CLI does not support agave stable versioning

### ISSUE THREAD

**Issue by Arrowana** [coral-xyz/anchor#3431]
Problem:
anchor doesn't support agave install versioning in cli

https://solana.com/docs/intro/installation#install-the-solana-cli
this will install `stable-{commit}` but this leads to a panic on https://github.com/coral-xyz/anchor/blob/afcbaedac69d23544cad177acfbe10b325cf0a06/cli/src/lib.rs#L638

agave-install list
1.18.18
stable-20a8749f7a71ca230bec4ecdbeb292e3d8cd399d
1.18.26
2.0.19

Workaround: Don't install "stable" and cleanup the folder

Possible fix: 
- agave not to install latest stable with this odd folder format but use the release tag
- consuming agave-install list should not panic on non valid version

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/3432
