### ISSUE TITLE
bug : Anchor IDL address misalignment.

### ISSUE THREAD

**Issue by shichen1iu** [coral-xyz/anchor#3438]
When I was testing my code with TS, I found that my Anchor test code runs fine initially, but after a while, when I run anchor test --skip-deploy (without --skip-build), it throws an error.
![image](https://github.com/user-attachments/assets/38c0222b-340b-4cdd-9f75-95153221da27)
At this point, when I check the address in target/idl, I find that the address is not the address of my program, but instead the address of the admin in a mod defined in the lib.
![image](https://github.com/user-attachments/assets/669d3bdb-b3f1-4bc4-86a9-980af08e6b01)
![image](https://github.com/user-attachments/assets/037ca4f6-b2bd-44d3-b59f-2fe91fbfafb5)
When I manually change the address in the IDL back to the correct pay... address, and then test using anchor test --skip build --skip-deploy, everything works fine. 
Therefore, I think this is a bug with anchor build.

**Comment by acheroncrypto** [comment]
This doesn't look like a bug to me because your program should only use `declare_id!` once. For declaring other public keys, like the one used in the `admin` module above, you should use the `pubkey!` macro instead (see https://www.anchor-lang.com/release-notes/0.30.1#pubkey-macro).
