### ISSUE TITLE
 We should add Docker images for anchors

### ISSUE THREAD

**Issue by xhynever** [coral-xyz/anchor#3442]
At this time, not using Docker is too outdated. Of course, it's also my technical weakness. I spent half a day unable to solve the problem of anchor build failure.
We should consider the network and environmental issues that prevent the anchor framework from being used by more people. So adding Docker images is a better measure。
The new image should be able to independently test and run Solana contracts through the Anchor framework.

**Comment by acheroncrypto** [comment]
We already have a Docker image [backpackapp/build](https://hub.docker.com/r/backpackapp/build). It's also being used for verifiable builds if you pass the `--verifiable` flag to `anchor build`.
