### ISSUE TITLE
Provider env is not available on browser.

### ISSUE THREAD

**Issue by cxp-13** [coral-xyz/anchor#3449]
I want to query PDA account information in the front-end project, similar to the testing code in the anchor project.
```
@coral-xyz_anchor.js?v=4aed2eaf:7116 Uncaught (in promise) Error: Provider env is not available on browser.
    at _AnchorProvider.env (@coral-xyz_anchor.js?v=4aed2eaf:7116:13)
    at fetchShares (Home.tsx:33:48)
    at Home.tsx:55:5
```
frontend code:
```
'use client'
import React, { useState, useEffect } from 'react'
import { OrbitLen } from "../assets/orbit_len";
import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  Transaction,
  sendAndConfirmTransaction,
} from "@solana/web3.js";


const Home = () => {
  const [rayShares, setRayShares] = useState({
    liability_shares: '0',
    asset_shares: '0'
  })

  const [wifShares, setWifShares] = useState({
    liability_shares: '0',
    asset_shares: '0'
  })


  const RayBank = new PublicKey("DeNFenr4diuZP8hTYeW8Rw9C7dm5Z5DSu8URkSpt8Tmj");
  const WIFBank = new PublicKey("GBmyafm37crVXMZuUYHYZ8d73gbyjxpEeXqCbM8Np9hy");
  // RayBank: DeNFenr4diuZP8hTYeW8Rw9C7dm5Z5DSu8URkSpt8Tmj, WIFBank: GBmyafm37crVXMZuUYHYZ8d73gbyjxpEeXqCbM8Np9hy
  useEffect(() => {
    const fetchShares = async () => {
      // 设置 Anchor provider
      anchor.setProvider(anchor.AnchorProvider.env());

      // 获取 OrbitLen 程序实例
      const program = anchor.workspace.OrbitLen as Program<OrbitLen>;
      ```

**Comment by acheroncrypto** [comment]
As its documentation suggests, the `AnchorProvider.env` method is only intended to be used with `node` because it expects `ANCHOR_PROVIDER_URL` environment variable to be set:

https://github.com/coral-xyz/anchor/blob/72c7e09538f38fa98de56caeee6e8c030c8b66b2/ts/packages/anchor/src/provider.ts#L107-L113

This environment variable is set when necessary in `anchor` CLI, but it won't exist in browsers (without manually overriding it).

In browsers, you can create an `AnchorProvider` instance by:

```ts
const provider = new AnchorProvider(connection, wallet);
```

**Comment by cxp-13** [comment]
Yes It have been work. but still have problems for instance a program case. There have any exmple with anchor client using by front-end?
```
const program = anchor.workspace.OrbitLen as Program<OrbitLen>;
```
console error:
```
TypeError: Cannot read properties of undefined (reading 'OrbitLen')
```


> As its documentation suggests, the `AnchorProvider.env` method is only intended to be used with `node` because it expects `ANCHOR_PROVIDER_URL` environment variable to be set:
> 
> https://github.com/coral-xyz/anchor/blob/72c7e09538f38fa98de56caeee6e8c030c8b66b2/ts/packages/anchor/src/provider.ts#L107-L113
> 
> This environment variable is set when necessary in `anchor` CLI, but it won't exist in browsers (without manually overriding it).
> 
> In browsers, you can create an `AnchorProvider` instance by:
> 
> ```ts
> const provider = new AnchorProvider(connection, wallet);
> ```
