### ISSUE TITLE
lang, ts: Remove deprecated state feature flag

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#449]
https://github.com/project-serum/anchor/pull/446 introduces a feature flag to maintain backwards compatibility for state account addresses for Anchor v0.6.0 and below. Before releasing v1.0.0 we should remove it.

**Comment by Henry-E** [comment]
Can't believe that `state` managed to hang around for this long, finally closed by https://github.com/coral-xyz/anchor/pull/2285
