### ISSUE TITLE
Anchor dapp fails to build on mac

### ISSUE THREAD

**Issue by cryptofie** [coral-xyz/anchor#481]
Anchor looks up the programs in the program directory when doing a build/test. On Mac, there is a system directory called .DS_Store which anchor picks and tries to find src/lib.rs and crashes.

Anchor should ignore the hidden directories when looking up for programs

**Comment by acamill** [comment]
Hot damn. Thanks

**Comment by acheroncrypto** [comment]
This issue hasn't been reported in a long time so I'm closing it but feel free to reopen if you can reproduce the problem.
