### ISSUE TITLE
lang: Accounts structs should allow references to account infos

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#512]
Currently the accounts context requires taking ownership of a clone of an account info. This is less efficient and particularly wasteful w.r.t. stack size.

**Comment by acheroncrypto** [comment]
`AccountInfo`s of the wrapper types are now references(https://github.com/coral-xyz/anchor/pull/2656) but it's not reference for `AccountInfo` itself because derive proc macro doesn't allow changing the owned type to a reference.
