### ISSUE TITLE
Anchor Rust Client Doesn't Allow Skipping Preflight Checks

### ISSUE THREAD

**Issue by bonedaddy** [coral-xyz/anchor#542]
# Overview

When using the `RequestBuilder` to construct a transaction to a program rpc handler, you are unable to skip preflight checks. 

# Solution

Expand the `options` method to enable specifying if you want to skip preflight checks, similar to how it is done with the js/ts client.

**Comment by Henry-E** [comment]
Not sure if still an issue or not. But this seems like something that probably got added
