### ISSUE TITLE
Provider.env()'s wallet doesn't use the Anchor.toml path when testing

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#560]
When running `anchor test` it should use the Anchor.toml value (or the --provider.wallet override).

**Comment by hetdagli234** [comment]
Hey, is this still open, I want to take this up.

**Comment by hetdagli234** [comment]
Okay, I think this is resolved by https://github.com/coral-xyz/anchor/pull/718, hence this can be closed.

**Comment by acheroncrypto** [comment]
Yes, resolved in https://github.com/coral-xyz/anchor/pull/718
