### ISSUE TITLE
easy seeds generations

### ISSUE THREAD

**Issue by WrRaThY** [coral-xyz/anchor#602]
hey

I've created a simple utility for nicer seeds generation:

```
import {utils} from "../index";

/**
 * can be used like that:
 *     const [pda, bump] = await PublicKey.findProgramAddress(
 *       Seeds.from(signer.publicKey, "input"),
 *       this.program.programId
 *     )
 * or like that:
 *     const [pda, bump] = await PublicKey.findProgramAddress(
 *       [signer.publicKey.toBuffer(), ...Seeds.from("input")],
 *       this.program.programId
 *     )
 */
export function from(...stringSeeds: (string | PublicKey)[]): Buffer[] {
  return stringSeeds.map(it => {
    if (typeof it === 'string') {
      return Buffer.from(utils.bytes.utf8.encode(it));
    } else {
      return it.toBuffer();
    }
  })
}
```

would it be good to merge it to master or do you prefer not to have such syntactic sugar?

**Comment by WrRaThY** [comment]
@armaniferrante sounds ok?

**Comment by WrRaThY** [comment]
anyway, PR is out there. lets see how it goes ;p 
https://github.com/project-serum/anchor/pull/603

**Comment by WrRaThY** [comment]
@armaniferrante any idea why it has been stuck on the "Travis CI - Branch" step for over half a day now?
https://github.com/project-serum/anchor/pull/611 
The build was successful

**Comment by armaniferrante** [comment]
> @armaniferrante any idea why it has been stuck on the "Travis CI - Branch" step for over half a day now?
> #611
> The build was successful

I wouldn't worry about it. I think it's because it's a PR from outside the repo's org.
