### ISSUE TITLE
Support unnamed structs in IDL

### ISSUE THREAD

**Issue by fanatid** [coral-xyz/anchor#607]
In continue of #605.

How :anchor: should support unnamed structs ([syn::Feilds::Unnamed](https://docs.rs/syn/1.0.74/syn/enum.Fields.html#variant.Unnamed))? I see two ways:
1. Add arrays support to IDL.
2. Add a new derive macro (`AnchorType` for example) which will add fields names to such structs:
```rust
#[derive(AnchorType)]
struct Z(#[field(name = x)] u64, #[field(name = y)] u64);
```

Additional derive macro looks better for me because it adds verbosity to JS and makes things more clear.

**Comment by armaniferrante** [comment]
Arrays are currently supported in the IDL. Is there anything in the current implementation lacking for your use case? For example, generic lengths can't be used at the moment.

**Comment by fanatid** [comment]
I did not know that arrays are supported. Looks like I need to check IDL again :smile:

**Comment by archseer** [comment]
It would be great if transparent newtype structs were at least supported, for example:

```rust
#[derive(
    Clone, Copy, Default, PartialOrd, Ord, PartialEq, Eq, AnchorSerialize, AnchorDeserialize,
)]
#[repr(transparent)]
pub struct Address(pub [u8; 20]);
```

This compiles fine and generates an IDL with `Address` references, but the `Address` type itself is missing. `anchor test` will then run and report "success! 0 test cases" when it fails to parse the IDL 😄

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2824.
