### ISSUE TITLE
lang: Number in method name causes incorrect serialization

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#736]
`my_method_2` doesn't serialize properly when testing with javascript. This is likely because the IDL's conversion to camelCase makes it ambiguous as to whether the name is `my_method2` vs `my_method_2`. Fix should be to use `snake_case` in the IDL.

**Comment by paul-schaaf** [comment]
@armaniferrante just to make sure I understand correctly, are you saying that the IDL and therefore the clients should just use `snake_case` and we remove the conversion to `camelCase`?

**Comment by armaniferrante** [comment]
This is addressed by https://github.com/project-serum/anchor/pull/912.

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2824.
