### ISSUE TITLE
Issue serializing enum related types

### ISSUE THREAD

**Issue by soualid** [coral-xyz/anchor#806]
Hello,

I am trying to implement a [feature in metaplex](https://github.com/metaplex-foundation/metaplex/pull/399) that requires the usage of an enum  defined this way:

```
#[derive(Clone)]
pub enum Config {
    V1 { config: ConfigV1 },
    V2 { config: ConfigV2 },
}

#[account]
#[derive(Default)]
pub struct ConfigV1 {
    // ...
}

#[account]
#[derive(Default)]
pub struct ConfigV2 {
    // ...
}
```

Here's how it's serialized in anchor generated IDL:

```
{
  "name": "Config",
  "type": {
    "kind": "enum",
    "variants": [
      {
        "name": "V1",
        "fields": [
          {
            "name": "config",
            "type": {
              "defined": "ConfigV1"
            }
          }
        ]
      },
      {
        "name": "V2",
        "fields": [
          {
            "name": "config",
            "type": {
              "defined": "ConfigV2"
            }
          }
        ]
      }
    ]
  }
}
```

Unfortunately, the related `ConfigV1` and `ConfigV2` types are not serialized along the base enum. Which cause the following error at runtime: 

```
IdlError: Type not found: {"name":"config","type":{"defined":"ConfigV1"}}
```

Am I missing something? Shouldn't the related type be seralized because they are referenced by the enum, but also because they are tagged with `#[account]`? Since I am quite new to this ecosystem, I may be missing something obvious, sorry if I am. 🙂 

If you need more context, here is the related pull request in Metaplex: https://github.com/metaplex-foundation/metaplex/pull/399#discussion_r715390786

Many thanks for reading!

**Comment by gdoteof** [comment]
i see this is added as a bug; I am having the same issue.  it is driving me insane; is there a work around?

**Comment by gdoteof** [comment]
I’d have to see the rest of your code to be sure but my PR #1343 fixes it for me
