### ISSUE TITLE
How to deploy smart contract using anchor deploy command

### ISSUE THREAD

**Issue by RichGao** [coral-xyz/anchor#811]
Hello 
I am a beginner with solana. Of course, I've written smart contract using anchor framework, and I am trying to deploy smart contract on testnet using it.
When I build smart contract by executing "anchor build" command, it was very perfet.
The first screenshot is anchor.toml config detail.
![image](https://user-images.githubusercontent.com/33213237/135303559-a04a2c46-3c8a-4f86-b787-d5064cc4d070.png)
This screenshot is built ABI json detail.
![image](https://user-images.githubusercontent.com/33213237/135303641-a0a73dfc-3d28-4d0d-a5c9-31f8772efbd9.png)
But if I try to execute "anchor deploy" command in the terminal, the following error is occurring continuously.
![image](https://user-images.githubusercontent.com/33213237/135303769-8d760db7-0745-4e8b-9419-48d5ebb3ed44.png)

OS is ubuntu 20.04 x64 version and it is running in VM ware player now.

I need anyone help asap.
Thanks

**Comment by acheroncrypto** [comment]
Could be either the wallet keypair file is missing or there is a mismatch between program names.
