### ISSUE TITLE
Mild possibility of #[derive(Accounts)] name clashes

### ISSUE THREAD

**Issue by cqfd** [coral-xyz/anchor#819]
Ran into a funny bug in the #beginner-questions discord: someone was using a accounts struct with a `program_id: AccountInfo<'info>` field. This breaks the derive macro output, because the generated `try_accounts` impl is already using the name `program_id` (you'd get a similar error if you used a field called `accounts` or `ix_data`).

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2464
