### ISSUE TITLE
Provide more information on errors

### ISSUE THREAD

**Issue by rav3nh0lm** [coral-xyz/anchor#882]
I believe error message could be more detailed, making debugging easier. I believe this would definitely improve the learning curve for many incoming solana devs.

I believe this error originated from supplying a token-account of a token of type "A", whereas the token type should be "B" (enforced through macros?). I think it'd be good to make this error more explicit, and perhaps have case distinctions based on what the error actually is (the above is just an educated guess).

```
{"code":143,"msg":"A raw constraint was violated"}
ProgramError: 
    at Function.parse (/Users/davidal/imo-launchpad/example-server/node_modules/@project-serum/anchor/src/error.ts:41:14)
    at Object.rpc [as exchangeUsdcForRedeemable] (/Users/davidal/imo-launchpad/example-server/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 143,
  msg: 'A raw constraint was violated'
}
```

**Comment by yasuoyuhao** [comment]
Hello, friends who have the same mistake.

My solution is as follows, which is to use an ATA account.

Use `Token.getAssociatedTokenAddress`
Get an ATA account

Then use
`Token.createAssociatedTokenAccountInstruction`

And send the transaction and wait for a while

like this:
```js
const userWatermelon = await Token.getAssociatedTokenAddress(
    ASSOCIATED_TOKEN_PROGRAM_ID,
    TOKEN_PROGRAM_ID,
    watermelonMint,
    program.provider.wallet.publicKey,
  );

  // Get the instructions to add to the RPC call
  const createUserWatermelonInstr =
    Token.createAssociatedTokenAccountInstruction(
      ASSOCIATED_TOKEN_PROGRAM_ID,
      TOKEN_PROGRAM_ID,
      watermelonMint,
      userWatermelon,
      program.provider.wallet.publicKey,
      program.provider.wallet.publicKey,
    );
  const createUserWatermelonTrns = new anchor.web3.Transaction().add(
    createUserWatermelonInstr,
  );
  await provider.send(createUserWatermelonTrns);

  console.log(`User Watermelon: ${userWatermelon.toString()}`);
  await sleep(secTrans * 2000);
```

**Comment by pistachiomatt** [comment]
For anyone else playing along, I had this bug when running Candy Machine. The issue was the treasury/deposit account needed to be funded for the first time.

**Comment by fanatid** [comment]
@rav3nh0lm do you have any proposal on how to provide more information on errors?

You also can use custom errors (through `@`) if anchor errors are not enough.

**Comment by sadsnake42** [comment]
@fanatid 
Perhaps it is worth implementing more complex enumeration types for errors so that we can add context and output it through the logs?
If I remember the implementation correctly, then there is no big problem, ralize support for more complex types, transfer the error number to attributes and process the fields using formating

```rust
#[error]
enum ErrorCode {
   #[msg("Wrong constraint for {0} account with condition {1}"), code(143)]
    ConstraintError(Pubkey, &'static str),
}
```
At the moment, when you have 14 accounts and 30+ different constraints, the most working debugging option is to comment them one at a time in order to understand which particular account has broken.

**Comment by devDesu** [comment]
It would be nice if debug flag for the ```new Program(idl)``` were available. Providing debug flag/option with logging level should enable console logging for all events (as for me, I patch anchor npm-package, adding console.log on this line https://github.com/project-serum/anchor/blob/1319dc65d6f8aa791f5121e565ab95129d72795d/ts/src/program/event.ts#L178)
