### ISSUE TITLE
idl generation does not support duplicate module name

### ISSUE THREAD

**Issue by dovahcrow** [coral-xyz/anchor#899]
Currently, anchor uses the module name as the key to store the module here: https://github.com/project-serum/anchor/blob/master/lang/syn/src/parser/context.rs#L10. This forbids modules with the same name in a project.
To make it worse, there's no error raised during the process which makes it super hard to debug without hacking the code in anchor.

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2824.
