### ISSUE TITLE
enum reprs are missing in idl

### ISSUE THREAD

**Issue by dovahcrow** [coral-xyz/anchor#904]
Enums with different reprs are all treated as u8 repr when the frontend loads the account data using anchor-ts, due to the repr information are not included in the IDL file. 

The error message is also very confusing as it contains minimal information about the root cause of the bug: Anchor is trying to parse the enum as u8 but due to the size difference of different reprs, Anchor reads data from wrong places and gets an unexpected variant.
![image](https://user-images.githubusercontent.com/998606/138144020-38ee0eab-d839-4602-99b5-f9d7de8fc0d0.png)

P.S.  the stack trace is inaccurate as well, which makes debugging anchor errors very unpleasant.

**Comment by bausano** [comment]
I encountered this issue when storing an array of enums with zero copy account. In my case, even though the program writes for example `Bar::A` to the second index, the anchor-ts can only understand first index, everything else is parsed as `Bar::None` (in another words, the first variant with discriminant of 0).

```rust
#[derive(Accounts)]
struct Endpoint<'info> {
  foo: AccountLoader<'info, Foo>
}

#[account(zero_copy)]
struct Foo {
  // .. other fields
  bar: [10; Bar],
  // ... other fields
}

enum Bar {
  None,
  A { inner: .. }, // if inner is not repr(packed), then the anchor-ts incorrectly calculates layout size
  B { inner: .. },
  Never { padding: [u8; N] } // is this safe to do with zero copy?
}
```

Also, the representation for my enum has layout with a span of -1 if that is relevant:

```
  WrappedLayout {
    span: -1,
    property: 'bar',
    layout: Structure {
      span: -1,
      property: undefined,
      fields: [Array],
      decodePrefixes: false
    },
    decoder: [Function (anonymous)],
    encoder: [Function (anonymous)]
  }
```

**Comment by acheroncrypto** [comment]
Added in https://github.com/coral-xyz/anchor/pull/2824.
