### ISSUE TITLE
npm: Invalid anchor version

### ISSUE THREAD

**Issue by fanatid** [coral-xyz/anchor#925]
npm package 0.18.0 have invalid anchor binary :disappointed: 

```bash
$ npm ls @project-serum/anchor-cli
solana-protocol@0.2.0 /home/kirill/projects/x-project
└── @project-serum/anchor-cli@0.18.0

$ npx anchor --version
Package binary version is not correct. Expected "anchor-cli 0.18.0", found "anchor-cli 0.17.0".
Trying globally installed anchor.
Failed to get version of global binary: Error: spawnSync undefined/anchor ENOENT
```

**Comment by lsbyerley** [comment]
```
npx anchor --version
Only x86_64 / Linux distributed in NPM package right now.
Trying globally installed anchor.
Globally installed anchor version is not correct. Expected "anchor-cli 0.18.2", found "anchor-cli 0.18.0".
```

Not entirely sure how I fix this?

**Comment by armaniferrante** [comment]
> ```
> 
> npx anchor --version
> 
> Only x86_64 / Linux distributed in NPM package right now.
> 
> Trying globally installed anchor.
> 
> Globally installed anchor version is not correct. Expected "anchor-cli 0.18.2", found "anchor-cli 0.18.0".
> 
> ```
> 
> 
> 
> Not entirely sure how I fix this?

The npm package is for Linux only. Need to use cargo install with v0.18.0

**Comment by LUK3ARK** [comment]
> Can't found the tag v0.18.2 using `cargo install`. Got this error:
> 
> ```
> cargo install --git https://github.com/project-serum/anchor --tag v0.18.2 anchor-cli --locked
> 
>     Updating git repository `https://github.com/project-serum/anchor`
> error: failed to find tag `v0.18.2`
> ```

I am also getting this error :(

**Comment by Hugooboutot** [comment]
I am getting this error ! 

cargo install --git https://github.com/project-serum/anchor anchor-cli --locked

    Updating git repository `https://github.com/project-serum/anchor`
error: the given reference name 'refs/heads/' is not valid; class=Reference (4)

**Comment by melchermaxwell** [comment]
If you tried installing Anchor with npm on a non-x86_64 Linux and it failed, then you installed from source successfully but  got the errors above ->
Try uninstalling the npm version with:
`npm uninstall -g @project-serum/anchor-cli`
Then try using the Anchor CLI.  Should work without conflict.

**Comment by ngundotra** [comment]
@melchermaxwell this worked for me on MacOS... thank you!

**Comment by S-Burns** [comment]
> If you tried installing Anchor with npm on a non-x86_64 Linux and it failed, then you installed from source successfully but got the errors above -> Try uninstalling the npm version with: `npm uninstall -g @project-serum/anchor-cli` Then try using the Anchor CLI. Should work without conflict.

Using `npm uninstall -g @project-serum/anchor-cli` with the caveat ....then installing and using the AVM aka Anchor Version Manager, running the 'avm install latest' ... then 'avm use latest' ... then restarting the terminal, worked for me on Ubuntu WSL / Windows Subsystem Linux, .

**Comment by Suraj1001singh** [comment]
C:\WINDOWS\system32>npx anchor --version
Only x86_64 / Linux distributed in NPM package right now.
Trying globally installed anchor.
Failed to get version of global binary: Error: spawnSync \Users\draco\AppData\Roaming\npm/anchor ENOENT


hey help me out, i new to solana , I am getting above error ever installing cli globally by using cmd
npm i -g @project-serum/anchor-cli
still getting an error.

**Comment by fanatid** [comment]
`anchor-cli` works only on linux x86-64

**Comment by S-Burns** [comment]
Need to use WSL

**Comment by IntikhabKhursheed** [comment]
Error: Anchor version not set. Please run `avm use latest`.
