### ISSUE TITLE
lang:Introduce AccountMut type and remove DerefMut from Account

### ISSUE THREAD

**Issue by paul-schaaf** [coral-xyz/anchor#980]
As discussed in discord (https://discord.com/channels/889577356681945098/891724485177245717/905545460566065192)

Right now `Account` implements `DerefMut` even if it is not annotated with `#[account(mut)]`. Ideally, it should not be possible to get a mutable reference to the data in `Account` if it's not annotated with `#[account(mut)]`. But this is not possible to do without a new type.

**Solution**

Add a new `AccountMut` type that implements `DerefMut` and remove `DerefMut` from `Account`. Deprecate `#[account(mut)]`

**Comment by paul-schaaf** [comment]
There are other accounts that should be changed too. e.g. Loader -> LoaderMut

**Comment by akutruff** [comment]
+1 - Just hit this issue myself for what its worth.

**Comment by Henry-E** [comment]
I like the idea in theory but i think the failing to add `mut` to an account that gets changed is more of a minor inconvenience than something which warrants a major lang change. Still keeping an eye out for other possible solutions that could detect the issue and error at compile time.
